### PR TITLE
Update site-post-permissions.md

### PR DESCRIPTION
**Pull request by kashiftahir**
Delegated permissions arent supported for this endpoint.

### CODE REVIEW

**Comment by BarryShehadeh** [comment]
What about Beta?

**Review by BarryShehadeh — COMMENTED** [review]
What about beta?

**Comment by kashiftahir** [comment]
> What about beta?

Beta doesnt have the doc bug: https://docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&tabs=http

**Comment by BarryShehadeh** [comment]
It's about to get shipped :)
https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/site-post-permissions.md

**Comment by kashiftahir** [comment]
> It's about to get shipped :) https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/site-post-permissions.md
> 
> technically neither v1.0 has it, yet https://docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&tabs=http

Thanks for pointing that out. I sent an email to Laura to revert that change.

**Pull request closed without merging**
