### PR TITLE
Remove unsupported fields from beta and add throttling limits for eDiscovery

### PR DESCRIPTION
**Pull request by SeunginLyu**
- Remove unsupported property (this was never supported and accidentally published "contentQuery" property from 
       - PATCH compliance/legal holds (beta)
       - POST/PATCH security/eDiscoveryCase/hold policy
- Add throttling limit for security/eDiscovery endpoints

### CODE REVIEW

**Review by Danielabom — CHANGES_REQUESTED** [review]
Thank you for working on this PR @SeunginLyu.  I just have one question. Could you confirm that removing this property is only a doc update and does not imply schema changes, or does it?

**Comment by SeunginLyu** [comment]
> Thank you for working on this PR @SeunginLyu. I just have one question. Could you confirm that removing this property is only a doc update and does not imply schema changes, or does it?

- no, we never supported content query for POST/PATCH in the schema
- This PR  corrects the wrongly documented properties

**Review by Danielabom — APPROVED** [review]
Thank you for answering my questions @SeunginLyu. PR approved.

**Comment by SeunginLyu** [comment]
Thanks! @Danielabom for the quick review and the approval. I added the "ready to merge" label.

**Pull request merged**
