### PR TITLE
MS Graph for Intune - repo purge and update

### PR DESCRIPTION
**Pull request by BrucePerlerMS**
Update repo by deleting all intune_* files, then adding only 1712 drop's Intune files. This process will purge all of the churned content with only the current generated content. 

Notes:

Phase 1 – purge all non-current Graph API for Intune files from repo and recreate using only current content

•	Create a new branch, sourced and tracked with Microsoft-graph-docs Staging
•	Delete all intune_* files from both api and resource folders
o	Resources folder
	In repo resources folder total file count: ___ – intune_* files count: 573 
	From 1712 generated content drop, resources folder – file count: 482
•	Difference between repo and 1712 drop: 91
	New total in resources : 1010
o	Api folder
	In repo api folder – total file count: 3387 - intune_* files count:  2515
	From 1712 generated content drop, api folder – file count: 1330
•	Difference between repo and 1712 drop: 1185
	New total in api : 2202
•	Copy into each api and resource folders – all of the generated files from Josh’s 1712 drop
•	Push to Staging and create a PR for just this update

### CODE REVIEW

**Comment by BrucePerlerMS** [comment]
With the build completing, based on a rebuilt repo, we now know that the API ref content is free of outdated files. This completes phase 1 of this process. 
@Lauragra - should we merge this PR, so as to close the phase 1 of this cleanup process?

**Comment by BrucePerlerMS** [comment]
@Lauragra - BTW - testing the TOC against the rebuilt repo shows 719 out of date links - those that go to files no longer in the API ref. These will be removed from the TOC in phase 2 of this process.

**Comment by BrucePerlerMS** [comment]
#sign-off 
@Lauragra - if you're ok with this as completion of phase 1 ...

**Comment by Lauragra** [comment]
Yes, we're good to merge. Please send me the full list of the files that have been deleted. Thanks!

**Comment by BrucePerlerMS** [comment]
@Lauragra - I'm working with Pat Altimore to find a way to extract the deleted files list from this PR. The info is here, just needs to be extracted. I'll be in touch about this.

**Comment by BrucePerlerMS** [comment]
Phase 2 - near complete. All bad links now removed from TOC. I think we should merge to stage and do some spot testing.

**Pull request merged**
