### PR TITLE
Add documentation for delta sync api

### PR DESCRIPTION
**Pull request by hiteshgulia**
Adding documentation for Delta Sync Messaging API

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[cb13725](https://github.com/hiteshgulia/microsoft-graph-docs/pull/4228/commits/cb13725f5a2f7fbde19b2b00402bf2d69492bfb6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-list-messages-delta.md](https://github.com/hiteshgulia/microsoft-graph-docs/blob/addDocumentationForDeltaSyncApi/api-reference/beta/api/channel-list-messages-delta.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903221733564778-4228%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Zj%2Bt6FVSqgEUN7LDvGE2Qkgpt4BpMPxy%2FskVVRNeMzM%3D&st=2019-03-22T17%3A32%3A43Z&se=2019-04-22T17%3A37%3A43Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[6afd455](https://github.com/hiteshgulia/microsoft-graph-docs/pull/4228/commits/6afd455168f9868fb710927e18297bc37f017589)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-list-messages-delta.md](https://github.com/hiteshgulia/microsoft-graph-docs/blob/addDocumentationForDeltaSyncApi/api-reference/beta/api/channel-list-messages-delta.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903221738366801-4228%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=qquSwWrDG78gZxs0OTVeYvqZHr6K%2FyAlHdmNoHkmIDI%3D&st=2019-03-22T17%3A36%3A59Z&se=2019-04-22T17%3A41%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[ed54285](https://github.com/hiteshgulia/microsoft-graph-docs/pull/4228/commits/ed542851d6d1f83583cae5eeeabad423966fab96)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-list-messages-delta.md](https://github.com/hiteshgulia/microsoft-graph-docs/blob/addDocumentationForDeltaSyncApi/api-reference/beta/api/channel-list-messages-delta.md) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/hiteshgulia/microsoft-graph-docs/blob/addDocumentationForDeltaSyncApi/concepts/changelog.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903242313598903-4228%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=W7Y1dBXlotmNfkSC6WP4HKSSzwS2eRQ6GonISCW%2F%2Fgg%3D&st=2019-03-24T23%3A12%3A34Z&se=2019-04-24T23%3A17%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nkramer** [comment]
See also https://github.com/microsoftgraph/microsoft-graph-docs/pull/5113, clarifying what lastModifiedDateTime does

**Comment by Lauragra** [comment]
@nkramer , @clearab, this file doesn't conform to our API reference structure. Do you have a timeline for publishing? If possible, let's use the stub generator tool to output the file in the correct format.

**Comment by Lauragra** [comment]
@clearab , putting this on your radar. Do you have a timeline for enabling this?

**Comment by Lauragra** [comment]
One other thing to mention here - we should update this section of the conceptual topic to indicate that chat messages in a channel are supported: https://docs.microsoft.com/en-us/graph/delta-query-overview?view=graph-rest-beta#supported-resources. @clearab , do we want to do that before we merge this?

**Comment by clearab** [comment]
@Lauragra I updated the delta query article, good catch!

**Pull request merged**
