### PR TITLE
[Doc Improvement][Response code update][3140616]

### PR DESCRIPTION
**Pull request by v-sdhakshina**

### CODE REVIEW

**Review by Meghana-MSFT — APPROVED** [review]
ok

**Review by Wajeed-msft — APPROVED** [review]

**Review by Danielabom — APPROVED** [review]
PR approved.

**Comment by v-sdhakshina** [comment]
@Danielabom I've updated the same changes in Beta doc as well. Request you to please review and approve the PR.

**Comment by Danielabom** [comment]
I did not have any comments on this PR. It was approved. thanks!

**Review by Danielabom — APPROVED** [review]

**Pull request merged**
