### PR TITLE
Adding User properties and enabling transitive Member search in v1.0

### PR DESCRIPTION
**Pull request by anchandaAADGraph**

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[1ce0b1e](https://github.com/anchandaAADGraph/microsoft-graph-docs/pull/3741/commits/1ce0b1e2f6d8c3819717122eeb3a80f1caa7adde)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 21 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[1ce0b1e](https://github.com/anchandaAADGraph/microsoft-graph-docs/pull/3741/commits/1ce0b1e2f6d8c3819717122eeb3a80f1caa7adde)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[1ce0b1e](https://github.com/anchandaAADGraph/microsoft-graph-docs/pull/3741/commits/1ce0b1e2f6d8c3819717122eeb3a80f1caa7adde)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/anchandaAADGraph/microsoft-graph-docs/blob/patch-4/concepts/changelog.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901081900196059-3741%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=kicM1b%2BFQ33LWHDoVhfFT%2FXjtb75aPFWcw5r3ybQkQQ%3D&st=2019-01-08T18%3A58%3A45Z&se=2019-02-08T19%3A03%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by anchandaAADGraph** [comment]
Can someone please change the label to ready to merge? I am unable to add it.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[66dca19](https://github.com/anchandaAADGraph/microsoft-graph-docs/pull/3741/commits/66dca19ace301e24ed434bb97889bb63953ab5f3)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 23 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[66dca19](https://github.com/anchandaAADGraph/microsoft-graph-docs/pull/3741/commits/66dca19ace301e24ed434bb97889bb63953ab5f3)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 23 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[66dca19](https://github.com/anchandaAADGraph/microsoft-graph-docs/pull/3741/commits/66dca19ace301e24ed434bb97889bb63953ab5f3)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 57 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[66dca19](https://github.com/anchandaAADGraph/microsoft-graph-docs/pull/3741/commits/66dca19ace301e24ed434bb97889bb63953ab5f3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/anchandaAADGraph/microsoft-graph-docs/blob/patch-4/concepts/changelog.md) | :warning:Warning | | [Details](#user-content-concepts%2Fchangelog.md)

<a name="concepts%2Fchangelog.md"></a>
### [concepts/changelog.md](https://github.com/anchandaAADGraph/microsoft-graph-docs/blob/patch-4/concepts/changelog.md)
 - **Line 37**: **[Warning]** Invalid file link:(~/../api-reference/v1.0/resources/user.md).
 - **Line 39**: **[Warning]** Invalid file link:(~/../api-reference/v1.0/resources/group.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901312006042262-3741%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=6JhUCPPjsV5DA1S%2FzJEgDo1kIQDAttoGpk0Ga0aIrQw%3D&st=2019-01-31T20%3A05%3A55Z&se=2019-03-03T20%3A10%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
