### PR TITLE
DirectoryServices: Fix beta device doc bugs

### PR DESCRIPTION
**Pull request by eketo-msft**

### CODE REVIEW

**Comment by eketo-msft** [comment]
Created a separate PR for these doc bugs so I can self merge to beta instead of v1.0 approval.

**Comment by jthake-msft** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/eketo-beta-device-fixes/api-reference/beta/api/device-list-memberof.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201812050308317929-3552%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=lbba17aqmoDfqdefUzAsPEzrImS4sEKbGjhTDtASDj0%3D&st=2018-12-05T03%3A06%3A41Z&se=2019-01-05T03%3A11%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by eketo-msft** [comment]
Or not... someone merge for me?  :)

**Comment by jthake-msft** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/eketo-beta-device-fixes/api-reference/beta/api/device-list-memberof.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201812051937342756-3552%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=bu4C2tBMxeFUUefh8Ncy6%2Fq%2BGCwoWe5YJ9YXt9NdDE0%3D&st=2018-12-05T19%3A35%3A35Z&se=2019-01-05T19%3A40%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
