### PR TITLE
Update TeamsFx provider doc for v3.0.0

### PR DESCRIPTION
**Pull request by SLdragon**
Please **DO NOT MERGE** this PR before TeamsFx provider 3.0.0 has been released.

### CODE REVIEW

**Comment by SLdragon** [comment]
Please **DO NOT MERGE** this PR before TeamsFx provider 3.0.0 has been released.
https://github.com/microsoftgraph/microsoft-graph-toolkit/releases

**Comment by Lauragra** [comment]
@SLdragon , @gavinbarron , please set the ready to merge label when you're ready to merge this PR. Thanks!

**Comment by gavinbarron** [comment]
@SLdragon can you please target this to the mgt/v3 branch.

We're collecting all of the v3 documentation changes on that branch so that we have them collated and ready to publish in a single PR

**Comment by SLdragon** [comment]
Thank you @Lauragra and @gavinbarron , I have created another PR to target this to the mgt/v3 branch, so close this PR.

https://github.com/microsoftgraph/microsoft-graph-docs/pull/20247

**Pull request closed without merging**
