### PR TITLE
Proposal to add new field in schema-config. Treat errors in specified workloads as warnings

### PR DESCRIPTION
**Pull request by finsharp**
Proposal to add new field in schema-config, to specify that errors in certain workloads should be treated as warnings. For example errors in the intune workloads should be treated as warnings since the intune workloads docs are autogenerated.

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[45c1140](https://github.com/microsoftgraph/microsoft-graph-docs/pull/4152/commits/45c114044ebd2ed32384492822acda90cff426b4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/config/schema-config.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/treatErrorsAsWarnings/api-reference/beta/config/schema-config.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903130934594906-4152%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Qh%2FROjhzU%2FqYj4NKlIWw1atCeZD%2BsagR6TC4nHu4gYc%3D&st=2019-03-13T09%3A33%3A19Z&se=2019-04-13T09%3A38%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
@jthake-msft , are we ready to merge this?

**Comment by finsharp** [comment]
Hi @Lauragra I think this PR can be merged, it doesn't directly affect the docs, but more of optional configuration.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[491bc06](https://github.com/microsoftgraph/microsoft-graph-docs/pull/4152/commits/491bc069e1ff21adc2206e99e2718e956b530ff8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/config/schema-config.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/treatErrorsAsWarnings/api-reference/beta/config/schema-config.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903220050430453-4152%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=wbs5M%2Fl5lJPal1dg9rzRG4jHY93LWl14ETIZBctRkIg%3D&st=2019-03-22T00%3A48%3A55Z&se=2019-04-22T00%3A53%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
