### PR TITLE
Added description in Update event file

### PR DESCRIPTION
**Pull request by Swathi-Birlangi**
Added description in Update Event file

### CODE REVIEW

**Comment by Swathi-Birlangi** [comment]
@angelgolfer-ms could you please review this PR

**Comment by jasonjoh** [comment]
Docs Build status updates of commit _[abd82bf](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/abd82bfcf3d5d1bc04454ee898a2a9c44bf34ed6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/event-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/event-update/descriptionaddition/api-reference/v1.0/api/event-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&branch=pr-en-us-13129) (>= graph-rest-1.0) | [Details](#user-content-6758276e5586e129e1f8b6cb63cd1969-970b2707)
[api-reference/beta/api/event-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/event-update/descriptionaddition/api-reference/beta/api/event-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-beta&branch=pr-en-us-13129) (graph-rest-beta) |

<a id="6758276e5586e129e1f8b6cb63cd1969-970b2707"></a>
### [api-reference/v1.0/api/event-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/event-update/descriptionaddition/api-reference/v1.0/api/event-update.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-update.md(2,8), v1.0/api/group-update-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update event' is duplicated with other articles: 'v1.0/api/event-update.md(10,1), v1.0/api/group-update-event.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109020133268492-13129%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=wIyjlPM7tAilTw%2F%2BnpLCo2uuuixs66rQ1JignXUF2Pk%3D&st=2021-09-02T01%3A30%3A11Z&se=2021-10-03T01%3A35%3A11Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by angelgolfer-ms — COMMENTED** [review]
Hi @Swathi-Birlangi , I noticed that your last round of updates included the v1 event-update.md topic. I just need to have Harini confirm if v1 applies, because the corresponding user story specifies the following title: 
"Update Event: Description addition in MS-Graph beta".

Upon her confirmation, I can merge this PR.

**Review by angelgolfer-ms — APPROVED** [review]
Updates confirmed to apply to v1 as well, can publish this PR.

**Comment by jasonjoh** [comment]
Docs Build status updates of commit _[f5425fb](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/f5425fb1ee203bc0004289f39c3f5e1e647c8433)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/event-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/event-update/descriptionaddition/api-reference/v1.0/api/event-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&branch=pr-en-us-13129) (>= graph-rest-1.0) | [Details](#user-content-6758276e5586e129e1f8b6cb63cd1969-55edf4fe)
[api-reference/beta/api/event-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/event-update/descriptionaddition/api-reference/beta/api/event-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-beta&branch=pr-en-us-13129) (graph-rest-beta) |

<a id="6758276e5586e129e1f8b6cb63cd1969-55edf4fe"></a>
### [api-reference/v1.0/api/event-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/event-update/descriptionaddition/api-reference/v1.0/api/event-update.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-update.md(2,8), v1.0/api/group-update-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update event' is duplicated with other articles: 'v1.0/api/event-update.md(10,1), v1.0/api/group-update-event.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109020317296183-13129%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=UkFIXb5Wua5rnDdND1zfZBp9in4JCr19iq0DFkNYk8w%3D&st=2021-09-02T03%3A14%3A12Z&se=2021-10-03T03%3A19%3A12Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
