### PR TITLE
Doc beta for lastPasswordChangeDateTime

### PR DESCRIPTION
**Pull request by eketo-msft**

### CODE REVIEW

**Comment by Lauragra** [comment]
@dkershaw10 , is this one ready to publish, or just approved?

**Comment by dkershaw10** [comment]
@Lauragra Please wait for @eketo-msft  to confirm this.  AFAIK this missed this week's deployment, so I think we are lining up for next week.

**Comment by Lauragra** [comment]
@eketo-msft , the new property is live in beta, are we ready to publish this PR?

**Comment by dkershaw10** [comment]
@Lauragra You can merge this now - it's in the /beta metadata.

**Pull request merged**
