### PR TITLE
fix: Convert to MS Docs Note format

### PR DESCRIPTION
**Pull request by nschonni**
Find: ^> \*\*Note:\*\*
Replace: > [!NOTE]\n>

### CODE REVIEW

**Comment by Lauragra** [comment]
Hi @nschonni , thanks for your contribution. In some cases, we've formatted the Notes a certain way intentionally. We'll track a work item internally to convert the Notes to the Docs format where appropriate. In the meantime, I'll close this PR for now.

**Comment by nschonni** [comment]
There is also the same issue with a bunch of the "Important" monikers as well

**Comment by Lauragra** [comment]
Okay, thanks for the heads up!

**Comment by nschonni** [comment]
No problem, you might try the regex above in VS Code, but scope it to folders if you're interested in cleaning up in smaller batches

**Pull request closed without merging**
