### PR TITLE
att targetResource must be targetResources to work

### PR DESCRIPTION
**Pull request by jefersonsv**
The attribuite targetResource don't work with $filter parameter. To use target Resource attribute you must to use targetResources (with 's' at end).

And the JSON of SDK sample code has the attribute targetResource but the correct is targetResources also.

### CODE REVIEW

**Comment by jefersonsv** [comment]
What is the branch that I must to do the pull request, it's master?

**Comment by Lauragra** [comment]
Master is the correct target branch. Thanks for the PR. @dkershaw10 or @dhanyahk , can you please review and verify? @darrelmiller for the SDK update.

**Comment by darrelmiller** [comment]
@Lauragra Once the example response is updated, next time we generate the snippets, the correction will be propagated.  I don't believe there is anything we need to do on the SDK snippet generation side.

**Comment by Lauragra** [comment]
@dkershaw10 , @dhanyahk , do you want to sign off on this before I merge? Thanks.

**Comment by Lauragra** [comment]
@dhanyahk , please sign off on this PR.

**Pull request merged**
