### PR TITLE
Publish changes to mention and reaction structures

### PR DESCRIPTION
**Pull request by hamenon-ms**
There's some minor updates to the chatmention and chatreaction structures that we'll be publishing soon. These are the associated documentation changes. At a high level the changes are:
* Change the mention structure to use identitySet instead of custom identity type definition
* Remove the  value field in chatreaction which was not being used based on the latest updates to the reactions feature.

### CODE REVIEW

**Comment by hamenon-ms** [comment]
FYI @nkramer

**Comment by Lauragra** [comment]
@nkramer , do we still need this PR, or can we close? We probably need to redo it given that this was opened before the migration and therefore has conflicts. Thanks.

**Comment by nkramer** [comment]
hmm, there's at least some content here that hasn't made it into master, I'll need to figure it out.

**Comment by nkramer** [comment]
Actually, looks like almost all of it needs to be brought in.

**Comment by Lauragra** [comment]
Thanks for taking a look. I'll assign this to you to follow up on next steps.

**Comment by nkramer** [comment]
merged via https://github.com/microsoftgraph/microsoft-graph-docs/pull/4393

**Pull request closed without merging**
