### PR TITLE
Update synchronization-synchronizationschema.md

### PR DESCRIPTION
**Pull request by ArvindHarinder1**

### CODE REVIEW

**Comment by Lauragra** [comment]
@ArvindHarinder1 , please set the Do not merge or Ready to merge label, depending on the status.

**Comment by ArvindHarinder1** [comment]
@Lauragra  how do I add a label? I don't have this option when I go to the PR https://help.github.com/en/articles/applying-labels-to-issues-and-pull-requests

**Comment by Lauragra** [comment]
@ArvindHarinder1 , please make sure you followed the Get started steps here to get set up as a contributor: https://msgo.azurewebsites.net/add/document/manage-content/get-started-with-github.html.

**Comment by Lauragra** [comment]
@ArvindHarinder1 , please address the following validation error: 

Error: Resource synchronizationSchema has documented navigation properties, but we thought it was a complex type!

  Error: /resources/synchronization-synchronizationschema.md/microsoft.graph.synchronizationSchema/directories:
      Type mismatch between example and table. Parameter name: directories; example type (Collection(microsoft.graph.directoryDefinition)) is a collection, while the table description type (microsoft.graph.directoryDefinition) is not.

**Pull request closed without merging**
