### PR TITLE
improved the create chat message sample by adding mentions

### PR DESCRIPTION
**Pull request by baywet**

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[a2829e4](https://github.com/baywet/microsoft-graph-docs/pull/4118/commits/a2829e4e94e7d05c6a6a4d01fcf04aa445936c4e)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 26 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[a2829e4](https://github.com/baywet/microsoft-graph-docs/pull/4118/commits/a2829e4e94e7d05c6a6a4d01fcf04aa445936c4e)_: 

:clock10: **Incremental building**: average incremental building time is _2 min(s) 4 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[a2829e4](https://github.com/baywet/microsoft-graph-docs/pull/4118/commits/a2829e4e94e7d05c6a6a4d01fcf04aa445936c4e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post-chatmessage.md](https://github.com/baywet/microsoft-graph-docs/blob/patch-3/api-reference/beta/api/channel-post-chatmessage.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903072141495062-4118%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=KMC9NCLVQbGojvEwgUx63gylicuuSDECmfER1IWpXTU%3D&st=2019-03-07T21%3A40%3A25Z&se=2019-04-07T21%3A45%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[03abb56](https://github.com/baywet/microsoft-graph-docs/pull/4118/commits/03abb567aebebf8003b4f7fa9a894f6b50c65dba)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 26 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[03abb56](https://github.com/baywet/microsoft-graph-docs/pull/4118/commits/03abb567aebebf8003b4f7fa9a894f6b50c65dba)_: 

:clock10: **Incremental building**: average incremental building time is _2 min(s) 4 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[03abb56](https://github.com/baywet/microsoft-graph-docs/pull/4118/commits/03abb567aebebf8003b4f7fa9a894f6b50c65dba)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post-chatmessage.md](https://github.com/baywet/microsoft-graph-docs/blob/patch-3/api-reference/beta/api/channel-post-chatmessage.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903072143045868-4118%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=jBLkoSDLlrzqU4imi0AxtX9xUdNMsVip6YJmC%2FvbJlk%3D&st=2019-03-07T21%3A44%3A03Z&se=2019-04-07T21%3A49%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[3a2de6d](https://github.com/baywet/microsoft-graph-docs/pull/4118/commits/3a2de6db730f7e9cfb76cd2effee34ecb06872ac)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 26 sec(s)_

**Comment by nkramer** [comment]
Thanks for putting this together. I've split it into a separate sample, so we don't lose the simplicity of hello world, otherwise this looks great.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[3a2de6d](https://github.com/baywet/microsoft-graph-docs/pull/4118/commits/3a2de6db730f7e9cfb76cd2effee34ecb06872ac)_: 

:clock10: **Incremental building**: average incremental building time is _2 min(s) 5 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[3a2de6d](https://github.com/baywet/microsoft-graph-docs/pull/4118/commits/3a2de6db730f7e9cfb76cd2effee34ecb06872ac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post-chatmessage.md](https://github.com/baywet/microsoft-graph-docs/blob/patch-3/api-reference/beta/api/channel-post-chatmessage.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903080525349907-4118%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=RmC8fyJbjacnaSvIytcicCKATWznv%2BvSlw%2BH9pilLLM%3D&st=2019-03-08T05%3A24%3A03Z&se=2019-04-08T05%3A29%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[d0759f1](https://github.com/baywet/microsoft-graph-docs/pull/4118/commits/d0759f1b055222d5b69615729e8a9cab174d1432)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post-chatmessage.md](https://github.com/baywet/microsoft-graph-docs/blob/patch-3/api-reference/beta/api/channel-post-chatmessage.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903252148265280-4118%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=V8WPjnguIDYvgMwckpLbbuLY6fpdTIHtHw%2BA%2Bqz6hDw%3D&st=2019-03-25T21%3A47%3A00Z&se=2019-04-25T21%3A52%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[dbe075a](https://github.com/baywet/microsoft-graph-docs/pull/4118/commits/dbe075aa101c997eadb32be105058ec9844b913b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post-chatmessage.md](https://github.com/baywet/microsoft-graph-docs/blob/patch-3/api-reference/beta/api/channel-post-chatmessage.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903252153006618-4118%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=hE%2B9KJ4GwBfKdLI5CWyZPTAYhZ%2FgkrVTiJvvMMdBQGo%3D&st=2019-03-25T21%3A51%3A56Z&se=2019-04-25T21%3A56%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
