### PR TITLE
Update sortOrderIndex value in JSON representation

### PR DESCRIPTION
**Pull request by tony-xia**
@nkramer @Lauragra  According to [PR's review feedback](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3576), i updated the docs.
1.  remove sortOrderIndex from v1.0 docs
2. update all beta samples to use sortOrderIndex as a string.

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[0072df8](https://github.com/tony-xia/microsoft-graph-docs/pull/3827/commits/0072df8c3a41fc1169e8ee1d9770167b1fd8362d)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[0072df8](https://github.com/tony-xia/microsoft-graph-docs/pull/3827/commits/0072df8c3a41fc1169e8ee1d9770167b1fd8362d)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[0072df8](https://github.com/tony-xia/microsoft-graph-docs/pull/3827/commits/0072df8c3a41fc1169e8ee1d9770167b1fd8362d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamstab-add.md](https://github.com/tony-xia/microsoft-graph-docs/blob/sortOrderIndex-type/api-reference/beta/api/teamstab-add.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/teamstab-get.md](https://github.com/tony-xia/microsoft-graph-docs/blob/sortOrderIndex-type/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/teamstab-list.md](https://github.com/tony-xia/microsoft-graph-docs/blob/sortOrderIndex-type/api-reference/beta/api/teamstab-list.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/teamstab-update.md](https://github.com/tony-xia/microsoft-graph-docs/blob/sortOrderIndex-type/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/teamstab.md](https://github.com/tony-xia/microsoft-graph-docs/blob/sortOrderIndex-type/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/teamstab-add.md](https://github.com/tony-xia/microsoft-graph-docs/blob/sortOrderIndex-type/api-reference/v1.0/api/teamstab-add.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/teamstab-get.md](https://github.com/tony-xia/microsoft-graph-docs/blob/sortOrderIndex-type/api-reference/v1.0/api/teamstab-get.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/teamstab-list.md](https://github.com/tony-xia/microsoft-graph-docs/blob/sortOrderIndex-type/api-reference/v1.0/api/teamstab-list.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/teamstab-update.md](https://github.com/tony-xia/microsoft-graph-docs/blob/sortOrderIndex-type/api-reference/v1.0/api/teamstab-update.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/teamstab.md](https://github.com/tony-xia/microsoft-graph-docs/blob/sortOrderIndex-type/api-reference/v1.0/resources/teamstab.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901201152415162-3827%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=tNKAP7fbSI80CY6g9nZ2bJTUqfFqUJGV374ulu%2FzMUs%3D&st=2019-01-20T11%3A51%3A43Z&se=2019-02-20T11%3A56%3A43Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nkramer** [comment]
Thanks for cleaning this up, this looks great!

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[cdc9c78](https://github.com/tony-xia/microsoft-graph-docs/pull/3827/commits/cdc9c78d3758b91eac5f5b2b5d3156fc7dc17c0c)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[cdc9c78](https://github.com/tony-xia/microsoft-graph-docs/pull/3827/commits/cdc9c78d3758b91eac5f5b2b5d3156fc7dc17c0c)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[cdc9c78](https://github.com/tony-xia/microsoft-graph-docs/pull/3827/commits/cdc9c78d3758b91eac5f5b2b5d3156fc7dc17c0c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamstab-add.md](https://github.com/tony-xia/microsoft-graph-docs/blob/sortOrderIndex-type/api-reference/beta/api/teamstab-add.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/teamstab-get.md](https://github.com/tony-xia/microsoft-graph-docs/blob/sortOrderIndex-type/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/teamstab-list.md](https://github.com/tony-xia/microsoft-graph-docs/blob/sortOrderIndex-type/api-reference/beta/api/teamstab-list.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/teamstab-update.md](https://github.com/tony-xia/microsoft-graph-docs/blob/sortOrderIndex-type/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/teamstab.md](https://github.com/tony-xia/microsoft-graph-docs/blob/sortOrderIndex-type/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/teamstab-add.md](https://github.com/tony-xia/microsoft-graph-docs/blob/sortOrderIndex-type/api-reference/v1.0/api/teamstab-add.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/teamstab-get.md](https://github.com/tony-xia/microsoft-graph-docs/blob/sortOrderIndex-type/api-reference/v1.0/api/teamstab-get.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/teamstab-list.md](https://github.com/tony-xia/microsoft-graph-docs/blob/sortOrderIndex-type/api-reference/v1.0/api/teamstab-list.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/teamstab-update.md](https://github.com/tony-xia/microsoft-graph-docs/blob/sortOrderIndex-type/api-reference/v1.0/api/teamstab-update.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/teamstab.md](https://github.com/tony-xia/microsoft-graph-docs/blob/sortOrderIndex-type/api-reference/v1.0/resources/teamstab.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901252302545610-3827%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=3SsKl%2FaPsqZncW%2B8RiVRP71AJbHy62Oxnab0tKzVQtU%3D&st=2019-01-25T23%3A01%3A36Z&se=2019-02-25T23%3A06%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
