### PR TITLE
Fix typo: "for on" --> "on"

### PR DESCRIPTION
**Pull request by jeffwidman**

### CODE REVIEW

**Comment by Lauragra** [comment]
@jeffwidman , please sign the license agreement and then we can merge. Thanks!

**Comment by jeffwidman** [comment]
@Lauragra signed! 

I'm surprised you were able to merge https://github.com/microsoftgraph/microsoft-graph-docs/pull/6932#event-2987829936 in this same repo even though I hadn't signed... do you have different checks setup for different portions of the repo somehow?

**Comment by Lauragra** [comment]
@jeffwidman , it seems that I can update your branch, I just can't pull your changes into master. Anyway, thanks for signing!

**Comment by jeffwidman** [comment]
> it seems that I can update your branch, I just can't pull your changes into master.

Yeah, except you were able to pull into master over on https://github.com/microsoftgraph/microsoft-graph-docs/pull/6932#event-2987829936 before I signed the CLA... really weird, there's some bug in your CI pipeline...

**Pull request merged**
