### PR TITLE
new app proxy tutorial

### PR DESCRIPTION
**Pull request by davidmu1**

### CODE REVIEW

**Comment by japere** [comment]
@davidmu1 - I addressed your feedback from the original PR. Let me know what you think!

**Comment by davidmu1** [comment]
@japere, looks good! Added Dan to also take a look for us.

**Comment by davidmu1** [comment]
oops! didnt mean to close. Repoened.

**Comment by japere** [comment]
@Lauragra - This doc has been through a technical review and is now ready for your review. Thanks!

**Comment by Lauragra** [comment]
@davidmu1 , are you looking for an editorial review of this PR?

**Comment by davidmu1** [comment]
@Lauragra - This was written by Jasmine, I'm just helping with publishing. I have looked it over and think its pretty good, but I'm sure she would appreciate you looking at it and approving for publishing.

**Comment by davidmu1** [comment]
@Lauragra I do intend to add an overview for Applications, but will need some help to do it so it will take a little time. I am also going to recreate the PR that was closed to restructure the API toc. Can we please go ahead and publish this tutorial? and the other pieces will be coming soon.

**Comment by japere** [comment]
@Lauragra - Just following up here to see if we can publish this soon.

**Comment by Lauragra** [comment]
> @Lauragra - Just following up here to see if we can publish this soon.

Hi, David is working on updates to the reference TOCs to surface the Applications node. Given the visibility of this node, I'd like to have a concept overview topic for Applications before we publish this node with the tutorial content, to give customers an overview of what this API represents. David is working on that so let's sync this PR with the concept overview. Thanks.

**Comment by davidmu1** [comment]
@Lauragra - I've added an overview with information that I know about. Please provide any feedback and any other actions that need to happen to merge the PR. Thanks, David

**Pull request merged**
