### PR TITLE
Fixes to user profile

### PR DESCRIPTION
**Pull request by dkershaw10**
Mainly around issue in permissions descriptions

### CODE REVIEW

**Comment by dkershaw10** [comment]
@angelgolfer-ms @Lauragra Is there a reason that a large number of relationships are missing in the user resource topic?  Also why are most of the relationships marked as read-only?  This doesn't seem correct.  I can fix these - just let me know.

**Comment by dkershaw10** [comment]
Fixes for #4749 and #4705 being added too

**Comment by Lauragra** [comment]
@dkershaw10 , can you resolve the merge conflicts? Should be pretty straightforward.

**Comment by dkershaw10** [comment]
This has had tech review as well - it's ready to go. Please merge.  Thanks!

**Pull request merged**
