### PR TITLE
Go snippets generation

### PR DESCRIPTION
**Pull request by baywet**
Preview of go snippets in the API documentation.
Should wait on https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/756 before it gets merged.

Related https://github.com/microsoftgraph/microsoft-graph-docs/pull/14828

### CODE REVIEW

**Review by jasonjoh — CHANGES_REQUESTED** [review]
Let's see if we can figure out why some requests didn't get Go snippets generated. That's why there's a lot of invalid-tab-group errors in the build output. When docs have tabbed sections, all sections have to have the same tabs or the page doesn't work properly.

**Comment by baywet** [comment]
@jasonjoh just pushed a fix that added 6 new snippets. Are there other ones you saw as missing?

**Comment by jasonjoh** [comment]
Yeah, there's still a lot of invalid-tab-group warnings in the OPS build. I'm not sure if these are all new or old warnings though.

Are these going through a pipeline? Is there any logging in the snippet gen process that might show us where it's failing?

**Comment by jasonjoh** [comment]
In channel-post-messages.md, I'm seeing this failure:

```
goException while processing /tmp/1041b56f-8792-4107-ba84-71293e3d12dc/post-channelmessage-2-v1-httpSnippet.
Object reference not set to an instance of an object.   
  at CodeSnippetsReflection.OpenAPI.LanguageGenerators.GoGenerator.GetRequestPayloadAndVariableName(SnippetModel snippetModel, IndentManager indentManager) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs:line 131   
  at CodeSnippetsReflection.OpenAPI.LanguageGenerators.GoGenerator.GenerateCodeSnippet(SnippetModel snippetModel) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs:line 24   
  at CodeSnippetsReflection.OpenAPI.OpenApiSnippetsGenerator.ProcessPayloadRequest(HttpRequestMessage requestPayload, String language) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/OpenAPISnippetsGenerator.cs:line 63
```

**Comment by jasonjoh** [comment]
@baywet: In chatmessage-list-hostedcontents.md:

```
Path segment 'hostedContents' not found in path   
  at CodeSnippetsReflection.OpenAPI.SnippetModel.LoadPathNodes(OpenApiUrlTreeNode node, IEnumerable`1 pathSegments)   
  at CodeSnippetsReflection.OpenAPI.SnippetModel.LoadNextNode(OpenApiUrlTreeNode node, IEnumerable`1 pathSegments) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/SnippetModel.cs:line 128   
  at CodeSnippetsReflection.OpenAPI.SnippetModel.LoadPathNodes(OpenApiUrlTreeNode node, IEnumerable`1 pathSegments)   
  at CodeSnippetsReflection.OpenAPI.SnippetModel.LoadNextNode(OpenApiUrlTreeNode node, IEnumerable`1 pathSegments) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/SnippetModel.cs:line 128   
  at CodeSnippetsReflection.OpenAPI.SnippetModel.LoadPathNodes(OpenApiUrlTreeNode node, IEnumerable`1 pathSegments)   
  at CodeSnippetsReflection.OpenAPI.SnippetModel.LoadNextNode(OpenApiUrlTreeNode node, IEnumerable`1 pathSegments) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/SnippetModel.cs:line 128
```

**Comment by jasonjoh** [comment]
@baywet: In chatmessagehostedcontent-get.md:

```
Exception while processing /tmp/1041b56f-8792-4107-ba84-71293e3d12dc/get-hostedcontentchatmessage-2-beta-httpSnippet.Path segment '$value' not found in path   
  at CodeSnippetsReflection.OpenAPI.SnippetModel.LoadPathNodes(OpenApiUrlTreeNode node, IEnumerable`1 pathSegments)   
  at CodeSnippetsReflection.OpenAPI.SnippetModel.LoadNextNode(OpenApiUrlTreeNode node, IEnumerable`1 pathSegments) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/SnippetModel.cs:line 128   
  at CodeSnippetsReflection.OpenAPI.SnippetModel.LoadPathNodes(OpenApiUrlTreeNode node, IEnumerable`1 pathSegments)   
  at CodeSnippetsReflection.OpenAPI.SnippetModel.LoadNextNode(OpenApiUrlTreeNode node, IEnumerable`1 pathSegments) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/SnippetModel.cs:line 128
```

**Comment by jasonjoh** [comment]
@baywet: In conditionalaccessroot-post-policies.md:

```
Exception while processing /tmp/1041b56f-8792-4107-ba84-71293e3d12dc/create-conditionalaccesspolicy-from-conditionalaccessroot-3-v1-httpSnippet.Sequence contains no elements   at System.Linq.ThrowHelper.ThrowNoElementsException()   
  at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)   
  at CodeSnippetsReflection.OpenAPI.LanguageGenerators.GoGenerator.WriteJsonArrayValue(StringBuilder payloadSB, JsonElement value, OpenApiSchema schema, IndentManager indentManager, String propertyAssignment) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs:line 219   
  at CodeSnippetsReflection.OpenAPI.LanguageGenerators.GoGenerator.WriteProperty(StringBuilder payloadSB, JsonElement value, OpenApiSchema propSchema, IndentManager indentManager, String propertyAssignment, String tempVarName, String propertySuffix) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs:line 212   
  at CodeSnippetsReflection.OpenAPI.LanguageGenerators.GoGenerator.WriteJsonObjectValue(StringBuilder payloadSB, JsonElement value, OpenApiSchema schema, IndentManager indentManager, Boolean includePropertyAssignment, String variableName) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs:line 159   
  at CodeSnippetsReflection.OpenAPI.LanguageGenerators.GoGenerator.WriteProperty(StringBuilder payloadSB, JsonElement value, OpenApiSchema propSchema, IndentManager indentManager, String propertyAssignment, String tempVarName, String propertySuffix) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs:line 208   
  at CodeSnippetsReflection.OpenAPI.LanguageGenerators.GoGenerator.WriteJsonObjectValue(StringBuilder payloadSB, JsonElement value, OpenApiSchema schema, IndentManager indentManager, Boolean includePropertyAssignment, String variableName) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs:line 159   
  at CodeSnippetsReflection.OpenAPI.LanguageGenerators.GoGenerator.WriteProperty(StringBuilder payloadSB, JsonElement value, OpenApiSchema propSchema, IndentManager indentManager, String propertyAssignment, String tempVarName, String propertySuffix) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs:line 208   
  at CodeSnippetsReflection.OpenAPI.LanguageGenerators.GoGenerator.WriteJsonObjectValue(StringBuilder payloadSB, JsonElement value, OpenApiSchema schema, IndentManager indentManager, Boolean includePropertyAssignment, String variableName) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs:line 159   
  at CodeSnippetsReflection.OpenAPI.LanguageGenerators.GoGenerator.GetRequestPayloadAndVariableName(SnippetModel snippetModel, IndentManager indentManager) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs:line 139   
  at CodeSnippetsReflection.OpenAPI.LanguageGenerators.GoGenerator.GenerateCodeSnippet(SnippetModel snippetModel) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs:line 24   
  at CodeSnippetsReflection.OpenAPI.OpenApiSnippetsGenerator.ProcessPayloadRequest(HttpRequestMessage requestPayload, String language) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/OpenAPISnippetsGenerator.cs:line 63
```

**Comment by baywet** [comment]
Thanks for catching all these things @jasonjoh! I've looked into all of those and was able to identify root causes, and implement some fixes.
I'm currently running the snippets generation pipeline to open a new PR against this branch so we can see the improvements.

Here is some more context for each of the things you reported:

- chatmessagehostedcontent-get.md, chatmessage-list-hostedcontents.md => error in odata conversion process, I opened an issue for that, probably won't be fixed in time for this PR https://github.com/microsoft/OpenAPI.NET.OData/issues/123
- channel-post-messages.md => missing content type request header in http snippet, but added tolerance for that in the snippet generation code.
- conditionalaccessroot-post-policies.md => bug in the snippet generation, fixed.

Let me know if you find other things!

**Comment by jasonjoh** [comment]
@baywet: In device-list-usagerights.md line 128:

```
Exception while processing /tmp/a5dbf981-1278-4a19-b6c6-cbde49daedf8/list-usageright-2-beta-httpSnippet.An item with the same key has already been added. Key: 20   
  at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)   
  at CodeSnippetsReflection.OpenAPI.LanguageGenerators.GoGenerator.ReplaceNestedOdataQueryParameters(String queryParams) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs:line 106   
  at CodeSnippetsReflection.OpenAPI.LanguageGenerators.GoGenerator.GetRequestQueryParameters(SnippetModel model, IndentManager indentManager) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs:line 83   
  at CodeSnippetsReflection.OpenAPI.LanguageGenerators.GoGenerator.GenerateCodeSnippet(SnippetModel snippetModel) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/LanguageGenerators/GoGenerator.cs:line 27
```

**Comment by jasonjoh** [comment]
@baywet: In directory-deleteditems-list.md line 98:

```
Exception while processing /tmp/a5dbf981-1278-4a19-b6c6-cbde49daedf8/get-deleteditems-beta-httpSnippet.Path segment 'deleteditems' not found in path   
  at CodeSnippetsReflection.OpenAPI.SnippetModel.LoadPathNodes(OpenApiUrlTreeNode node, IEnumerable`1 pathSegments) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/SnippetModel.cs:line 123   
  at CodeSnippetsReflection.OpenAPI.SnippetModel.LoadNextNode(OpenApiUrlTreeNode node, IEnumerable`1 pathSegments) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/SnippetModel.cs:line 128   
  at CodeSnippetsReflection.OpenAPI.SnippetModel.LoadPathNodes(OpenApiUrlTreeNode node, IEnumerable`1 pathSegments) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/SnippetModel.cs:line 102   
  at CodeSnippetsReflection.OpenAPI.SnippetModel..ctor(HttpRequestMessage requestPayload, String serviceRootUrl, OpenApiUrlTreeNode treeNode) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/SnippetModel.cs:line 27   
  at CodeSnippetsReflection.OpenAPI.OpenApiSnippetsGenerator.ProcessPayloadRequest(HttpRequestMessage requestPayload, String language) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/OpenAPISnippetsGenerator.cs:line 61
```

**Comment by jasonjoh** [comment]
@baywet: In eventmessage-get.md line 212:

```
Exception while processing /tmp/a5dbf981-1278-4a19-b6c6-cbde49daedf8/get-event-based-on-eventmessage-beta-httpSnippet.Path segment '' not found in pathError when generating code snippets!!!
```

**Comment by jasonjoh** [comment]
@baywet: In group-list-members.md line 197:

```
Path segment 'microsoft.graph.user' not found in path   
  at CodeSnippetsReflection.OpenAPI.SnippetModel.LoadPathNodes(OpenApiUrlTreeNode node, IEnumerable`1 pathSegments) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/SnippetModel.cs:line 123   
  at CodeSnippetsReflection.OpenAPI.SnippetModel.LoadNextNode(OpenApiUrlTreeNode node, IEnumerable`1 pathSegments) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/SnippetModel.cs:line 128   
  at CodeSnippetsReflection.OpenAPI.SnippetModel.LoadPathNodes(OpenApiUrlTreeNode node, IEnumerable`1 pathSegments) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/SnippetModel.cs:line 102   
  at CodeSnippetsReflection.OpenAPI.SnippetModel.LoadNextNode(OpenApiUrlTreeNode node, IEnumerable`1 pathSegments) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/SnippetModel.cs:line 128   
  at CodeSnippetsReflection.OpenAPI.SnippetModel.LoadPathNodes(OpenApiUrlTreeNode node, IEnumerable`1 pathSegments) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/SnippetModel.cs:line 119   
  at CodeSnippetsReflection.OpenAPI.SnippetModel.LoadNextNode(OpenApiUrlTreeNode node, IEnumerable`1 pathSegments) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/SnippetModel.cs:line 128   
  at CodeSnippetsReflection.OpenAPI.SnippetModel.LoadPathNodes(OpenApiUrlTreeNode node, IEnumerable`1 pathSegments) in /home/vsts/work/1/s/microsoft-graph-devx-api/CodeSnippetsReflection.OpenAPI/SnippetModel.cs:line 102
```

**Comment by baywet** [comment]
@jasonjoh Thanks a lot for these additional cases! Here is the result:
- directory-deleteditems-list.md, device-list-usagerights.md, eventmessage-get.md => fixed
- group-list-members.md => [bug in the conversion library](https://github.com/microsoft/OpenAPI.NET.OData/issues/124)

Like last time, I'll put together a PR shortly against this branch so we can see how much things have improved.

**Comment by baywet** [comment]
@jasonjoh looking at the logs the generation without go fails on 900 snippets, with go 1600, which means an additional 700 failures for go snippets.
There's a total of 7519 go snippets that are attempted to be generated. Which means about 10% of our snippets fail for go.
I suggest we merge this along and revisit it for GA and/or when raptor adds support for go.
Thoughts?

**Comment by jasonjoh** [comment]
Yes, I think that's reasonable.

**Review by jasonjoh — APPROVED** [review]

**Comment by Lauragra** [comment]
@baywet , PR 756 isn't merged yet; do you want me to merge this one?

**Comment by baywet** [comment]
Thanks for catching that. Let's hold. I'll get the other one merged first. I don't want the weekly generation to rollback this change, it'd be a poor experience for everyone

**Comment by Lauragra** [comment]
> Thanks for catching that. Let's hold. I'll get the other one merged first. I don't want the weekly generation to rollback this change, it'd be a poor experience for everyone

Okay, I removed the ready to merge label; just add it back after the other PR is merged. Thanks!

**Comment by baywet** [comment]
now pending on https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/785

**Comment by baywet** [comment]
both PRs have been merged, we're good to go

**Pull request merged**
