### PR TITLE
Fix broken links changelog/Microsoft.Intune.json

### PR DESCRIPTION
**Pull request by dodaromike**
First commit: Remove broken links through 1020 changelist

### CODE REVIEW

**Comment by dodaromike** [comment]
I think it's best to merge this PR and continue fixing broken links in a new branch.  We'll avoid conflicts in the long run.

**Review by Danielabom — APPROVED** [review]
PR approved.

**Comment by Lauragra** [comment]
@dodaromike , are you able to resolve the merge conflicts? Thanks.

**Comment by dodaromike** [comment]
@Lauragra The Resolve conflicts button is greyed out here.

**Comment by dodaromike** [comment]
No conflicts showing when I run:
C:\Users\v-dodaromike\angela\microsoft-graph-docs>git status
On branch fix-broken-links-1-24-2023
Your branch is up to date with 'origin/fix-broken-links-1-24-2023'.

nothing to commit, working tree clean

**Comment by Lauragra** [comment]
> No conflicts showing when I run: C:\Users\v-dodaromike\angela\microsoft-graph-docs>git status On branch fix-broken-links-1-24-2023 Your branch is up to date with 'origin/fix-broken-links-1-24-2023'.
> 
> nothing to commit, working tree clean

@dodaromike Can you try following the instructions to resolve the merge conflicts? Normally GitHub lets you do it right in the browser but for some reason that option isn't available here.

image

**Comment by dodaromike** [comment]
> > No conflicts showing when I run: C:\Users\v-dodaromike\angela\microsoft-graph-docs>git status On branch fix-broken-links-1-24-2023 Your branch is up to date with 'origin/fix-broken-links-1-24-2023'.
> > nothing to commit, working tree clean
> 
> @dodaromike Can you try following the instructions to resolve the merge conflicts? Normally GitHub lets you do it right in the browser but for some reason that option isn't available here.


That's what I was trying to do when I got the status above.  I'm not showing any conflicts in my branch.

**Pull request closed without merging**
