### PR TITLE
Introducing authz challenges for Outlook notifications

### PR DESCRIPTION
**Pull request by piotrci**
This change introduces a new flow around authz challenges to the existing basic notifications for Outlook/Exchange entities.

We are doing this to address a gap in the Exchange flow where Exchange may remove active subscriptions due to mailbox events, and currently does not notify the app. This looks like subscriptions simply disappear and notifications stop flowing.

The new `lifecycleNotificationUrl` will be used to deliver authz challenges to which the app responds to recreate a subscription.

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[9e8d273](https://github.com/microsoftgraph/microsoft-graph-docs/pull/4247/commits/9e8d273e43dc9cfac38d150eec2407338ac5e01f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/toc.yml) | :x:Error | | [Details](#user-content-concepts%2Ftoc.yml)
[concepts/webhooks-exchange-authz.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/webhooks-exchange-authz.md) | :warning:Warning | | [Details](#user-content-concepts%2Fwebhooks-exchange-authz.md)

<a name="concepts%2Ftoc.yml"></a>
### [concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/toc.yml)
 - **[Error]** W:\0ukb-s\concepts\toc.yml is not a valid TOC File: W:\0ukb-s\concepts\toc.yml is not a valid TOC file, detail: (Line: 245, Col: 13, Idx: 9202) - (Line: 245, Col: 13, Idx: 9202): While parsing a block collection, did not find expected &#39;-&#39; indicator..
 - **[Error]** Unable to load file &#39;toc.yml&#39; via processor &#39;ExperimentalTocDocumentProcessor&#39;: W:\0ukb-s\concepts\toc.yml is not a valid TOC File: W:\0ukb-s\concepts\toc.yml is not a valid TOC file, detail: (Line: 245, Col: 13, Idx: 9202) - (Line: 245, Col: 13, Idx: 9202): While parsing a block collection, did not find expected &#39;-&#39; indicator..
 - **[Error]** W:\0ukb-s\concepts\toc.yml is not a valid TOC File: W:\0ukb-s\concepts\toc.yml is not a valid TOC file, detail: (Line: 245, Col: 13, Idx: 9202) - (Line: 245, Col: 13, Idx: 9202): While parsing a block collection, did not find expected &#39;-&#39; indicator..
 - **[Error]** Unable to load file &#39;toc.yml&#39; via processor &#39;TocDocumentProcessor&#39;: W:\0ukb-s\concepts\toc.yml is not a valid TOC File: W:\0ukb-s\concepts\toc.yml is not a valid TOC file, detail: (Line: 245, Col: 13, Idx: 9202) - (Line: 245, Col: 13, Idx: 9202): While parsing a block collection, did not find expected &#39;-&#39; indicator..

<a name="concepts%2Fwebhooks-exchange-authz.md"></a>
### [concepts/webhooks-exchange-authz.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/webhooks-exchange-authz.md)
 - **Line 99**: **[Warning]** Invalid file link:(~/(webhooks.md#notifications)).
 - **Line 153**: **[Warning]** Invalid file link:(~/(webhooks.md#notifications)).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903252248186615-4247%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Qs4tFR%2BSEmMvcvRHYvJ9DJ4VKnkxP5oQmQbkgwq0SwY%3D&st=2019-03-25T22%3A46%3A32Z&se=2019-04-25T22%3A51%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
@piotrci , what is your timeline for publishing this PR?

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[a31bd4e](https://github.com/microsoftgraph/microsoft-graph-docs/pull/4247/commits/a31bd4eca9af164d3d2d85b6f616333661e8a9ff)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/toc.yml) | :x:Error | | [Details](#user-content-concepts%2Ftoc.yml)
[concepts/webhooks-outlook-authz.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/webhooks-outlook-authz.md) | :warning:Warning | | [Details](#user-content-concepts%2Fwebhooks-outlook-authz.md)

<a name="concepts%2Ftoc.yml"></a>
### [concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/toc.yml)
 - **[Error]** W:\p3xn-s\concepts\toc.yml is not a valid TOC File: W:\p3xn-s\concepts\toc.yml is not a valid TOC file, detail: (Line: 245, Col: 13, Idx: 9202) - (Line: 245, Col: 13, Idx: 9202): While parsing a block collection, did not find expected &#39;-&#39; indicator..
 - **[Error]** Unable to load file &#39;toc.yml&#39; via processor &#39;ExperimentalTocDocumentProcessor&#39;: W:\p3xn-s\concepts\toc.yml is not a valid TOC File: W:\p3xn-s\concepts\toc.yml is not a valid TOC file, detail: (Line: 245, Col: 13, Idx: 9202) - (Line: 245, Col: 13, Idx: 9202): While parsing a block collection, did not find expected &#39;-&#39; indicator..
 - **[Error]** W:\p3xn-s\concepts\toc.yml is not a valid TOC File: W:\p3xn-s\concepts\toc.yml is not a valid TOC file, detail: (Line: 245, Col: 13, Idx: 9202) - (Line: 245, Col: 13, Idx: 9202): While parsing a block collection, did not find expected &#39;-&#39; indicator..
 - **[Error]** Unable to load file &#39;toc.yml&#39; via processor &#39;TocDocumentProcessor&#39;: W:\p3xn-s\concepts\toc.yml is not a valid TOC File: W:\p3xn-s\concepts\toc.yml is not a valid TOC file, detail: (Line: 245, Col: 13, Idx: 9202) - (Line: 245, Col: 13, Idx: 9202): While parsing a block collection, did not find expected &#39;-&#39; indicator..

<a name="concepts%2Fwebhooks-outlook-authz.md"></a>
### [concepts/webhooks-outlook-authz.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/webhooks-outlook-authz.md)
 - **Line 99**: **[Warning]** Invalid file link:(~/(webhooks.md#notifications)).
 - **Line 153**: **[Warning]** Invalid file link:(~/(webhooks.md#notifications)).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903260042084871-4247%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=XjAYo2PShKfLB1Wjdc2qQwNJu6N8157zeZMw31hPdps%3D&st=2019-03-26T00%3A40%3A17Z&se=2019-04-26T00%3A45%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[ad3f1c2](https://github.com/microsoftgraph/microsoft-graph-docs/pull/4247/commits/ad3f1c2ce3da66bf9ae69d60646d9ee5cad016de)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/toc.yml) | :x:Error | | [Details](#user-content-concepts%2Ftoc.yml)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/changelog.md) | :warning:Warning | | [Details](#user-content-concepts%2Fchangelog.md)
[concepts/webhooks-outlook-authz.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/webhooks-outlook-authz.md) | :warning:Warning | | [Details](#user-content-concepts%2Fwebhooks-outlook-authz.md)

<a name="concepts%2Ftoc.yml"></a>
### [concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/toc.yml)
 - **[Error]** W:\gl1z-s\concepts\toc.yml is not a valid TOC File: W:\gl1z-s\concepts\toc.yml is not a valid TOC file, detail: (Line: 245, Col: 13, Idx: 9202) - (Line: 245, Col: 13, Idx: 9202): While parsing a block collection, did not find expected &#39;-&#39; indicator..
 - **[Error]** Unable to load file &#39;toc.yml&#39; via processor &#39;ExperimentalTocDocumentProcessor&#39;: W:\gl1z-s\concepts\toc.yml is not a valid TOC File: W:\gl1z-s\concepts\toc.yml is not a valid TOC file, detail: (Line: 245, Col: 13, Idx: 9202) - (Line: 245, Col: 13, Idx: 9202): While parsing a block collection, did not find expected &#39;-&#39; indicator..
 - **[Error]** W:\gl1z-s\concepts\toc.yml is not a valid TOC File: W:\gl1z-s\concepts\toc.yml is not a valid TOC file, detail: (Line: 245, Col: 13, Idx: 9202) - (Line: 245, Col: 13, Idx: 9202): While parsing a block collection, did not find expected &#39;-&#39; indicator..
 - **[Error]** Unable to load file &#39;toc.yml&#39; via processor &#39;TocDocumentProcessor&#39;: W:\gl1z-s\concepts\toc.yml is not a valid TOC File: W:\gl1z-s\concepts\toc.yml is not a valid TOC file, detail: (Line: 245, Col: 13, Idx: 9202) - (Line: 245, Col: 13, Idx: 9202): While parsing a block collection, did not find expected &#39;-&#39; indicator..

<a name="concepts%2Fchangelog.md"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/changelog.md)
 - **Line 19**: **[Warning]** Invalid file link:(~/graph/api/resources/webhooks?view=graph-rest-beta).

<a name="concepts%2Fwebhooks-outlook-authz.md"></a>
### [concepts/webhooks-outlook-authz.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/webhooks-outlook-authz.md)
 - **Line 99**: **[Warning]** Invalid file link:(~/(webhooks.md#notifications)).
 - **Line 153**: **[Warning]** Invalid file link:(~/(webhooks.md#notifications)).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903260046099024-4247%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Z%2FF44KmrsJ7rpOqpAZLERTBdTWhLphJBGtSI4RSOnQo%3D&st=2019-03-26T00%3A44%3A11Z&se=2019-04-26T00%3A49%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[3877df2](https://github.com/microsoftgraph/microsoft-graph-docs/pull/4247/commits/3877df2083345117111d832e29de01bfa6a527e8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/changelog.md) | :warning:Warning | | [Details](#user-content-concepts%2Fchangelog.md)
[concepts/webhooks-outlook-authz.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/webhooks-outlook-authz.md) | :warning:Warning | | [Details](#user-content-concepts%2Fwebhooks-outlook-authz.md)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/toc.yml) | :white_check_mark:Succeeded | |

<a name="concepts%2Fchangelog.md"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/changelog.md)
 - **Line 19**: **[Warning]** Invalid file link:(~/graph/api/resources/webhooks?view=graph-rest-beta).

<a name="concepts%2Fwebhooks-outlook-authz.md"></a>
### [concepts/webhooks-outlook-authz.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/webhooks-outlook-authz.md)
 - **Line 99**: **[Warning]** Invalid file link:(~/(webhooks.md#notifications)).
 - **Line 153**: **[Warning]** Invalid file link:(~/(webhooks.md#notifications)).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903260051036533-4247%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=2aY9nznkQ905wgfLjiEd31oCj5cJ9EPU1lMHEGkqdas%3D&st=2019-03-26T00%3A49%3A41Z&se=2019-04-26T00%3A54%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by piotrci** [comment]
#hold-off main doc is not final, yet. still a few TBDs (marked with @@@)

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[8488ef7](https://github.com/microsoftgraph/microsoft-graph-docs/pull/4247/commits/8488ef7aee8468cf0785791919925e45eeddb377)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/changelog.md) | :warning:Warning | | [Details](#user-content-concepts%2Fchangelog.md)
[concepts/webhooks-outlook-authz.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/webhooks-outlook-authz.md) | :warning:Warning | | [Details](#user-content-concepts%2Fwebhooks-outlook-authz.md)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/toc.yml) | :white_check_mark:Succeeded | |

<a name="concepts%2Fchangelog.md"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/changelog.md)
 - **Line 20**: **[Warning]** Invalid file link:(~/webhooks).
 - **Line 20**: **[Warning]** Invalid file link:(~/webhooks-outlook-authz).

<a name="concepts%2Fwebhooks-outlook-authz.md"></a>
### [concepts/webhooks-outlook-authz.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/webhooks-outlook-authz.md)
 - **Line 20**: **[Warning]** Invalid file link:(~/webhooks).
 - **Line 47**: **[Warning]** Invalid file link:(~/webhooks#managing-subscriptions).
 - **Line 98**: **[Warning]** Invalid file link:(~/webhooks#notifications).
 - **Line 99**: **[Warning]** Invalid file link:(~/(webhooks#notifications)).
 - **Line 151**: **[Warning]** Invalid file link:(~/webhooks#notifications).
 - **Line 153**: **[Warning]** Invalid file link:(~/(webhooks#notifications)).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903260058126178-4247%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=nvtv8zVHDeXQNQLPqM2Q6nfjmSrkCj1VhfP3LFtUBFw%3D&st=2019-03-26T00%3A56%3A54Z&se=2019-04-26T01%3A01%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[318a678](https://github.com/microsoftgraph/microsoft-graph-docs/pull/4247/commits/318a678e4e4dd3c9dc4305a9a297554359a4819a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/changelog.md) | :warning:Warning | | [Details](#user-content-concepts%2Fchangelog.md)
[concepts/webhooks-outlook-authz.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/webhooks-outlook-authz.md) | :warning:Warning | | [Details](#user-content-concepts%2Fwebhooks-outlook-authz.md)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/toc.yml) | :white_check_mark:Succeeded | |

<a name="concepts%2Fchangelog.md"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/changelog.md)
 - **Line 20**: **[Warning]** Invalid file link:(~/webhooks).
 - **Line 20**: **[Warning]** Invalid file link:(~/webhooks-outlook-authz).

<a name="concepts%2Fwebhooks-outlook-authz.md"></a>
### [concepts/webhooks-outlook-authz.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/webhooks-outlook-authz.md)
 - **Line 99**: **[Warning]** Invalid file link:(~/(webhooks.md#notifications)).
 - **Line 153**: **[Warning]** Invalid file link:(~/(webhooks.md#notifications)).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903260112462914-4247%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=tTrDVia3UktJqEdRs4X%2BiWyLDET2M8lFFejcKguyaJ8%3D&st=2019-03-26T01%3A11%3A17Z&se=2019-04-26T01%3A16%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[6b2583a](https://github.com/microsoftgraph/microsoft-graph-docs/pull/4247/commits/6b2583aa358f6901aaa2b2cbb564375e4c16a64b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/changelog.md) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/toc.yml) | :white_check_mark:Succeeded | |
[concepts/webhooks-outlook-authz.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/webhooks-outlook-authz.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903260120046962-4247%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=DQOPfPbKgbdc1Jaf6Pt%2FyPk%2BcPGFyds2fSexmXyUMCA%3D&st=2019-03-26T01%3A18%3A36Z&se=2019-04-26T01%3A23%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[b4cac93](https://github.com/microsoftgraph/microsoft-graph-docs/pull/4247/commits/b4cac93acce89ac528c407eec45ce8425b48979c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/changelog.md) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/toc.yml) | :white_check_mark:Succeeded | |
[concepts/webhooks-outlook-authz.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/webhooks-outlook-authz.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903260127003105-4247%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=lWCyMiPmrNMQUsnXyDjPlFWD1YgM1bYbCmVwUQb17%2F0%3D&st=2019-03-26T01%3A25%3A28Z&se=2019-04-26T01%3A30%3A28Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[77a9820](https://github.com/microsoftgraph/microsoft-graph-docs/pull/4247/commits/77a9820096ffba8010731a705d10f2735aceb70f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/changelog.md) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/toc.yml) | :white_check_mark:Succeeded | |
[concepts/webhooks-outlook-authz.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/webhooks-outlook-authz.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903270021374823-4247%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=7ySisL3zow7b%2BngnYP7NbpJvCyK3kJTYPw8bI9AgYtU%3D&st=2019-03-27T00%3A20%3A31Z&se=2019-04-27T00%3A25%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[9ed53e9](https://github.com/microsoftgraph/microsoft-graph-docs/pull/4247/commits/9ed53e99844634576a64feaf231e571c5731b6ec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/changelog.md) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/toc.yml) | :white_check_mark:Succeeded | |
[concepts/webhooks-outlook-authz.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/webhooks-outlook-authz.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903270120551366-4247%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=M8s5tJ1BPkcMMTqghJYNsAMPm5pYCw%2F8AWJnJIx4eUE%3D&st=2019-03-27T01%3A19%3A40Z&se=2019-04-27T01%3A24%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[257760f](https://github.com/microsoftgraph/microsoft-graph-docs/pull/4247/commits/257760facfe32d01f091cd5cab7cf17c39383f9d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/changelog.md) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/toc.yml) | :white_check_mark:Succeeded | |
[concepts/webhooks-outlook-authz.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/webhooks-outlook-authz.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903272219009721-4247%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=NGoRzhNLcl0lXOYJlcyhMmXE9kU8ySgJYeCAjg4Ywc8%3D&st=2019-03-27T22%3A17%3A47Z&se=2019-04-27T22%3A22%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[22b5d3e](https://github.com/microsoftgraph/microsoft-graph-docs/pull/4247/commits/22b5d3ea370fc877dae9d4b58f9a7f42917aea16)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/changelog.md) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/toc.yml) | :white_check_mark:Succeeded | |
[concepts/webhooks-outlook-authz.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/webhooks-outlook-authz.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903272234429673-4247%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=08wg%2BrooSQlC23RZ9m46p%2BLt0aU02ehF0Y%2Bru8tZ4%2BY%3D&st=2019-03-27T22%3A33%3A27Z&se=2019-04-27T22%3A38%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
Docs Build status updates of commit _[8337a24](https://github.com/microsoftgraph/microsoft-graph-docs/pull/4247/commits/8337a2443b3ac4ae9ab8b3f159d1b42dbdfb4abc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/changelog.md) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/toc.yml) | :white_check_mark:Succeeded | |
[concepts/webhooks-outlook-authz.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ExchangeNotificationsWithAouthzChallenges/concepts/webhooks-outlook-authz.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201904020759322263-4247%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=N5%2F6JBj%2F9RCqHDINfGPpIhNil3GAjSE6JDkXW849c04%3D&st=2019-04-02T07%3A57%3A47Z&se=2019-05-03T08%3A02%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by piotrci** [comment]
We will be deleting this PR, replacing it with a new one. Keeping it active for a while, so folks can compare.

**Comment by piotrci** [comment]
Closed the PR because it has been replaced by https://github.com/microsoftgraph/microsoft-graph-docs/pull/4308

Keeping the original branch in case we want to go back to some aspects of the original design.

**Pull request closed without merging**
