### PR TITLE
Remove List & Get endpoints from Groups v1.0

### PR DESCRIPTION
**Pull request by FaithOmbongi**
Fixes
- #11310
- #11311

### CODE REVIEW

**Review by yyuank — COMMENTED** [review]
Why did we remove the description from beta/resources/endpoint.md?

**Comment by FaithOmbongi** [comment]
> Why did we remove the description from beta/resources/endpoint.md?

**Comment by yyuank** [comment]
@FaithOmbongi I was referring to this deleted description "For example, when a new Microsoft 365 group is created, additional resources are also created as part of the Microsoft 365 group. These include things like a group mailbox for conversations and a group OneDrive folder for documents and files. Further information about these Microsoft 365 group resources, including their associated resource URLs can now be read using the *endpoints* navigation on the group resource-type. This allows applications to understand these resources, and even embed the resource URL experiences in their own experiences."

Is it because that description is too group specific and doesn't apply to service principal?

**Comment by FaithOmbongi** [comment]
@yyuank The description metadata was too long and a duplicate of the description content. I hope this is OK?

**Review by yyuank — APPROVED** [review]

**Review by davidmu1 — APPROVED** [review]

**Pull request merged**
