### PR TITLE
Release Live Event in Graphv1.0

### PR DESCRIPTION
**Pull request by frankpeng7**
Release Live Event in Graphv1.0

Beta doc release PR for reference #10345

### CODE REVIEW

**Comment by jasonjoh** [comment]
Docs Build status updates of commit _[1914557](https://github.com/microsoftgraph/microsoft-graph-docs/commits/19145573a7695888b82f9475752bd7dbb7a22d51)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live_event_v1/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-14000) (graph-rest-beta) |
[api-reference/beta/resources/broadcastmeetingsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live_event_v1/api-reference/beta/resources/broadcastmeetingsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastmeetingsettings?view=graph-rest-beta&branch=pr-en-us-14000) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live_event_v1/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-14000) (graph-rest-beta) |
[api-reference/v1.0/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live_event_v1/api-reference/v1.0/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&branch=pr-en-us-14000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/broadcastmeetingsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live_event_v1/api-reference/v1.0/resources/broadcastmeetingsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastmeetingsettings?view=graph-rest-1.0&branch=pr-en-us-14000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/meetingparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live_event_v1/api-reference/v1.0/resources/meetingparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingparticipantinfo?view=graph-rest-1.0&branch=pr-en-us-14000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live_event_v1/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-14000) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live_event_v1/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109012049066032-14000%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=nHYFKPGFptuGQxBjVdBfuVqEBM3CRuVTqc0lTN3nZ3A%3D&st=2021-09-01T20%3A46%3A08Z&se=2021-10-02T20%3A51%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by Lauragra — APPROVED** [review]

**Comment by jasonjoh** [comment]
Docs Build status updates of commit _[14831d0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/14831d0260a892be7c3ed822d298d0bbb2957960)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live_event_v1/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-14000) (graph-rest-beta) |
[api-reference/beta/resources/broadcastmeetingsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live_event_v1/api-reference/beta/resources/broadcastmeetingsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastmeetingsettings?view=graph-rest-beta&branch=pr-en-us-14000) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live_event_v1/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-14000) (graph-rest-beta) |
[api-reference/v1.0/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live_event_v1/api-reference/v1.0/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&branch=pr-en-us-14000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/broadcastmeetingsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live_event_v1/api-reference/v1.0/resources/broadcastmeetingsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastmeetingsettings?view=graph-rest-1.0&branch=pr-en-us-14000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/meetingparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live_event_v1/api-reference/v1.0/resources/meetingparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingparticipantinfo?view=graph-rest-1.0&branch=pr-en-us-14000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live_event_v1/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-14000) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live_event_v1/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109012049441354-14000%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=tg%2BpzqynjjzmXNxLe%2Fwyij%2B638NLmWoCwQaNFGCg1VY%3D&st=2021-09-01T20%3A48%3A02Z&se=2021-10-02T20%3A53%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by jasonjoh** [comment]
Docs Build status updates of commit _[8d1f366](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8d1f366f29aca6c3d92b484e9514cdf8bceb7abb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live_event_v1/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-14000) (graph-rest-beta) |
[api-reference/beta/resources/broadcastmeetingsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live_event_v1/api-reference/beta/resources/broadcastmeetingsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastmeetingsettings?view=graph-rest-beta&branch=pr-en-us-14000) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live_event_v1/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-14000) (graph-rest-beta) |
[api-reference/v1.0/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live_event_v1/api-reference/v1.0/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&branch=pr-en-us-14000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/broadcastmeetingsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live_event_v1/api-reference/v1.0/resources/broadcastmeetingsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastmeetingsettings?view=graph-rest-1.0&branch=pr-en-us-14000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/meetingparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live_event_v1/api-reference/v1.0/resources/meetingparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingparticipantinfo?view=graph-rest-1.0&branch=pr-en-us-14000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live_event_v1/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-14000) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/live_event_v1/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109012051579076-14000%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=PG07oaJmoz2x7he5ZJuZncUVRt4sDG9lIyWjwee8rgs%3D&st=2021-09-01T20%3A49%3A45Z&se=2021-10-02T20%3A54%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by frankpeng7** [comment]
@Lauragra this is now ready to merge. Thank you!

**Pull request merged**
