### PR TITLE
UserShiftPreferences app permissions in Beta

### PR DESCRIPTION
**Pull request by akumar39**
This PR includes the changes to Beta Graph docs to add UserShiftPreferences.Read.All and UserShiftPreferences.ReadWrite.All for shiftpreferences resource.
It adds missing documentation for Schedule.Read.All, Schedule.ReadWrite.All user delegated permissions for all applicable Shifts resources and newly supported enum types in workforceintegration _supports_ property.

### CODE REVIEW

**Comment by akumar39** [comment]
Ready for review @Lauragra @Jackson-Woods

**Comment by Lauragra** [comment]
@akumar39 , @Jackson-Woods , are we ready to publish this PR?

**Comment by Jackson-Woods** [comment]
I don't think this needs my approval, but I looked it over and agree it's ready to go. @akumar39 please set the "ready to merge" tag if you're done with the PR.

**Comment by akumar39** [comment]
Updated with Ready to merge tag. What about any new conflicts? @Lauragra

**Comment by Lauragra** [comment]
> Updated with Ready to merge tag. What about any new conflicts? @Lauragra

I don't see any conflicts so this should be good.

**Pull request merged**
