### PR TITLE
improved description of the chatmessagemention id

### PR DESCRIPTION
**Pull request by baywet**

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[a034334](https://github.com/baywet/microsoft-graph-docs/pull/4117/commits/a034334305b9f9651cb73a133e9eb3cda578df76)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 26 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[a034334](https://github.com/baywet/microsoft-graph-docs/pull/4117/commits/a034334305b9f9651cb73a133e9eb3cda578df76)_: 

:clock10: **Incremental building**: average incremental building time is _2 min(s) 4 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[a034334](https://github.com/baywet/microsoft-graph-docs/pull/4117/commits/a034334305b9f9651cb73a133e9eb3cda578df76)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatMention.md](https://github.com/baywet/microsoft-graph-docs/blob/patch-2/api-reference/beta/resources/chatMention.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903072137494005-4117%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=qXoCr8x3lkyqrpII25wyI5ChT%2FXZKSwdGLZHbS8E4g4%3D&st=2019-03-07T21%3A36%3A18Z&se=2019-04-07T21%3A41%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[40b9653](https://github.com/baywet/microsoft-graph-docs/pull/4117/commits/40b9653ffee57037ac682f88ee80bd659fc87fd2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatMention.md](https://github.com/baywet/microsoft-graph-docs/blob/patch-2/api-reference/beta/resources/chatMention.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903271604306887-4117%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=3oJtccc9fzN0MCnh7PtH416lAFmml3XJCk1weoCGiWk%3D&st=2019-03-27T16%3A03%3A07Z&se=2019-04-27T16%3A08%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nkramer** [comment]
Thanks for the contribution! To deal with the merge conflict, I incorporated this into PR
https://github.com/microsoftgraph/microsoft-graph-docs/pull/4393

**Pull request closed without merging**
