### PR TITLE
Added enum to Microsoft AAD

### PR DESCRIPTION
**Pull request by wachuga**

### CODE REVIEW

**Comment by Lauragra** [comment]
@davidmu1 , please review. Are we missing a value in the enum type definition?

**Comment by angelgolfer-ms** [comment]
@davidmu1 , please track down if and where the enum itself is documented. It's not in master right now.

**Comment by davidmu1** [comment]
@wachuga - can you please provide more information about this change? @Lauragra and @angelgolfer-ms , currently this enumeration is not defined in the beta documentation. As is, unless more information is provided, I suggest closing the request.

**Review by davidmu1 — COMMENTED** [review]
The enumeration can't be found in the repository. This change is not currently accurate without more context.

**Pull request closed without merging**
