### PR TITLE
Initial draft of v1.0 pages for directoryAudit and signIn.

### PR DESCRIPTION
**Pull request by lleonard-msft**
- Initial version of updates.  More expected.
- Assorted updates to beta pages.

### CODE REVIEW

**Comment by lleonard-msft** [comment]
Initial commit contains just content changes; once we pass validation, I'll update the changelog and the TOC.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[23aa4f8](https://github.com/lleonard-msft/microsoft-graph-docs/pull/4212/commits/23aa4f83cdbb9edfec4f3e79fa3a619595198f67)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/directoryaudit_list.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/api/directoryaudit_list.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fv1.0%2Fapi%2Fdirectoryaudit_list.md)
[api-reference/v1.0/resources/directoryaudit.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/resources/directoryaudit.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fv1.0%2Fresources%2Fdirectoryaudit.md)
[api-reference/v1.0/resources/restrictedsignin.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/resources/restrictedsignin.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fv1.0%2Fresources%2Frestrictedsignin.md)
[api-reference/v1.0/resources/signin.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/resources/signin.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fv1.0%2Fresources%2Fsignin.md)
[api-reference/beta/api/directoryaudit-get.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/beta/api/directoryaudit-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/directoryaudit-list.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/beta/api/directoryaudit-list.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/restrictedsignin_get.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/beta/api/restrictedsignin_get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/restrictedsignin_list.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/beta/api/restrictedsignin_list.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/signin-get.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/signin-list.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/directoryaudit.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/beta/resources/directoryaudit.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/restrictedsignin.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/beta/resources/restrictedsignin.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/signin.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/directoryaudit_get.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/api/directoryaudit_get.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/restrictedsignin_get.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/api/restrictedsignin_get.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/restrictedsignin_list.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/api/restrictedsignin_list.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/signin_get.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/api/signin_get.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/signin_list.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/api/signin_list.md) | :white_check_mark:Succeeded | |

<a name="api-reference%2Fv1.0%2Fapi%2Fdirectoryaudit_list.md"></a>
### [api-reference/v1.0/api/directoryaudit_list.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/api/directoryaudit_list.md)
 - **Line 66**: **[Warning]** Invalid file link:(~/v1.0/resources/directoryaudit?).

<a name="api-reference%2Fv1.0%2Fresources%2Fdirectoryaudit.md"></a>
### [api-reference/v1.0/resources/directoryaudit.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/resources/directoryaudit.md)
 - **Line 17**: **[Warning]** Invalid file link:(~/v1.0/api/directoryaudit-list.md).
 - **Line 18**: **[Warning]** Invalid file link:(~/v1.0/api/directoryaudit-get.md).
 - **Line 26**: **[Warning]** Invalid file link:(~/v1.0/resources/keyvalue.md).
 - **Line 30**: **[Warning]** Invalid file link:(~/v1.0/resources/auditactivityinitiator.md).
 - **Line 34**: **[Warning]** Invalid file link:(~/v1.0/resources/targetresource.md).

<a name="api-reference%2Fv1.0%2Fresources%2Frestrictedsignin.md"></a>
### [api-reference/v1.0/resources/restrictedsignin.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/resources/restrictedsignin.md)
 - **Line 17**: **[Warning]** Invalid file link:(~/v1.0/api/signin-list.md).
 - **Line 18**: **[Warning]** Invalid file link:(~/v1.0/api/signin-get.md).
 - **Line 25**: **[Warning]** Invalid file link:(~/v1.0/resources/conditionalaccesspolicy.md).
 - **Line 31**: **[Warning]** Invalid file link:(~/v1.0/resources/devicedetail.md).
 - **Line 35**: **[Warning]** Invalid file link:(~/v1.0/resources/signinlocation.md).
 - **Line 36**: **[Warning]** Invalid file link:(~/v1.0/resources/mfadetail.md).
 - **Line 37**: **[Warning]** Invalid file link:(~/v1.0/resources/networklocationdetail.md).
 - **Line 48**: **[Warning]** Invalid file link:(~/v1.0/resources/signinstatus.md).

<a name="api-reference%2Fv1.0%2Fresources%2Fsignin.md"></a>
### [api-reference/v1.0/resources/signin.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/resources/signin.md)
 - **Line 17**: **[Warning]** Invalid file link:(~/v1.0/api/signin-list.md).
 - **Line 18**: **[Warning]** Invalid file link:(~/v1.0/api/signin-get.md).
 - **Line 25**: **[Warning]** Invalid file link:(~/v1.0/resources/conditionalaccesspolicy.md).
 - **Line 31**: **[Warning]** Invalid file link:(~/v1.0/resources/devicedetail.md).
 - **Line 35**: **[Warning]** Invalid file link:(~/v1.0/resources/signinlocation.md).
 - **Line 36**: **[Warning]** Invalid file link:(~/v1.0/resources/mfadetail.md).
 - **Line 37**: **[Warning]** Invalid file link:(~/v1.0/resources/networklocationdetail.md).
 - **Line 48**: **[Warning]** Invalid file link:(~/v1.0/resources/signinstatus.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903201843582126-4212%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=CZJVOcnw13ZNVm76wC1Okc33CR4gpaII%2FbSckUiPQt0%3D&st=2019-03-20T18%3A42%3A31Z&se=2019-04-20T18%3A47%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[5a7559c](https://github.com/lleonard-msft/microsoft-graph-docs/pull/4212/commits/5a7559c2dab044476595fd8eddaf94c2fcc8bced)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/directoryaudit_list.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/api/directoryaudit_list.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fv1.0%2Fapi%2Fdirectoryaudit_list.md)
[api-reference/v1.0/resources/directoryaudit.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/resources/directoryaudit.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fv1.0%2Fresources%2Fdirectoryaudit.md)
[api-reference/v1.0/resources/signin.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/resources/signin.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fv1.0%2Fresources%2Fsignin.md)
[api-reference/beta/api/directoryaudit-get.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/beta/api/directoryaudit-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/directoryaudit-list.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/beta/api/directoryaudit-list.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/signin-get.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/signin-list.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/directoryaudit.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/beta/resources/directoryaudit.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/signin.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/directoryaudit_get.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/api/directoryaudit_get.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/signin_get.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/api/signin_get.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/signin_list.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/api/signin_list.md) | :white_check_mark:Succeeded | |

<a name="api-reference%2Fv1.0%2Fapi%2Fdirectoryaudit_list.md"></a>
### [api-reference/v1.0/api/directoryaudit_list.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/api/directoryaudit_list.md)
 - **Line 66**: **[Warning]** Invalid file link:(~/v1.0/resources/directoryaudit?).

<a name="api-reference%2Fv1.0%2Fresources%2Fdirectoryaudit.md"></a>
### [api-reference/v1.0/resources/directoryaudit.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/resources/directoryaudit.md)
 - **Line 17**: **[Warning]** Invalid file link:(~/v1.0/api/directoryaudit-list.md).
 - **Line 18**: **[Warning]** Invalid file link:(~/v1.0/api/directoryaudit-get.md).
 - **Line 26**: **[Warning]** Invalid file link:(~/v1.0/resources/keyvalue.md).
 - **Line 30**: **[Warning]** Invalid file link:(~/v1.0/resources/auditactivityinitiator.md).
 - **Line 34**: **[Warning]** Invalid file link:(~/v1.0/resources/targetresource.md).

<a name="api-reference%2Fv1.0%2Fresources%2Fsignin.md"></a>
### [api-reference/v1.0/resources/signin.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/resources/signin.md)
 - **Line 17**: **[Warning]** Invalid file link:(~/v1.0/api/signin-list.md).
 - **Line 18**: **[Warning]** Invalid file link:(~/v1.0/api/signin-get.md).
 - **Line 25**: **[Warning]** Invalid file link:(~/v1.0/resources/conditionalaccesspolicy.md).
 - **Line 30**: **[Warning]** Invalid file link:(~/v1.0/resources/devicedetail.md).
 - **Line 34**: **[Warning]** Invalid file link:(~/v1.0/resources/signinlocation.md).
 - **Line 35**: **[Warning]** Invalid file link:(~/v1.0/resources/mfadetail.md).
 - **Line 36**: **[Warning]** Invalid file link:(~/v1.0/resources/networklocationdetail.md).
 - **Line 47**: **[Warning]** Invalid file link:(~/v1.0/resources/signinstatus.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903210245135065-4212%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=bKtzFKOKBg%2FUtohGFL%2BGF9jBXoAZuQbYljTSsY%2F3%2B6Q%3D&st=2019-03-21T02%3A43%3A50Z&se=2019-04-21T02%3A48%3A50Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[6afd67d](https://github.com/lleonard-msft/microsoft-graph-docs/pull/4212/commits/6afd67d4d9ef82d3723f566de7cafd67b819aeba)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/directoryaudit.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/resources/directoryaudit.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fv1.0%2Fresources%2Fdirectoryaudit.md)
[api-reference/v1.0/resources/signin.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/resources/signin.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fv1.0%2Fresources%2Fsignin.md)
[api-reference/beta/api/directoryaudit-get.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/beta/api/directoryaudit-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/directoryaudit-list.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/beta/api/directoryaudit-list.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/signin-get.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/signin-list.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/directoryaudit.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/beta/resources/directoryaudit.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/signin.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/directoryaudit_get.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/api/directoryaudit_get.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/directoryaudit_list.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/api/directoryaudit_list.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/signin_get.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/api/signin_get.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/signin_list.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/api/signin_list.md) | :white_check_mark:Succeeded | |

<a name="api-reference%2Fv1.0%2Fresources%2Fdirectoryaudit.md"></a>
### [api-reference/v1.0/resources/directoryaudit.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/resources/directoryaudit.md)
 - **Line 17**: **[Warning]** Invalid file link:(~/v1.0/api/directoryaudit-list.md).
 - **Line 18**: **[Warning]** Invalid file link:(~/v1.0/api/directoryaudit-get.md).
 - **Line 26**: **[Warning]** Invalid file link:(~/v1.0/resources/keyvalue.md).
 - **Line 30**: **[Warning]** Invalid file link:(~/v1.0/resources/auditactivityinitiator.md).
 - **Line 34**: **[Warning]** Invalid file link:(~/v1.0/resources/targetresource.md).

<a name="api-reference%2Fv1.0%2Fresources%2Fsignin.md"></a>
### [api-reference/v1.0/resources/signin.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/resources/signin.md)
 - **Line 17**: **[Warning]** Invalid file link:(~/v1.0/api/signin-list.md).
 - **Line 18**: **[Warning]** Invalid file link:(~/v1.0/api/signin-get.md).
 - **Line 25**: **[Warning]** Invalid file link:(~/v1.0/resources/conditionalaccesspolicy.md).
 - **Line 30**: **[Warning]** Invalid file link:(~/v1.0/resources/devicedetail.md).
 - **Line 34**: **[Warning]** Invalid file link:(~/v1.0/resources/signinlocation.md).
 - **Line 35**: **[Warning]** Invalid file link:(~/v1.0/resources/mfadetail.md).
 - **Line 36**: **[Warning]** Invalid file link:(~/v1.0/resources/networklocationdetail.md).
 - **Line 47**: **[Warning]** Invalid file link:(~/v1.0/resources/signinstatus.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903210626500052-4212%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=bn08jI0Bk83XAcMYlBgQrmSohHUkzJMvwdwUtpWzvOw%3D&st=2019-03-21T06%3A25%3A23Z&se=2019-04-21T06%3A30%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[b13cf8a](https://github.com/lleonard-msft/microsoft-graph-docs/pull/4212/commits/b13cf8a729a65b3c635af59833700fc9ba7ef886)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/directoryaudit.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/resources/directoryaudit.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fv1.0%2Fresources%2Fdirectoryaudit.md)
[api-reference/v1.0/resources/signin.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/resources/signin.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fv1.0%2Fresources%2Fsignin.md)
[api-reference/beta/api/directoryaudit-get.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/beta/api/directoryaudit-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/directoryaudit-list.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/beta/api/directoryaudit-list.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/signin-get.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/signin-list.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/directoryaudit.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/beta/resources/directoryaudit.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/signin.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/directoryaudit_get.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/api/directoryaudit_get.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/directoryaudit_list.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/api/directoryaudit_list.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/signin_get.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/api/signin_get.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/signin_list.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/api/signin_list.md) | :white_check_mark:Succeeded | |

<a name="api-reference%2Fv1.0%2Fresources%2Fdirectoryaudit.md"></a>
### [api-reference/v1.0/resources/directoryaudit.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/resources/directoryaudit.md)
 - **Line 17**: **[Warning]** Invalid file link:(~/v1.0/api/directoryaudit-list.md).
 - **Line 18**: **[Warning]** Invalid file link:(~/v1.0/api/directoryaudit-get.md).
 - **Line 26**: **[Warning]** Invalid file link:(~/v1.0/resources/keyvalue.md).
 - **Line 30**: **[Warning]** Invalid file link:(~/v1.0/resources/auditactivityinitiator.md).
 - **Line 34**: **[Warning]** Invalid file link:(~/v1.0/resources/targetresource.md).

<a name="api-reference%2Fv1.0%2Fresources%2Fsignin.md"></a>
### [api-reference/v1.0/resources/signin.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/update-signin-v1.0/api-reference/v1.0/resources/signin.md)
 - **Line 17**: **[Warning]** Invalid file link:(~/v1.0/api/signin-list.md).
 - **Line 18**: **[Warning]** Invalid file link:(~/v1.0/api/signin-get.md).
 - **Line 25**: **[Warning]** Invalid file link:(~/v1.0/resources/conditionalaccesspolicy.md).
 - **Line 30**: **[Warning]** Invalid file link:(~/v1.0/resources/devicedetail.md).
 - **Line 34**: **[Warning]** Invalid file link:(~/v1.0/resources/signinlocation.md).
 - **Line 35**: **[Warning]** Invalid file link:(~/v1.0/resources/mfadetail.md).
 - **Line 36**: **[Warning]** Invalid file link:(~/v1.0/resources/networklocationdetail.md).
 - **Line 47**: **[Warning]** Invalid file link:(~/v1.0/resources/signinstatus.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903211346499783-4212%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=XI6oxpn4c9Q15yYMfFLFllGyfnScrWdAx5JKzhDvg5M%3D&st=2019-03-21T13%3A45%3A41Z&se=2019-04-21T13%3A50%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
