### PR TITLE
Attempting to add dataPolicyOperation to beta and v1.0 menus.

### PR DESCRIPTION
**Pull request by lleonard-msft**
Attempting to add TOC entries for the following PRs:
- PR #3410 
- PR #3396 
- PR #3395

### CODE REVIEW

**Comment by lleonard-msft** [comment]
@Lauragra - Please verify that I did this correctly.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[9658084](https://github.com/lleonard-msft/microsoft-graph-docs/pull/3643/commits/9658084aa0a921e62f106ae1fd2db3a7866a0fb0)_: 

### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/aad-id-datapolicy-toc/api-reference/v1.0/toc.yml) | :x:Error | | [Details](#user-content-api-reference%2Fv1.0%2Ftoc.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="api-reference%2Fv1.0%2Ftoc.yml"></a>
### [api-reference/v1.0/toc.yml](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/aad-id-datapolicy-toc/api-reference/v1.0/toc.yml)
 - **[Error]** W:\w3mk-s\api-reference\v1.0\toc.yml is not a valid TOC File: W:\w3mk-s\api-reference\v1.0\toc.yml is not a valid TOC file, detail: (Line: 3049, Col: 9, Idx: 146418) - (Line: 3049, Col: 10, Idx: 146419): While parsing a block mapping, did not find expected key..
 - **[Error]** W:\w3mk-s\api-reference\v1.0\toc.yml is not a valid TOC File: W:\w3mk-s\api-reference\v1.0\toc.yml is not a valid TOC file, detail: (Line: 3049, Col: 9, Idx: 146418) - (Line: 3049, Col: 10, Idx: 146419): While parsing a block mapping, did not find expected key..
 - **[Error]** Unable to load file: v1.0/toc.yml via processor: TocDocumentProcessor: W:\w3mk-s\api-reference\v1.0\toc.yml is not a valid TOC File: W:\w3mk-s\api-reference\v1.0\toc.yml is not a valid TOC file, detail: (Line: 3049, Col: 9, Idx: 146418) - (Line: 3049, Col: 10, Idx: 146419): While parsing a block mapping, did not find expected key..
 - **[Error]** Unable to load file: v1.0/toc.yml via processor: ExperimentalTocDocumentProcessor: W:\w3mk-s\api-reference\v1.0\toc.yml is not a valid TOC File: W:\w3mk-s\api-reference\v1.0\toc.yml is not a valid TOC file, detail: (Line: 3049, Col: 9, Idx: 146418) - (Line: 3049, Col: 10, Idx: 146419): While parsing a block mapping, did not find expected key..

<a name=""></a>
### []()
 - **[Error]** W:\w3mk-s\api-reference\v1.0\toc.yml is not a valid TOC File: W:\w3mk-s\api-reference\v1.0\toc.yml is not a valid TOC file, detail: (Line: 3049, Col: 9, Idx: 146418) - (Line: 3049, Col: 10, Idx: 146419): While parsing a block mapping, did not find expected key..

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201812142347085740-3643%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=GzISRDJV3WrBQBApUDzpx6I%2BrhUzJoyaFE7q5dtPPv0%3D&st=2018-12-14T23%3A43%3A58Z&se=2019-01-14T23%3A48%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[c906cad](https://github.com/lleonard-msft/microsoft-graph-docs/pull/3643/commits/c906cad2f5f865fe478b0efb26737c35985d8e49)_: 

### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/aad-id-datapolicy-toc/api-reference/v1.0/toc.yml) | :x:Error | | [Details](#user-content-api-reference%2Fv1.0%2Ftoc.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="api-reference%2Fv1.0%2Ftoc.yml"></a>
### [api-reference/v1.0/toc.yml](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/aad-id-datapolicy-toc/api-reference/v1.0/toc.yml)
 - **[Error]** W:\d5j0-s\api-reference\v1.0\toc.yml is not a valid TOC File: W:\d5j0-s\api-reference\v1.0\toc.yml is not a valid TOC file, detail: (Line: 3049, Col: 9, Idx: 146418) - (Line: 3049, Col: 10, Idx: 146419): While parsing a block mapping, did not find expected key..
 - **[Error]** Unable to load file: v1.0/toc.yml via processor: TocDocumentProcessor: W:\d5j0-s\api-reference\v1.0\toc.yml is not a valid TOC File: W:\d5j0-s\api-reference\v1.0\toc.yml is not a valid TOC file, detail: (Line: 3049, Col: 9, Idx: 146418) - (Line: 3049, Col: 10, Idx: 146419): While parsing a block mapping, did not find expected key..

<a name=""></a>
### []()
 - **[Error]** W:\d5j0-s\api-reference\v1.0\toc.yml is not a valid TOC File: W:\d5j0-s\api-reference\v1.0\toc.yml is not a valid TOC file, detail: (Line: 3049, Col: 9, Idx: 146418) - (Line: 3049, Col: 10, Idx: 146419): While parsing a block mapping, did not find expected key..

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201812150100140753-3643%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=RQp2kWeUOEBiMY57x2L9IoxV%2B6i%2FMgCVpHGGp20Sx1k%3D&st=2018-12-15T00%3A57%3A34Z&se=2019-01-15T01%3A02%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[f17c1c3](https://github.com/lleonard-msft/microsoft-graph-docs/pull/3643/commits/f17c1c319a9c0c0aa29d056807cdfba60a88ab77)_: 

### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/aad-id-datapolicy-toc/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-api-reference%2Fbeta%2Ftoc.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="api-reference%2Fbeta%2Ftoc.yml"></a>
### [api-reference/beta/toc.yml](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/aad-id-datapolicy-toc/api-reference/beta/toc.yml)
 - **[Error]** W:\koyc-s\api-reference\beta\toc.yml is not a valid TOC File: W:\koyc-s\api-reference\beta\toc.yml is not a valid TOC file, detail: (Line: 6260, Col: 9, Idx: 314389) - (Line: 6260, Col: 10, Idx: 314390): While parsing a block mapping, did not find expected key..
 - **[Error]** Unable to load file: beta/toc.yml via processor: ExperimentalTocDocumentProcessor: W:\koyc-s\api-reference\beta\toc.yml is not a valid TOC File: W:\koyc-s\api-reference\beta\toc.yml is not a valid TOC file, detail: (Line: 6260, Col: 9, Idx: 314389) - (Line: 6260, Col: 10, Idx: 314390): While parsing a block mapping, did not find expected key..
 - **[Error]** W:\koyc-s\api-reference\beta\toc.yml is not a valid TOC File: W:\koyc-s\api-reference\beta\toc.yml is not a valid TOC file, detail: (Line: 6260, Col: 9, Idx: 314389) - (Line: 6260, Col: 10, Idx: 314390): While parsing a block mapping, did not find expected key..
 - **[Error]** Unable to load file: beta/toc.yml via processor: TocDocumentProcessor: W:\koyc-s\api-reference\beta\toc.yml is not a valid TOC File: W:\koyc-s\api-reference\beta\toc.yml is not a valid TOC file, detail: (Line: 6260, Col: 9, Idx: 314389) - (Line: 6260, Col: 10, Idx: 314390): While parsing a block mapping, did not find expected key..

<a name=""></a>
### []()
 - **[Error]** W:\koyc-s\api-reference\beta\toc.yml is not a valid TOC File: W:\koyc-s\api-reference\beta\toc.yml is not a valid TOC file, detail: (Line: 6260, Col: 9, Idx: 314389) - (Line: 6260, Col: 10, Idx: 314390): While parsing a block mapping, did not find expected key..

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201812150302572692-3643%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Y%2B5Y1j4nUwhk5m1YuSKfSzSyoUbHA3rymHiOTcPIj0c%3D&st=2018-12-15T03%3A00%3A32Z&se=2019-01-15T03%3A05%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[59b577b](https://github.com/lleonard-msft/microsoft-graph-docs/pull/3643/commits/59b577b7493269e31d79fe90b7f3d7893659009d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/aad-id-datapolicy-toc/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | |
[api-reference/v1.0/toc.yml](https://github.com/lleonard-msft/microsoft-graph-docs/blob/update/aad-id-datapolicy-toc/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201812150304107637-3643%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=oISSUkPVOldZneEj13MZN88XFrcPMe4FzqFqlFXvXJM%3D&st=2018-12-15T03%3A05%3A48Z&se=2019-01-15T03%3A10%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
