### PR TITLE
[Universal Print] Adding printIdentity and printUserIdentity references

### PR DESCRIPTION
**Pull request by braedenp-msft**
Adding `printIdentity` and `printUserIdentity` types and correcting references in the allowedUsers/Groups APIs.

### CODE REVIEW

**Comment by braedenp-msft** [comment]
> @braedenp-msft , thanks for making this fix.
> Please also fix printer.md and printershare.md - their Methods table has the incorrect types in the Return Type column, for the related 2 "list" methods.
> With those fixes, we'd be good to publish.
> Thanks!

Good catch, thanks!

Fixed.

**Comment by braedenp-msft** [comment]
> @braedenp-msft , can you include a changelog entry with this update please? Thanks!

These updates are just to reflect what has existed in the API all along (the documentation was incorrect before).

Should I still create a changelog entry?

**Comment by Lauragra** [comment]
> > @braedenp-msft , can you include a changelog entry with this update please? Thanks!
> 
> These updates are just to reflect what has existed in the API all along (the documentation was incorrect before).
> 
> Should I still create a changelog entry?

Yes, we still want a changelog entry to call users' attention to the new docs. It can go in the table in the April entry.

**Comment by braedenp-msft** [comment]
> > > @braedenp-msft , can you include a changelog entry with this update please? Thanks!
> > 
> > 
> > These updates are just to reflect what has existed in the API all along (the documentation was incorrect before).
> > Should I still create a changelog entry?
> 
> Yes, we still want a changelog entry to call users' attention to the new docs. It can go in the table in the April entry.

Done!

**Pull request merged**
