### PR TITLE
Update /shares/ documentation

### PR DESCRIPTION
**Pull request by kevklam**
Updating docs with some functionality that has been live in production for a while

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[df810c8](https://github.com/kevklam/microsoft-graph-docs/pull/3841/commits/df810c8094d51697bcfd83d4fbb21cb95f2b5e97)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[df810c8](https://github.com/kevklam/microsoft-graph-docs/pull/3841/commits/df810c8094d51697bcfd83d4fbb21cb95f2b5e97)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[df810c8](https://github.com/kevklam/microsoft-graph-docs/pull/3841/commits/df810c8094d51697bcfd83d4fbb21cb95f2b5e97)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/shares-get.md](https://github.com/kevklam/microsoft-graph-docs/blob/kevinlam-sharesUpdates/api-reference/beta/api/shares-get.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/shares-get.md](https://github.com/kevklam/microsoft-graph-docs/blob/kevinlam-sharesUpdates/api-reference/v1.0/api/shares-get.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901231957406571-3841%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=SWDrVZmI2yLFjcpXiy%2BZvuJD4ojK1ntAXKjwlGUcBzQ%3D&st=2019-01-23T19%3A56%3A06Z&se=2019-02-23T20%3A01%3A06Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
@kevklam , when do you want to merge this PR?

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[135f793](https://github.com/kevklam/microsoft-graph-docs/pull/3841/commits/135f7932f3bb2d2fd2e569921c20d58ce6ae3f83)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[135f793](https://github.com/kevklam/microsoft-graph-docs/pull/3841/commits/135f7932f3bb2d2fd2e569921c20d58ce6ae3f83)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/shares-get.md](https://github.com/kevklam/microsoft-graph-docs/blob/kevinlam-sharesUpdates/api-reference/beta/api/shares-get.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/shares-get.md](https://github.com/kevklam/microsoft-graph-docs/blob/kevinlam-sharesUpdates/api-reference/v1.0/api/shares-get.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901240127522808-3841%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=qsKWIE6fAGCL5RMY%2BD2ar6xurlgs2srNkfS%2BZ31lpsQ%3D&st=2019-01-24T01%3A28%3A55Z&se=2019-02-24T01%3A33%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
