### PR TITLE
signInFrequency beta to v1

### PR DESCRIPTION
**Pull request by rckyplln**
Moving signInFrequency from beta to v1

### CODE REVIEW

**Comment by rckyplln** [comment]
Including the PR for the engineering-side changes: https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/6306274

**Review by FaithOmbongi — APPROVED** [review]
Thank you @rckyplln for your work in this PR. I've left suggestions for minor fixes. Approved with suggestions.

**Comment by FaithOmbongi** [comment]
Heads up @rckyplln - I see the schema for these changes is live. When you're ready to make the docs public, replace the **do notvmerge** label with **ready to merge**.

**Comment by rckyplln** [comment]
Adding @Inbar Cizer ***@***.***> as she is taking over this feature.

/ricky

**Comment by rckyplln** [comment]
FYI @Inbar Cizer ***@***.***>

/ricky

**Pull request merged**
