### PR TITLE
AAD applications are not supported

### PR DESCRIPTION
**Pull request by woter1832**
Make it abundantly clear AAD applications are not supported

### CODE REVIEW

**Comment by FaithOmbongi** [comment]
Hi @woter1832 - Thank you for your contribution.

Can you provide more context as to this change? For example, when you say Azure AD applications aren't supported, do you mean that a user can't call this API from a Microsoft-owned application? Please help me understand the comment.

**Comment by woter1832** [comment]
@FaithOmbongi,

Authenticating with an AAD application is not supported. It must be a user.

AAD app = SPN or App registration. (client_id / client_secret).

I wasted a whole day messing around with Graph permissions trying to get this endpoint to work with an AAD app. I want to prevent others going through the same pain by explicitly calling it out.

**Comment by FaithOmbongi** [comment]
> @FaithOmbongi,
> 
> Authenticating with an AAD application is not supported. It must be a user.
> 
> AAD app = SPN or App registration. (client_id / client_secret).
> 
> I wasted a whole day messing around with Graph permissions trying to get this endpoint to work with an AAD app. I want to prevent others going through the same pain by explicitly calling it out.

Hi @woter1832 - Ah, now I've understood.

Yes, that's correct, app-only scenarios aren't supported.
But we already communicate this in the "Application" row of the permissions table which shows "Not supported."
Let me know if this helps.

**Comment by FaithOmbongi** [comment]
Hi @woter1832 - I hope my response cleared up how we document unsupported access scenarios per API. I'll close this PR.

Feel free to file a docs issue and leave suggestions on how we can improve.

**Pull request closed without merging**
