### PR TITLE
Corrected scope name for Microsoft Graph

### PR DESCRIPTION
**Pull request by stianstrysse**
As far as I know, there is no Graph scope named 'RoleManagement.ReadWrite.All', not many hits on Google for this value - I only found two articles on docs.microsoft.com and I'm submitting a PR for both of them.

I believe the correct scope name is 'RoleManagement.ReadWrite.Directory'

#ATCP

### CODE REVIEW

**Comment by stianstrysse** [comment]
PR for the second article on docs.microsoft.com with the wrong scope name: https://github.com/MicrosoftDocs/azure-docs/pull/86063

**Comment by stianstrysse** [comment]
image

**Comment by Lauragra** [comment]
@FaithOmbongi , can you verify this PR please? There is a similar reference to RoleManagement.ReadWrite.All in the permissions reference topic. Thanks.

**Review by FaithOmbongi — APPROVED** [review]
Great catch @stianstrysse; and thank you for raising this PR. Approved. Should be merged on Friday.

**Comment by stianstrysse** [comment]
Thanks, @FaithOmbongi! :)

Anything we need to do about this check?

image

**Comment by FaithOmbongi** [comment]
> Thanks, @FaithOmbongi! :)
> 
> Anything we need to do about this check?
> 
> image

Hi @stianstrysse, don't worry about it. @Lauragra will run the flow.

**Pull request merged**
