### PR TITLE
remove unwanted comma

### PR DESCRIPTION
**Pull request by paul-cheung**

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[6a4cce8](https://github.com/paul-cheung/microsoft-graph-docs/pull/3995/commits/6a4cce818a1fa9aa8fe58813dd346688105d5158)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 24 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[6a4cce8](https://github.com/paul-cheung/microsoft-graph-docs/pull/3995/commits/6a4cce818a1fa9aa8fe58813dd346688105d5158)_: 

:clock10: **Incremental building**: average incremental building time is _2 min(s) 2 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[6a4cce8](https://github.com/paul-cheung/microsoft-graph-docs/pull/3995/commits/6a4cce818a1fa9aa8fe58813dd346688105d5158)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/channel.md](https://github.com/paul-cheung/microsoft-graph-docs/blob/channel-json-format/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902160901306348-3995%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=KBXBRLLPG8NSeBdeW1T7rFbuI4jWsYkhSakjUQj%2F6bM%3D&st=2019-02-16T09%3A00%3A17Z&se=2019-03-19T09%3A05%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by paul-cheung** [comment]
@jthake-msft so why is this PR blocked?

**Pull request merged**
