### PR TITLE
Update docs for addition of new property to group object in beta.

### PR DESCRIPTION
**Pull request by samridhigupta**

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[37bc7c2](https://github.com/samridhigupta/microsoft-graph-docs/pull/3671/commits/37bc7c2d48e297cf8dad052de0e52a3ffcb31372)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 20 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[37bc7c2](https://github.com/samridhigupta/microsoft-graph-docs/pull/3671/commits/37bc7c2d48e297cf8dad052de0e52a3ffcb31372)_: 

### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **Line 386**: **[Error]** Error happened in build.entrypoint.ps1. Please build your target branch first and then reopen this pull request to do another round of verification. If the issue still happens, open a ticket in http://SiteHelp and include the following error message for our team to troubleshoot: The process cannot access the file &#39;W:\2fz3-log-37844676\report.txt&#39; because it is being used by another process.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201812200330238317-3671%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=q%2FUom7hPYllyyx0FcaqsPDRAJjsmJD3LB8DrsjJf338%3D&st=2018-12-20T03%3A26%3A41Z&se=2019-01-20T03%3A31%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[37bc7c2](https://github.com/samridhigupta/microsoft-graph-docs/pull/3671/commits/37bc7c2d48e297cf8dad052de0e52a3ffcb31372)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 20 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[37bc7c2](https://github.com/samridhigupta/microsoft-graph-docs/pull/3671/commits/37bc7c2d48e297cf8dad052de0e52a3ffcb31372)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[37bc7c2](https://github.com/samridhigupta/microsoft-graph-docs/pull/3671/commits/37bc7c2d48e297cf8dad052de0e52a3ffcb31372)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/group.md](https://github.com/samridhigupta/microsoft-graph-docs/blob/samgupta-aadGroup-expirationDateTime/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/samridhigupta/microsoft-graph-docs/blob/samgupta-aadGroup-expirationDateTime/concepts/changelog.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201812201947167649-3671%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=MStctN8lEwluvSAtoPLWyOds9c%2FGYKvyZQZH35YHXvs%3D&st=2018-12-20T19%3A45%3A47Z&se=2019-01-20T19%3A50%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[37bc7c2](https://github.com/samridhigupta/microsoft-graph-docs/pull/3671/commits/37bc7c2d48e297cf8dad052de0e52a3ffcb31372)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 20 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[37bc7c2](https://github.com/samridhigupta/microsoft-graph-docs/pull/3671/commits/37bc7c2d48e297cf8dad052de0e52a3ffcb31372)_: 

### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Run script failed with no detailed information. Please retry building your content again. If the issue still happens, open a ticket in http://SiteHelp and include the error report for our team to troubleshoot

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201812270111475397-3671%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=dKnxr2mUQfZN2UuNMSxFX1lKyqZzuO6smuF1JtFwp6M%3D&st=2018-12-27T01%3A08%3A02Z&se=2019-01-27T01%3A13%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
Closing as this is a duplicate PR.

**Pull request closed without merging**
