### PR TITLE
Updating user resource to add 2 new properties

### PR DESCRIPTION
**Pull request by aybankaMSFT**
2 new properties are being added to the user resource on the v1.0 public endpoint.

### CODE REVIEW

**Comment by Lauragra** [comment]
@aybankaMSFT , please add a changelog entry for the new properties. Do you need to update any examples? What is the merge status of this PR?

**Comment by aybankaMSFT** [comment]
@Lauragra this is the PR for the changelog
https://github.com/microsoftgraph/microsoft-graph-docs/pull/8316

Please wait until next week before merging this PR, our last leg of changes were not completely rolled out this week due to MSBuild, I will add a comment sometime next week when we can merge both the PRs, for changelog and this one.
Thanks

**Comment by Lauragra** [comment]
> @Lauragra this is the PR for the changelog
> #8316
> 
> Please wait until next week before merging this PR, our last leg of changes were not completely rolled out this week due to MSBuild, I will add a comment sometime next week when we can merge both the PRs, for changelog and this one.
> Thanks

Please set **ready to merge** on both PRs when you're ready to publish. Thanks.

**Comment by aybankaMSFT** [comment]
@Lauragra deployments have completed, please merge this PR. Thanks

**Comment by aybankaMSFT** [comment]
@Lauragra  changelog PR is here
https://github.com/microsoftgraph/microsoft-graph-docs/pull/8316

**Comment by Lauragra** [comment]
> @Lauragra deployments have completed, please merge this PR. Thanks

In the future to make it easier to process your PRs, please include your changelog entry in the same PR with your change. Please also set the **ready to merge** label on your PRs when you're ready to publish.

**Pull request merged**
