### PR TITLE
Add ThreatIndicators.Read.All to the permissions

### PR DESCRIPTION
**Pull request by shaofengbu**

### CODE REVIEW

**Comment by Lauragra** [comment]
@shaofengbu , what is the merge status of this PR? Thanks.

**Comment by shaofengbu** [comment]
The Validation passed.

All checks have passed.

Chiguyen1 added ‘do not merge’ label.

https://github.com/microsoftgraph/microsoft-graph-docs/pull/7205

**Comment by shaofengbu** [comment]
Sorry to reply with wrong PR link. Please ignore the last email.

Shaofeng


From: Shaofeng Bu
Sent: Wednesday, February 26, 2020 11:35 AM
To: microsoftgraph/microsoft-graph-docs <reply@reply.github.com>; microsoftgraph/microsoft-graph-docs <microsoft-graph-docs@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [microsoftgraph/microsoft-graph-docs] Add ThreatIndicators.Read.All to the permissions (#7197)

The Validation passed.

All checks have passed.

Chiguyen1 added ‘do not merge’ label.

https://github.com/microsoftgraph/microsoft-graph-docs/pull/7205

**Comment by shaofengbu** [comment]
@Lauragra All checks have passed. I could not merge this PR.

**Comment by Lauragra** [comment]
@shaofengbu , contributors don't have merge permissions on the repo. When you're ready to have a PR merged, set the **ready to merge** label on the PR and it will show up in my publishing queue.

**Pull request merged**
