### PR TITLE
Replace placeholder query term in examples

### PR DESCRIPTION
**Pull request by BrianTJackett**
Replacing placeholder query term with actual search text in HTTP examples.  Reduces confusion around curly braces being placeholders, not literals.  Unsure how to update the included snippets from SDKs as they appear auto-generated.

### CODE REVIEW

**Comment by Lauragra** [comment]
@BrianTJackett , the snippets will be updated via the automation that runs every Tuesday. I think we can merge this PR?

**Comment by BrianTJackett** [comment]
@Lauragra so the automation will pull from the HTTP request listed in the doc?  I'm not familiar with that process so want to make sure it doesn't result in broken sample.  Other than that I have no issues with merging.

**Comment by Lauragra** [comment]
> @Lauragra so the automation will pull from the HTTP request listed in the doc? I'm not familiar with that process so want to make sure it doesn't result in broken sample. Other than that I have no issues with merging.

It should, yes, the process only runs on Tuesdays. Do you want to go ahead and merge, or wait until Monday?

**Comment by BrianTJackett** [comment]
I'm ok with merging now.  Will check back next week to ensure snippets updated properly.

**Comment by Lauragra** [comment]
@BrianTJackett , FYI, in the future, if you update a v1.0 topic, be sure to update the beta version of the topic as well (if it has the same issue).

**Comment by BrianTJackett** [comment]
Thank you for reminder on updating v1.0 and beta.  I normally do but I originally found this on the OneDrive docs (also submitted PR there) and forgot to check both versions of Graph docs.  Thanks again.

**Pull request merged**
