### PR TITLE
Update tokenlifetimepolicy.md

### PR DESCRIPTION
**Pull request by lujiangfeng666**
https://github.com/microsoftgraph/microsoft-graph-docs/issues/10906 - it does make sense to remove

### CODE REVIEW

**Comment by lujiangfeng666** [comment]
#sign-off

**Review by davidmu1 — APPROVED** [review]

**Comment by jasonjoh** [comment]
Please disregard the earlier message from msftbot. Your pull request was incorrectly flagged.

**Comment by lujiangfeng666** [comment]
#sign-off

**Comment by lujiangfeng666** [comment]
@davidmu1 any idea why this is never published?

**Comment by lujiangfeng666** [comment]
#sign-off

**Pull request merged**
