### PR TITLE
Rossten/outcomes

### PR DESCRIPTION
**Pull request by rossten**
This change adds rubrics and outcomes to education assignments.

A rubric is a grading tool; a matrix of qualities and levels.  Rubrics are created by and contained under a teacher's "user"; rubrics can be attached to assignments by reference.

An outcome is the result of a teacher grading a student's submission; outcomes can be points, feedback, rubrics, or a collection of multiple of these types.

### CODE REVIEW

**Comment by Lauragra** [comment]
@rossten , did you use the stub generator tool to generate these files?

**Comment by rossten** [comment]
No, I didn’t know that was a thing.  Where do I find that?

**Comment by Lauragra** [comment]
You can find information here: https://msgo.azurewebsites.net/add/document/guidelines/stub-generator.html

**Comment by rossten** [comment]
That looks extremely helpful; thank you.  Do you want me to re-create the new doc files using that tool?

**Comment by Lauragra** [comment]
If you can, that will help you get around the validation errors we're seeing on your current PR.

**Comment by rossten** [comment]
OK, I’ll work on that.

**Pull request closed without merging**
