### PR TITLE
Correction for Delta query and Microsoft Planner

### PR DESCRIPTION
**Pull request by negoe**
Correction for Delta query and Microsoft Planner not supported in National Cloud.

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[8e45e38](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3946/commits/8e45e38edc19a680cbd74efeeb89549ccb1a3c6d)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 24 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[8e45e38](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3946/commits/8e45e38edc19a680cbd74efeeb89549ccb1a3c6d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/microsoftgraph/microsoft-graph-docs, working directory: W:\tgzd-s, target branch: master, target branch commit: f024cc3c181736dc51a07f834c582baae31d28b3, source branch: negoe-graph-nationalclouds, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902080806121481-3946%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=DP9XOINE5p7ki4lkIL5x5cOmzTvkKKoWU%2BpnhzNKKU8%3D&st=2019-02-08T08%3A02%3A13Z&se=2019-03-11T08%3A07%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[e68c62f](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3946/commits/e68c62f2f6afda64fac09ae9ce9b8eba465ee0ad)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 24 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[e68c62f](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3946/commits/e68c62f2f6afda64fac09ae9ce9b8eba465ee0ad)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/microsoftgraph/microsoft-graph-docs, working directory: W:\b1iv-s, target branch: master, target branch commit: f024cc3c181736dc51a07f834c582baae31d28b3, source branch: negoe-graph-nationalclouds, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902081602581794-3946%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=9KucF8pbc839GmA8Nu5%2B4Keo9daT6VhvEIdiaCXDCgY%3D&st=2019-02-08T15%3A59%3A02Z&se=2019-03-11T16%3A04%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[80601d6](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3946/commits/80601d68bf4ddc656f4481e8294b1e9673f51f56)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 24 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[80601d6](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3946/commits/80601d68bf4ddc656f4481e8294b1e9673f51f56)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 59 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[80601d6](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3946/commits/80601d68bf4ddc656f4481e8294b1e9673f51f56)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/deployments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/negoe-graph-nationalclouds/concepts/deployments.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902081606009214-3946%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=4UvpoFd5O%2Bus8mmcA%2BCMLpSjUAmzOFPsJORaLTD9bZA%3D&st=2019-02-08T16%3A04%3A37Z&se=2019-03-11T16%3A09%3A37Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by negoe** [comment]
@Lauragra Hi Laura, I am not able to see changes I made, reflected on the page.

**Comment by Lauragra** [comment]
@negoe , I'm publishing this update today. I just opened the PR.

**Pull request merged**
