### PR TITLE
Update organizationalbranding.md

### PR DESCRIPTION
**Pull request by AlexanderMars**
Added squareLogoDark property

Schema update PR: 6327279

### CODE REVIEW

**Review by FaithOmbongi — COMMENTED** [review]
Thank you @AlexanderMars for your work in this PR. 

The changes look good. LMK once the schema PR is ready so I can do a comparison before approval.

**Comment by AlexanderMars** [comment]
> Thank you @AlexanderMars for your work in this PR.
> 
> The changes look good. LMK once the schema PR is ready so I can do a comparison before approval.

I hope this PR works https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/10729
It's already LIVE in Beta prod.

**Comment by FaithOmbongi** [comment]
> > Thank you @AlexanderMars for your work in this PR.
> > The changes look good. LMK once the schema PR is ready so I can do a comparison before approval.
> 
> I hope this PR works https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/10729 It's already LIVE in Beta prod.

Hi @AlexanderMars - That's the API.md PR. Yes, I see the property is live in the beta response payload but it's not yet in the [public schema](https://developer.microsoft.com/en-us/graph/graph-explorer?request=%24metadata&method=GET&version=beta&GraphUrl=https://graph.microsoft.com).

**Comment by AlexanderMars** [comment]
Here are we go https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/5994987

**Comment by FaithOmbongi** [comment]
> Hi @FaithOmbongi, here are we go https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/5994987

Hi @AlexanderMars - I see the engineer was introducing those properties as hidden (`IsHidden="true"`). That explains why the properties aren't in the public schema. Could you follow up on their unhiding? Thanks.

**Comment by AlexanderMars** [comment]
Hi @FaithOmbongi, here is the PR to unhide the properties https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/6327279

**Review by FaithOmbongi — APPROVED** [review]

**Comment by AlexanderMars** [comment]
Hi @FaithOmbongi, here is the requested PR https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/6327279

**Pull request merged**
