### PR TITLE
Fix wrong URLs

### PR DESCRIPTION
**Pull request by pierreneter**
Fix wrong URLs at https://developer.microsoft.com/en-us/graph/docs

### CODE REVIEW

**Comment by Lauragra** [comment]
Hi, thanks for your contribution. The relative links appear to be working correctly on the site, so I'm not sure that we need this fix. Did you experience an issue with the links? Thanks!

**Comment by pierreneter** [comment]
I mentioned the URL: https://developer.microsoft.com/en-us/graph/docs
No the URL: https://developer.microsoft.com/en-us/graph/docs/concepts/overview
Please check again for sure. Thanks.

**Comment by pierreneter** [comment]
I mentioned the URL: https://developer.microsoft.com/en-us/graph/docs
Not the URL: https://developer.microsoft.com/en-us/graph/docs/concepts/overview
Please check again for sure. Thanks.

**Comment by pierreneter** [comment]
URLs in **Next steps** section.
capture-ms
Or we can redirect https://developer.microsoft.com/en-us/graph/docs to https://developer.microsoft.com/en-us/graph/docs/concepts/overview
But I do not know if this site supports redirecting or not?

**Comment by Lauragra** [comment]
Got it. Let me see what we can do there. Thanks!

**Comment by pierreneter** [comment]
I think I just need edit that URLs to direct URLs same with what you did here (in section Next steps) https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/featured_scenarios.md so I created this PR. Sorry for not creating a issue first,

**Comment by Lauragra** [comment]
Thanks for bringing this to our attention! I have filed a bug internally; we will look into whether we redirect or change to hard-coded URLs. I'll update this PR when we have a resolution.

**Comment by Lauragra** [comment]
Hi, the fix for this is live on the site now. Thanks again!

**Pull request closed without merging**
