### PR TITLE
Permission updates to servicePrincipalRiskDetections

### PR DESCRIPTION
**Pull request by ebasseri**
Correcting a documentation error on my part.

### CODE REVIEW

**Review by FaithOmbongi — APPROVED** [review]

**Comment by FaithOmbongi** [comment]
An off question - which APIs require the IdentityRiskEvent.ReadWrite.All permission? I don't see the permission referencedby any API we've documented.

**Comment by ebasseri** [comment]
@Sarah ***@***.***> is this something related to marking sign-ins as safe?

**Comment by ebasseri** [comment]
Correct, IIRC we're reusing that permission for confirm safe/compromised

From: Etan Basseri ***@***.***>
Sent: Tuesday, February 22, 2022 12:29 PM
To: microsoftgraph/microsoft-graph-docs ***@***.***>; microsoftgraph/microsoft-graph-docs ***@***.***>; Sarah Handler ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [microsoftgraph/microsoft-graph-docs] Permission updates to servicePrincipalRiskDetections (PR #15941)

@Sarah ***@***.***> is this something related to marking sign-ins as safe?

**Comment by FaithOmbongi** [comment]
Hi @ebasseri, bumping this is in your inbox. Shouldn't this fix be merged? If there's no reason it should be held back, please replace the **do not merge** with the **ready to merge** label.

**Pull request merged**
