### PR TITLE
Adding auth methods API tutorial

### PR DESCRIPTION
**Pull request by mmcla**
Adding a step-by-step tutorial for authentication methods API in the concepts section. Tagging @CelesteDG per our earlier conversation

### CODE REVIEW

**Comment by CelesteDG** [comment]
Thank you @Lauragra - I've got the branch checked out and will be making some updates. Thank you.

**Comment by CelesteDG** [comment]
Hello @mmcla - I pushed out some editorial changes to the doc. Please review: https://review.docs.microsoft.com/en-us/graph/authenticationmethods-get-started?branch=pr-en-us-8197 - Thank you.

**Comment by mmcla** [comment]
> Hello @mmcla - I pushed out some editorial changes to the doc. Please review: https://review.docs.microsoft.com/en-us/graph/authenticationmethods-get-started?branch=pr-en-us-8197 - Thank you.

@CelesteDG - looks great! The one thing I didn't know how to render correctly is in Step 5, where we need to display the Location header, which is a header rather than the body of the response. Is there a standard way of doing that, or is it ok as is?

**Comment by CelesteDG** [comment]
HI @mmcla - In case you didn't see my email reply, pasting here: Apologies for the delayed response (been in meetings). For the location header, this is just something for them to “see” and not something they need to copy/enter into Graph Explorer/or other tool, correct? If so, we could just make it into a plain code block (remove text so it doesn’t render that copy button). Other option is just show a screenshot of what they can see but I think just a plain code block is fine.

**Comment by CelesteDG** [comment]
@Lauragra - Hi Laura. I set this to "ready to merge". Wanted to let you know in case you want to be the one to merge to master if there are other PRs waiting in the docket. Thank you.

**Comment by CelesteDG** [comment]
Thank you very much, @Lauragra Have a wonderful weekend.

**Pull request merged**
