### PR TITLE
Updating uset_get.md to include /users/ query

### PR DESCRIPTION
**Pull request by shawntabrizi**
This file is supposed to show examples of "getting a user" and using the "/users/" endpoint. However, the only examples shown on this page use the /me endpoint...

I have modified the page to include a query example of the /users/ endpoint as well as the /me endpoint, and updated the $select example to also use the /users/ endpoint.

### CODE REVIEW

**Comment by shawntabrizi** [comment]
Are there any other steps here to get these changes reflected?

**Comment by PatAltimore** [comment]
Hi @shawntabrizi.  Thanks for the contribution.  The change is failing AppVeyor validation.  It's getting confused because of {id | userPrincipalName} .  I'd recommend changing your example request 

**from**

##### Request

```http
GET https://graph.microsoft.com/v1.0/users/{id | userPrincipalName}?$select=displayName,givenName,postalCode
```
**to**

##### Request

```http
GET https://graph.microsoft.com/v1.0/users/{id | userPrincipalName}?$select=displayName,givenName,postalCode
```

That should skip the validation and then I can merge it.

Thanks,
Pat

**Comment by PatAltimore** [comment]
Hi @shawntabrizi. Sorry, the AppVeyor comments didn't display.

From:

```##### Request
<!-- {
  "blockType": "request",
  "name": "get_user"
}-->
'''http
GET https://graph.microsoft.com/v1.0/users/{id | userPrincipalName}?$select=displayName,givenName,postalCode
```
**to**

##### Request

'''http
GET https://graph.microsoft.com/v1.0/users/{id | userPrincipalName}?$select=displayName,givenName,postalCode
```
Note: I had to change the back ticks to apostrophes in front of http for this to (hopefully) display correctly.

Pat

**Comment by PatAltimore** [comment]
Hi @shawntabrizi. AppVeyor can be a challenge.  I made the modifications directly to your PR and merged it.  Thanks again for your contribution.

Pat

**Pull request merged**
