### PR TITLE
Make the POST example valid

### PR DESCRIPTION
**Pull request by jsweiler**
If you post the current example you get an error. I've found that the change suggested here https://stackoverflow.com/a/48609918/2171587 works fine.

### CODE REVIEW

**Comment by dkershaw10** [comment]
@sureshja Please take a look at this request. Typically the POST topics have a "required properties" section - this topic is missing this section.  While Jeff's suggestion is good, `passwordCredential` is not  a required property.  So it might be better, if we want to show this, to have an intro line something like - "Here is an example of creating a web app registration, with a secret." and put in all the fields for that type of app.
@jsweiler NOTE: the property descriptions in the docs are **now** correct (see https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/passwordcredential)

**Comment by dkershaw10** [comment]
@sureshja Please take a look at this PR.

**Comment by Lauragra** [comment]
@sureshja , did you have a chance to take a look at this PR? Do we want to merge it or do we need changes?

**Comment by Lauragra** [comment]
@davidmu1 , can you please help drive resolution on this PR? Thanks.

**Comment by davidmu1** [comment]
Suresh is updating application articles. Closing this PR.

**Pull request closed without merging**
