### PR TITLE
Adding GDPR note to the Access Reviews intro page

### PR DESCRIPTION
**Pull request by leherpel**
As part of our yearly Privacy Review we need to document how customers could export as well as delete their GDPR data. After discussing with Dean on the Privacy Team he suggested to follow the [official guidance and wording from CELA](https://review.docs.microsoft.com/en-us/help/contribute/contribute-add-gdpr-references?branch=main) by adding a note to our API.

### CODE REVIEW

**Review by FaithOmbongi — APPROVED** [review]
Thank you @leherpel for raising this PR. Please also include the notice in this overview article https://docs.microsoft.com/en-us/graph/accessreviews-overview.

PS. Can't figure out why the include statement is flagged as a broken link 🤔

**Review by FaithOmbongi — APPROVED** [review]

**Review by isabelleatmsft — APPROVED** [review]

**Comment by Lauragra** [comment]
@FaithOmbongi , are we sure that this note belongs in all these topics? The note text talks about deleting data, and we're adding it to resource topics and other CRUD operations that aren't Delete. Also, do we want to think about the placement of the Note at all? For example, there are a lot of alerts in this topic: https://review.docs.microsoft.com/en-us/graph/api/accessreview-list?view=graph-rest-beta&branch=pr-en-us-16176&tabs=http. 

In the context of resource topics, is the note accurate? Or is the intended meeting more like "The methods listed in this section provide steps... "? And is it okay to include the note when there are no Delete operations on the resource?

**Review by FaithOmbongi — APPROVED** [review]
Hi @leherpel, pushed a commit to remove the GET and resource topics too.

**Comment by FaithOmbongi** [comment]
> @FaithOmbongi , are we sure that this note belongs in all these topics? The note text talks about deleting data, and we're adding it to resource topics and other CRUD operations that aren't Delete. Also, do we want to think about the placement of the Note at all? For example, there are a lot of alerts in this topic: https://review.docs.microsoft.com/en-us/graph/api/accessreview-list?view=graph-rest-beta&branch=pr-en-us-16176&tabs=http.
> 
> In the context of resource topics, is the note accurate? Or is the intended meeting more like "The methods listed in this section provide steps... "? And is it okay to include the note when there are no Delete operations on the resource?

Hi @Lauragra, my bad. I misled Levi on this one. I was looking at List/Get operations as export which is meant to be covered by the include statement - but the include statement is also missing a mention of the "export" feature so we've left the related methods out of this PR until we can get some confirmation.

**Pull request merged**
