### PR TITLE
[donotmerge-yet] Defer commit storage plans

### PR DESCRIPTION
**Pull request by kevklam**
Docs for additional properties in the process of being published

### CODE REVIEW

**Comment by Lauragra** [comment]
@kevklam , do you have a timeline for merging in this change? This PR now has conflicts; I recommend you close this one and reopen a new one when you're ready.

**Comment by kevklam** [comment]
Whoops - @Lauragra this change shipped a long time ago, must have forgotten about this PR. I'll open a new PR, but should the changelog show March 2019 or reflect the original date we pushed the schema?

**Comment by Lauragra** [comment]
@kevklam , it should reflect the date that we updated the schema. Thanks!

**Comment by Lauragra** [comment]
@kevklam , did you open a new PR for this? Closing this one.

**Pull request closed without merging**
