### PR TITLE
Reject and Delete APIs update

### PR DESCRIPTION
**Pull request by Hunterjet**
Update call-delete and call-reject docs

### CODE REVIEW

**Comment by Lauragra** [comment]
@Hunterjet , please see our workflow topic and set the label on your PR as appropriate: https://msgo.azurewebsites.net/add/document/guidelines/content-workflow.html#new-and-updated-content-workflow-for-internal-contributors .

**Comment by Lauragra** [comment]
@VinodRavichandran , please review and sign off on this PR.

**Comment by VinodRavichandran** [comment]
@Lauragra Will get back.

**Comment by Hunterjet** [comment]
Sorry for closing this suddenly, I will submit the changes in this PR together in an aggregate PR with the rest of the team shortly.

**Pull request closed without merging**
