### PR TITLE
Add three enums to CloudPcOnPremisesConnectionHealthCheckErrorType

### PR DESCRIPTION
**Pull request by zhishending**

### CODE REVIEW

**Comment by zhishending** [comment]
api.md: https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/8166

CSDL: https://dev.azure.com/msazure/One/_git/AD-AggregatorService-Workloads/pullrequest/4598189?path=%2FWorkloads%2FMicrosoft.CloudManagedDesktop%2Foverride%2Fschema-Prod-beta.csdl

Purpose of PR: Add three subscription related error types to cloudPcOnPremisesConnectionHealthCheckErrorType.

**Review by isvargasmsft — CHANGES_REQUESTED** [review]
Thank you very much for your work in this PR.

Everything looks good. I just have one question:
If this is an enumeration type, why isn't it listed in the enums.md file?

Could you please clarify and/or add the entry in the enums.md file? Guidance here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103158/Enumerations 

Thank you,

Isaac Vargas

**Comment by zhishending** [comment]
Some enums are taken out of the enum.md and put to on-premises connection resource page, because these enums are error types and we would like customers to be able to find descriptions of error types easily. The enums added in this PR are error types and they are not in enum.md due to the reason above.

**Review by isvargasmsft — APPROVED** [review]
Thank you for [the clarification](https://github.com/microsoftgraph/microsoft-graph-docs/pull/12960#issuecomment-876872013). 

This PR looks good to me.

**Review by Lauragra — APPROVED** [review]

**Pull request merged**
