### PR TITLE
Add windows application properties

### PR DESCRIPTION
**Pull request by aricrowe57**
Schema update PR: 5642960

### CODE REVIEW

**Comment by aricrowe57** [comment]
https://dev.azure.com/msazure/One/_git/AD-AggregatorService-Workloads/pullrequest/5642960 for AGS PR link

**Review by FaithOmbongi — CHANGES_REQUESTED** [review]
Thank you @aricrowe57 for your work on this PR. Left suggestions for minor changes.
Also, please move your changelog record to top of the file, starting at line 3.

**Comment by aricrowe57** [comment]
#feedback-addressed

**Comment by aricrowe57** [comment]
Thanks so much @FaithOmbongi for your review.  I've addressed all the suggestions on the PR and moved the changelog record to the top of the file.

**Review by FaithOmbongi — APPROVED** [review]
Thank you @aricrowe57 for your quick work through this PR. When these new API elements are live, replace the **do not merge** with the **ready to merge** label.

**Comment by FaithOmbongi** [comment]
Heads up @aricrowe57, the schema for these doc changes is live. I've added this PR to today's merge queue. If there's any reason we should keep holding it back, please replace the **ready to merge** label with the **do not merge**.

**Pull request merged**
