### PR TITLE
Fix doc: /messages is actually including the deleted items

### PR DESCRIPTION
**Pull request by jdevost**
See ../api/user_list_messages.md, it says "including" in there.

### CODE REVIEW

**Comment by angelgolfer-ms** [comment]
@jdevost , thanks for the pull request! Nice catch! Would you mind updating your branch before we merge your pull request?
BTW, if you feel like applying the same change to the beta version of the message resource topic (https://graph.microsoft.io/en-us/docs/api-reference/beta/resources/message), please go ahead, otherwise one of us will follow up on that. Thank you!

**Comment by angelgolfer-ms** [comment]
@jdevost, thank you again for your contribution. Since you haven't been able to update your branch, to avoid possible merge conflicts, I manually applied the fix to v1 and beta in a fresh branch and pushed the fix live.

**Comment by angelgolfer-ms** [comment]
@jdevost, thank you and we look forward to your continued support. I am closing this pull request now.

**Comment by jdevost** [comment]
Thanks!

Really sorry I didn't update my branch. I didn't your previous message
(from Jan 24) until now. Don't know why I missed it.

Thanks again.

**Comment by angelgolfer-ms** [comment]
No problem, @jdevost!

**Pull request closed without merging**
