### PR TITLE
GitHub issues Nov 2021

### PR DESCRIPTION
**Pull request by isvargasmsft**
Resolving some GitHub issues.

### CODE REVIEW

**Comment by isvargasmsft** [comment]
Resolving https://github.com/microsoftgraph/microsoft-graph-docs/issues/14453

**Comment by isvargasmsft** [comment]
Resolving https://github.com/microsoftgraph/microsoft-graph-docs/issues/14471

**Comment by isvargasmsft** [comment]
Resolving https://github.com/microsoftgraph/microsoft-graph-docs/issues/6805

I'd deeply appreciate a review in this commit.

**Comment by isvargasmsft** [comment]
Fixing https://github.com/microsoftgraph/microsoft-graph-docs/issues/5076

Updating status code.

**Comment by isvargasmsft** [comment]
Fixing https://github.com/microsoftgraph/microsoft-graph-docs/issues/4784

Fixing the actual range from 30 to 28 days.

**Comment by isvargasmsft** [comment]
Fixing https://github.com/microsoftgraph/microsoft-graph-docs/issues/4579

Adding a clearer description as requested by Harini.

**Comment by isvargasmsft** [comment]
Fixing https://github.com/microsoftgraph/microsoft-graph-docs/issues/4547

Removing icaluid property from example as requested by Harini.

**Comment by isvargasmsft** [comment]
Fixing https://github.com/microsoftgraph/microsoft-graph-docs/issues/4063

Capitalization.

**Comment by isvargasmsft** [comment]
Fixing https://github.com/microsoftgraph/microsoft-graph-docs/issues/2886 

Adding clarification and link as per Abheek's request.

**Comment by isvargasmsft** [comment]
Fixing https://github.com/microsoftgraph/microsoft-graph-docs/issues/14861

Updating links

**Comment by isvargasmsft** [comment]
Fixing https://github.com/microsoftgraph/microsoft-graph-docs/issues/14975

Fixing example.

**Review by Lauragra — APPROVED** [review]

**Pull request merged**
