### PR TITLE
Windows application patch

### PR DESCRIPTION
**Pull request by aricrowe57**
Few minor updates to 'windowsApplication' docs

### CODE REVIEW

**Comment by aricrowe57** [comment]
#sign-off

**Comment by aricrowe57** [comment]
Hi @FaithOmbongi, this is a minor change.  Is there anything else I need to do to get it merged?  Thanks!

**Comment by aricrowe57** [comment]
#sign-off

**Review by FaithOmbongi — APPROVED** [review]
Thank you @aricrowe57 for handling this fix. Approved and will be merged at EOD.

**Pull request merged**
