### PR TITLE
Update call.md

### PR DESCRIPTION
**Pull request by hrazi**
Added Transcription Info. Can you please check if this is correct.

### CODE REVIEW

**Comment by Lauragra** [comment]
@hrazi , based on this error, it looks like you need to update the response example:  
Error: /api/application-post-calls.md:
      Missing properties: response was missing these required properties: transcriptionInfo

  Error: /api/application-post-calls.md:
      Missing properties: response was missing these required properties: transcriptionInfo

**Comment by hrazi** [comment]
@Lauragra fixed errors. please let me know if I need to make any other changes.

**Comment by Lauragra** [comment]
> @Lauragra fixed errors. please let me know if I need to make any other changes.

We're still getting the same API Doctor error. Please make sure that you've updated all the relevant response examples that should return that property.

**Comment by lramosvea** [comment]
In the live metadata, I see the property is called transcription, not transcriptionInfo.

**Pull request closed without merging**
