### PR TITLE
Add v1.0 docs for allowUserConsentForRiskyApps

### PR DESCRIPTION
**Pull request by psignoret**

### CODE REVIEW

**Comment by psignoret** [comment]
@FaithOmbongi Can you please help me get past the changelog link validation errors? I believe the issue is a bad redirect configured in /redirects/.openpublishing.redirection.0822.json (there's an extra ".md" in there).

**Comment by FaithOmbongi** [comment]
Hi @psignoret - I've raised this PR #20452. Once it's merged, update your branch and the changelog validation error will have resolved itself.

**Comment by Jarbas-MSFT** [comment]
Hi @psignoret, can you please share with me via Teams a pointer to the api.md and CSDL files related to your PR?

**Comment by JarbasHorst** [comment]
Hi @Lauragra, this PR is ready for final review.

**Review by Lauragra — APPROVED** [review]

**Pull request merged**
