### PR TITLE
Beta - New risk detail m365DAdminDismissedDetection

### PR DESCRIPTION
**Pull request by tracyshi**
Added new sign-in risk detail m365DAdminDismissedDetection.

### CODE REVIEW

**Comment by besiler** [comment]
@tracyshi could you please share the dev (not docs) PR for this change with the CSDL and schema changes? I would assume that this new enum will have to go behind the unknownfuturevalue parameter and will need the standard explanation about using unknownfuturevalue

**Comment by besiler** [comment]
Also @tracyshi I'm not sure if the docs team will pick this up automatically if I'm marked as a reviewer - may be a good idea to request @FaithOmbongi as well

**Comment by tracyshi** [comment]
> @tracyshi could you please share the dev (not docs) PR for this change with the CSDL and schema changes? I would assume that this new enum will have to go behind the unknownfuturevalue parameter and will need the standard explanation about using unknownfuturevalue

@liz-peng could you please share the dev PR here? Thanks!

**Comment by liz-peng** [comment]
@besiler @tracyshi the PR link for beta schema change: https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/6649385

**Comment by Jarbas-MSFT** [comment]
This PR is no longer needed because PR 18684 will introduce this change now.

**Pull request closed without merging**
