### PR TITLE
Content for Rostering V1.0

### PR DESCRIPTION
**Pull request by abhijitsverma**
Content for Rostering V1.0

### CODE REVIEW

**Comment by Lauragra** [comment]
@KundanaP , should we remove the links to administrativeunit and educationorganization in the educationschool topic, or do we need to include those topics? Thanks.

**Comment by KundanaP** [comment]
We should keep administrativeunit and educationorganization.

**Comment by Lauragra** [comment]
So, we need to add them to v1.0? They aren't included in this PR.

**Comment by KundanaP** [comment]
I don't see why they should be removed? Is it because is AU has not GA'ed. @garethj-msft  - can you please comment?

**Comment by JohnAustin-MSFT** [comment]
Closing PR.  The content of the PR was forked to a johnaustin-msft repo, corrected, and merged to master via a new PR

**Pull request closed without merging**
