### PR TITLE
Fix sample URLs to match schema

### PR DESCRIPTION
**Pull request by kanchm**
Changes were made to:

openShiftsChangeRequests -> openShiftChangeRequests
fido2AuthenticationMethod -> fido2Methods
/me/profile/responsibilities -> /me/responsibilities
/printerShare/ -> /printerShares/
/profile/accounts -> /profile/account
/user/profile -> /me/profile

### CODE REVIEW

**Comment by kanchm** [comment]
@Lauragra @angelgolfer-ms please review as I have a couple more to queue after this.

**Comment by Lauragra** [comment]
@kanchm , should we remove the SDK snippets from these files until they can get regenerated with the new request syntax?

**Comment by kanchm** [comment]
@Lauragra I undid the changes in snippets areas.

**Comment by Lauragra** [comment]
> @Lauragra I undid the changes in snippets areas.

The examples should match the syntax shown in the HTTP request section. so we should have those updates. When you update the request example, we should remove the SDK snippet links from the topic because they'll be inaccurate. They'll get added back in via the automation.

**Pull request merged**
