### PR TITLE
Added Send Outlook message from another user topic

### PR DESCRIPTION
**Pull request by jasonjoh**

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[8e52e42](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3803/commits/8e52e42fc37acce6f4ee85740f24b5b80f6e615e)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[8e52e42](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3803/commits/8e52e42fc37acce6f4ee85740f24b5b80f6e615e)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[8e52e42](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3803/commits/8e52e42fc37acce6f4ee85740f24b5b80f6e615e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/images/outlook-sent-on-behalf.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-mail-sendas/concepts/images/outlook-sent-on-behalf.png) | :white_check_mark:Succeeded | |
[concepts/outlook-send-mail-from-other-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-mail-sendas/concepts/outlook-send-mail-from-other-user.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901161934317876-3803%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=hBVG54p4AzQ88whLlnpeglxJfDYlj%2BXNkG%2FKcHfUj2w%3D&st=2019-01-16T19%3A32%3A38Z&se=2019-02-16T19%3A37%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[98d2654](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3803/commits/98d2654f9a351b0cf6c0afe6b7c324fd02feda41)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[98d2654](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3803/commits/98d2654f9a351b0cf6c0afe6b7c324fd02feda41)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[98d2654](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3803/commits/98d2654f9a351b0cf6c0afe6b7c324fd02feda41)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/images/outlook-sent-on-behalf.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-mail-sendas/concepts/images/outlook-sent-on-behalf.png) | :white_check_mark:Succeeded | |
[concepts/outlook-send-mail-from-other-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-mail-sendas/concepts/outlook-send-mail-from-other-user.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901161948324359-3803%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=zqYyxyzlbZ57yV0sGlDO57udtXq%2BnnjGkmB514nIfFs%3D&st=2019-01-16T19%3A46%3A48Z&se=2019-02-16T19%3A51%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[ead1567](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3803/commits/ead15673d7d5ddaba98cee669cf41c36b2be26e4)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[ead1567](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3803/commits/ead15673d7d5ddaba98cee669cf41c36b2be26e4)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[ead1567](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3803/commits/ead15673d7d5ddaba98cee669cf41c36b2be26e4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/images/outlook-sent-on-behalf.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-mail-sendas/concepts/images/outlook-sent-on-behalf.png) | :white_check_mark:Succeeded | |
[concepts/outlook-send-mail-from-other-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-mail-sendas/concepts/outlook-send-mail-from-other-user.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901161957465272-3803%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=sdVT%2FtG3LFvlrgP250bsD764zpWUPHCNMyStMqKNM9Y%3D&st=2019-01-16T19%3A55%3A53Z&se=2019-02-16T20%3A00%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[32272b0](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3803/commits/32272b0923c3ddebf510279cef6576ace749d09c)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[8bf14ce](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3803/commits/8bf14ce9d6cc681b480dec54294db4edc4bb363d)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

**Comment by jasonjoh** [comment]
@Lauragra requesting your review since I'm adding a topic to the TOC :)

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[8bf14ce](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3803/commits/8bf14ce9d6cc681b480dec54294db4edc4bb363d)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[8bf14ce](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3803/commits/8bf14ce9d6cc681b480dec54294db4edc4bb363d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/images/outlook-sent-on-behalf.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-mail-sendas/concepts/images/outlook-sent-on-behalf.png) | :white_check_mark:Succeeded | |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-mail-sendas/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | |
[concepts/outlook-send-mail-from-other-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-mail-sendas/concepts/outlook-send-mail-from-other-user.md) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-mail-sendas/concepts/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901162014335989-3803%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=JcvwGzne5b4odDVEZoThQpT4GiMGGwO4OfItVKShNw4%3D&st=2019-01-16T20%3A13%3A01Z&se=2019-02-16T20%3A18%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[ee9a6e6](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3803/commits/ee9a6e6e68cbf11f881ac52aa42bb71bcded3046)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/images/outlook-sent-on-behalf.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-mail-sendas/concepts/images/outlook-sent-on-behalf.png) | :white_check_mark:Succeeded | |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-mail-sendas/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | |
[concepts/outlook-send-mail-from-other-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-mail-sendas/concepts/outlook-send-mail-from-other-user.md) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-mail-sendas/concepts/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901170027207496-3803%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Mpfl4mcJjue90qcS51k9GvGTIWQQeRLU2VjeuNshbxY%3D&st=2019-01-17T00%3A25%3A32Z&se=2019-02-17T00%3A30%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[139e71f](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3803/commits/139e71f669beeb2c2580851dcac1987204a9be1d)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[139e71f](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3803/commits/139e71f669beeb2c2580851dcac1987204a9be1d)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[139e71f](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3803/commits/139e71f669beeb2c2580851dcac1987204a9be1d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/images/outlook-sent-on-behalf.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-mail-sendas/concepts/images/outlook-sent-on-behalf.png) | :white_check_mark:Succeeded | |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-mail-sendas/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | |
[concepts/outlook-send-mail-from-other-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-mail-sendas/concepts/outlook-send-mail-from-other-user.md) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-mail-sendas/concepts/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901170028166994-3803%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=yjJQqXI4YEUW0BrM0tp9gLLfXKdZ283WdczYa4LCvFw%3D&st=2019-01-17T00%3A28%3A50Z&se=2019-02-17T00%3A33%3A50Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
