### PR TITLE
Update per PR #2755.

### PR DESCRIPTION
**Pull request by Lauragra**

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[872a1b9](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3890/commits/872a1b97c30249aa554a84b5be552115ebd086b0)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 23 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[872a1b9](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3890/commits/872a1b97c30249aa554a84b5be552115ebd086b0)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 23 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[872a1b9](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3890/commits/872a1b97c30249aa554a84b5be552115ebd086b0)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 56 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[872a1b9](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3890/commits/872a1b97c30249aa554a84b5be552115ebd086b0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lauragra-pr2755/concepts/changelog.md) | :warning:Warning | | [Details](#user-content-concepts%2Fchangelog.md)
[concepts/auth-v2-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lauragra-pr2755/concepts/auth-v2-user.md) | :white_check_mark:Succeeded | |

<a name="concepts%2Fchangelog.md"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lauragra-pr2755/concepts/changelog.md)
 - **Line 33**: **[Warning]** Invalid file link:(~/../api-reference/v1.0/resources/user.md).
 - **Line 35**: **[Warning]** Invalid file link:(~/../api-reference/v1.0/resources/group.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901300101361972-3890%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=g7XbVXEOL08%2FGBeKslqtPaBws4BPwWy5zQ28rTQRkks%3D&st=2019-01-30T01%3A01%3A16Z&se=2019-03-02T01%3A06%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
@CelesteDG , can you assign someone to review and update this PR per Jackson's feedback please? Thanks.

**Comment by Lauragra** [comment]
@Jackson-Woods , do you want to merge in this change, or should I close this PR? Thanks.

**Pull request closed without merging**
