### PR TITLE
Issue #3727

### PR DESCRIPTION
**Pull request by seydel1847**
This commit fixes Issue #3727

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[827ea42](https://github.com/seydel1847/microsoft-graph-docs/pull/3728/commits/827ea42554a8d86b69819f249fffd3a65bd4481e)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 20 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[827ea42](https://github.com/seydel1847/microsoft-graph-docs/pull/3728/commits/827ea42554a8d86b69819f249fffd3a65bd4481e)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[827ea42](https://github.com/seydel1847/microsoft-graph-docs/pull/3728/commits/827ea42554a8d86b69819f249fffd3a65bd4481e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/listitem.md](https://github.com/seydel1847/microsoft-graph-docs/blob/Issue_#3727%5Capi-reference/beta/resources/listitem.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fresources%2Flistitem.md)
[api-reference/beta/resources/sitepage.md](https://github.com/seydel1847/microsoft-graph-docs/blob/Issue_#3727%5Capi-reference/beta/resources/sitepage.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fresources%2Fsitepage.md)
[api-reference/beta/resources/contentTypeInfo.md](https://github.com/seydel1847/microsoft-graph-docs/blob/Issue_#3727%5Capi-reference/beta/resources/contentTypeInfo.md) | :white_check_mark:Succeeded | |

<a name="api-reference%2Fbeta%2Fresources%2Flistitem.md"></a>
### [api-reference/beta/resources/listitem.md](https://github.com/seydel1847/microsoft-graph-docs/blob/Issue_#3727%5Capi-reference/beta/resources/listitem.md)
 - **Line 80**: **[Warning]** Invalid file link:(~/beta/resources/contenttypeinfo.md).

<a name="api-reference%2Fbeta%2Fresources%2Fsitepage.md"></a>
### [api-reference/beta/resources/sitepage.md](https://github.com/seydel1847/microsoft-graph-docs/blob/Issue_#3727%5Capi-reference/beta/resources/sitepage.md)
 - **Line 74**: **[Warning]** Invalid file link:(~/beta/resources/contenttypeinfo.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901052145501675-3728%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=YP5Lz7bYaqpFy9yat5iswwSSrUkakYEs3IKZkGGewzg%3D&st=2019-01-05T21%3A43%3A46Z&se=2019-02-05T21%3A48%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[87a33f0](https://github.com/seydel1847/microsoft-graph-docs/pull/3728/commits/87a33f0c704f8392c1ee8882e781b75e4885d88a)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 20 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[87a33f0](https://github.com/seydel1847/microsoft-graph-docs/pull/3728/commits/87a33f0c704f8392c1ee8882e781b75e4885d88a)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[87a33f0](https://github.com/seydel1847/microsoft-graph-docs/pull/3728/commits/87a33f0c704f8392c1ee8882e781b75e4885d88a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/sitepage.md](https://github.com/seydel1847/microsoft-graph-docs/blob/Issue_#3727%5Capi-reference/beta/resources/sitepage.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fresources%2Fsitepage.md)
[api-reference/beta/resources/listitem.md](https://github.com/seydel1847/microsoft-graph-docs/blob/Issue_#3727%5Capi-reference/beta/resources/listitem.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fresources%2Flistitem.md)
[api-reference/beta/resources/contentTypeInfo.md](https://github.com/seydel1847/microsoft-graph-docs/blob/Issue_#3727%5Capi-reference/beta/resources/contentTypeInfo.md) | :white_check_mark:Succeeded | |

<a name="api-reference%2Fbeta%2Fresources%2Fsitepage.md"></a>
### [api-reference/beta/resources/sitepage.md](https://github.com/seydel1847/microsoft-graph-docs/blob/Issue_#3727%5Capi-reference/beta/resources/sitepage.md)
 - **Line 74**: **[Warning]** Invalid file link:(~/beta/resources/contenttypeinfo.md).

<a name="api-reference%2Fbeta%2Fresources%2Flistitem.md"></a>
### [api-reference/beta/resources/listitem.md](https://github.com/seydel1847/microsoft-graph-docs/blob/Issue_#3727%5Capi-reference/beta/resources/listitem.md)
 - **Line 80**: **[Warning]** Invalid file link:(~/beta/resources/contenttypeinfo.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901071658590668-3728%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=6ClzMK1F85QQpwJuxswcgAcIItJh4TVhNqug3betSTg%3D&st=2019-01-07T16%3A57%3A29Z&se=2019-02-07T17%3A02%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
Thanks for fixing that!

**Pull request merged**
