### PR TITLE
Updated API Pages in beta

### PR DESCRIPTION
**Pull request by Y-Meenakshi**
Added the namespace:

### CODE REVIEW

**Comment by Lauragra** [comment]
@Y-Meenakshi , please include the changelog, TOC, and parent resource updates. What is the merge status of this PR?

**Comment by nkramer** [comment]
@Lauragra , we already had change log entries for these APIs, we will update them to link to these new pages.

**Comment by Y-Meenakshi** [comment]
Hi @Lauragra , I have already updated the TOC for these pages . Il will link in the change log file.

**Comment by Y-Meenakshi** [comment]
Moved changes to another PR

**Comment by Y-Meenakshi** [comment]
Moved changes to another PR

**Pull request closed without merging**
