### PR TITLE
[ready to merge] Update user resource to remove companyName read-only

### PR DESCRIPTION
**Pull request by eketo-msft**
CompanyName is now writeable on user

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[e9efeb6](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3929/commits/e9efeb6a570f0ff349f8c879bd11fcac95f7e76e)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 23 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[e9efeb6](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3929/commits/e9efeb6a570f0ff349f8c879bd11fcac95f7e76e)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 58 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[e9efeb6](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3929/commits/e9efeb6a570f0ff349f8c879bd11fcac95f7e76e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/eketo-companyName-update/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902052116065818-3929%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2FKf5HycFIH%2BNqRDLR5WRMpnfSafrHQqzT0FrfLReoZU%3D&st=2019-02-05T21%3A14%3A20Z&se=2019-03-08T21%3A19%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[1de828d](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3929/commits/1de828d9c4b398c20243be64a721a0351ec0a8e4)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 23 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[1de828d](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3929/commits/1de828d9c4b398c20243be64a721a0351ec0a8e4)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 58 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[1de828d](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3929/commits/1de828d9c4b398c20243be64a721a0351ec0a8e4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/eketo-companyName-update/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/eketo-companyName-update/api-reference/v1.0/resources/user.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902052119440782-3929%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=dBGtRMtZfP8irMWLQ7CyBMz%2FoislhFpECvJJWsOBwHc%3D&st=2019-02-05T21%3A18%3A11Z&se=2019-03-08T21%3A23%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[9abb7cd](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3929/commits/9abb7cdaaded87294477609146735554f7a5722c)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 23 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[9abb7cd](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3929/commits/9abb7cdaaded87294477609146735554f7a5722c)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 58 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[9abb7cd](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3929/commits/9abb7cdaaded87294477609146735554f7a5722c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/eketo-companyName-update/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/eketo-companyName-update/api-reference/v1.0/resources/user.md) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/eketo-companyName-update/concepts/changelog.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902052132210222-3929%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=HiAXPpvf1f7Qfoc1ZTg6u9vsONOki%2BWPGiILRt0d4eQ%3D&st=2019-02-05T21%3A30%3A59Z&se=2019-03-08T21%3A35%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[ba9f8ce](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3929/commits/ba9f8ce39c747c2aeb2590c6109d722fbfa00ef0)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 23 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[ba9f8ce](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3929/commits/ba9f8ce39c747c2aeb2590c6109d722fbfa00ef0)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 58 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[ba9f8ce](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3929/commits/ba9f8ce39c747c2aeb2590c6109d722fbfa00ef0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/eketo-companyName-update/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/eketo-companyName-update/api-reference/v1.0/resources/user.md) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/eketo-companyName-update/concepts/changelog.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902052233562098-3929%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=qbTYiXbakAEQljD7odzlQIeW%2FocHbvWLPbTfuodglVc%3D&st=2019-02-05T22%3A32%3A39Z&se=2019-03-08T22%3A37%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[2f736b7](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3929/commits/2f736b716705f44648fad673776e20c71768d03b)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 23 sec(s)_

**Comment by Lauragra** [comment]
@eketo-msft , are you ready to merge this PR today?

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[2f736b7](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3929/commits/2f736b716705f44648fad673776e20c71768d03b)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 58 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[2f736b7](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3929/commits/2f736b716705f44648fad673776e20c71768d03b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/eketo-companyName-update/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/eketo-companyName-update/api-reference/v1.0/resources/user.md) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/eketo-companyName-update/concepts/changelog.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902060017172857-3929%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=u%2BOtcR9%2FIXh4np%2B4DBFl%2FIhBse6tgE%2B9Sg6YRRl5RrU%3D&st=2019-02-06T00%3A15%3A59Z&se=2019-03-09T00%3A20%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[9a37ffc](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3929/commits/9a37ffcdc4d3f452f72b1be9bc8f23481e7b1434)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 23 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[9a37ffc](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3929/commits/9a37ffcdc4d3f452f72b1be9bc8f23481e7b1434)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 59 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[9a37ffc](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3929/commits/9a37ffcdc4d3f452f72b1be9bc8f23481e7b1434)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/eketo-companyName-update/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/eketo-companyName-update/api-reference/v1.0/resources/user.md) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/eketo-companyName-update/concepts/changelog.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902060017372722-3929%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=nMifRISJLSVd%2FP%2FOFveEXzOZOV0L51WrZDkd5c7Eapk%3D&st=2019-02-06T00%3A19%3A49Z&se=2019-03-09T00%3A24%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by eketo-msft** [comment]
@Lauragra, am now, updated the title.

**Pull request merged**
