### PR TITLE
fix: MD037/no-space-in-emphasis

### PR DESCRIPTION
**Pull request by nschonni**
Spaces inside emphasis markers

### CODE REVIEW

**Comment by Lauragra** [comment]
Assigning this to you, @rolyon. This is an issue in the Intune docs, which are autogenerated. Rather than fixing the bold, we should follow up on resolving the TODOs. Thanks.

**Comment by rolyon** [comment]
Sorry for the delay on this. These changes look fine.

**Comment by rolyon** [comment]
#sign-off

**Comment by rolyon** [comment]
@Lauragra 
I signed off on this request.

**Pull request merged**
