### PR TITLE
update changelog, add new riskeventtype

### PR DESCRIPTION
**Pull request by cloudhandler**

### CODE REVIEW

**Comment by cloudhandler** [comment]
@dkershaw10 / @Lauragra  can you please help this get published? We need the changelog addition that we are moving to a new riskEventType property

**Comment by Lauragra** [comment]
@cloudhandler , when you're ready for a PR to be published, please set the ready to merge label.

**Comment by Lauragra** [comment]
@cloudhandler , is there another PR that adds the riskEventType property?

**Comment by cloudhandler** [comment]
@Lauragra - the riskEventType property was already added to docs, the changelog got missed

**Pull request merged**
