### PR TITLE
IMAP, POP, SMTP permissions

### PR DESCRIPTION
**Pull request by svpsiva**

### CODE REVIEW

**Comment by Lauragra** [comment]
@svpsiva , what is the merge status of this PR?

**Comment by svpsiva** [comment]
> @svpsiva , what is the merge status of this PR?

@Lauragra Pls hold off on this merge. We need the scopes released to PROD and some initial validations done before we can release the docs.

**Comment by svpsiva** [comment]
@Lauragra You can merge this PR now. We are ready to announce the feature.

**Comment by Jackson-Woods** [comment]
@svpsiva @psignoret We'd like to add a note explaining that these permissions do not give access to MS Graph APIs and linking to a doc that does explain the intended scenario for their use. Can you add that to this PR?

**Comment by Jackson-Woods** [comment]
@svpsiva Can you add the requested note/doc link so we can merge this? The permissions have been live in the portal for a long time now without being documented.

**Comment by Jackson-Woods** [comment]
@svpsiva @psignoret merging this since it's going on a year that these haven't been documented. if you get a chance, please add the note/doc link that was requested last summer.

**Pull request merged**
