### PR TITLE
Update installation.md

### PR DESCRIPTION
**Pull request by sassdawe**
Added `-Scope CurrentUser` to the install-module example because that way it doesn't require admin rights. 

The second example with '-Scope AllUsers' might need admin rights.

### CODE REVIEW

**Comment by sassdawe** [comment]
pinging @jasonjoh as author for approval :)

**Review by jasonjoh — APPROVED** [review]

**Comment by jasonjoh** [comment]
Thanks @sassdawe for contributing! I've flagged this as ready to merge so our editor will merge it into main.

**Comment by sassdawe** [comment]
@jasonjoh Do you know why I can't see the link to this repo anymore on [this page](https://docs.microsoft.com/en-us/powershell/microsoftgraph/installation) and where did my name and avatar went from the page as a contributor?

**Comment by jasonjoh** [comment]
@sassdawe the documents were removed from the Graph documentation and added to the PowerShell documentation. The page used to be at docs.microsoft.com/graph/powershell/installation, but now lives at docs.microsoft.com/powershell/microsoftgraph/installation.

The presence of an "edit" button on a doc page to take you to the Markdown source in GitHub is an option set on each documentation "set". Evidently the PowerShell doc set does not have that option set. 

The Markdown file installation.md no longer exists in this repository. Our docs pages get contributor info from GitHub, and since this is now a new file in a new repo, contribution history is different.

**Pull request merged**
