### PR TITLE
Images only accept data-url or binary part

### PR DESCRIPTION
**Pull request by LucianD-Microsoft**
When updating an image on a OneNote page through the API you are unable to use www links since the service won't try and download random resources from www. Instead the image needs to be part of the request itself, either by an image-data-url or a part-name of a multipart request.

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[032192b](https://github.com/LucianD-Microsoft/microsoft-graph-docs/pull/4120/commits/032192bae969f8568c5103018fc145564cfdbbc3)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 26 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[032192b](https://github.com/LucianD-Microsoft/microsoft-graph-docs/pull/4120/commits/032192bae969f8568c5103018fc145564cfdbbc3)_: 

:clock10: **Incremental building**: average incremental building time is _2 min(s) 4 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[032192b](https://github.com/LucianD-Microsoft/microsoft-graph-docs/pull/4120/commits/032192bae969f8568c5103018fc145564cfdbbc3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/onenote-update-page.md](https://github.com/LucianD-Microsoft/microsoft-graph-docs/blob/master/concepts/onenote-update-page.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903080039336762-4120%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=c6kVsreT%2FMryFLLTb55DmXoodsmGa03vURgVMbyriBY%3D&st=2019-03-08T00%3A37%3A55Z&se=2019-04-08T00%3A42%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
@jewan-microsoft , can you review this change please?

**Pull request merged**
