### PR TITLE
Remove identityRiskEvents API

### PR DESCRIPTION
**Pull request by cloudhandler**
removes identityRiskEvents API topics, updates identity protection root, updates TOC

### CODE REVIEW

**Comment by cloudhandler** [comment]
#hold-off

**Comment by cloudhandler** [comment]
Hi, we're ready to merge this PR to remove the identityriskevents API from the docs. When I click on the API doctor error link I'm getting "build not found". Can someone please assist?

**Comment by jasonjoh** [comment]
@cloudhandler that failed build was from May 2020 - I'm sure AzDO doesn't keep that stuff around forever :D. Just need to kick off a new build. If you resolve the merge conflicts that should trigger new builds.

**Comment by lramosvea** [comment]
Hi @cloudhandler were you able to follow Jason's instructions to resolve conflicts? Also, it seems like you'll need to edit the changelog to indicate this change. Thanks.

**Pull request merged**
