### PR TITLE
Fix invalid invitation example

### PR DESCRIPTION
**Pull request by shawnferry**
"read | write" is not a valid role

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[8db31a8](https://github.com/shawnferry/microsoft-graph-docs/pull/4062/commits/8db31a8b2af7da141792070b6b2ee8b47a806db8)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 25 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[8db31a8](https://github.com/shawnferry/microsoft-graph-docs/pull/4062/commits/8db31a8b2af7da141792070b6b2ee8b47a806db8)_: 

:clock10: **Incremental building**: average incremental building time is _2 min(s) 3 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[8db31a8](https://github.com/shawnferry/microsoft-graph-docs/pull/4062/commits/8db31a8b2af7da141792070b6b2ee8b47a806db8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/shawnferry/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902280102422200-4062%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=zXtB4hCq%2FrlklBmn7yWlX0DFeg%2BoBR4u9Lk13Nybs0Y%3D&st=2019-02-28T01%3A01%3A19Z&se=2019-03-31T01%3A06%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
Thanks for your contribution. Closing this as the source content is correct as-is.

**Pull request closed without merging**
