### PR TITLE
Fixes per PR #2603.

### PR DESCRIPTION
**Pull request by Lauragra**

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[262f879](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3872/commits/262f879ed8b7efee7fb033e8e53a3cedb822903e)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[262f879](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3872/commits/262f879ed8b7efee7fb033e8e53a3cedb822903e)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 56 sec(s)_

**Comment by Lauragra** [comment]
@JeremyKelley , @kevklam , driveItemVersion and the associated methods are not currently exposed in the beta or v1.0 TOCs. Do we need to add them?

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[262f879](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3872/commits/262f879ed8b7efee7fb033e8e53a3cedb822903e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitemversion-get-contents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lauragra-pr2603/api-reference/beta/api/driveitemversion-get-contents.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/driveitemversion-get-contents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lauragra-pr2603/api-reference/v1.0/api/driveitemversion-get-contents.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901270142275820-3872%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=hBRPnGxYeB0DxuY29wFTV6%2B80XGLCCrUMSK%2FB%2BNwEWA%3D&st=2019-01-27T01%3A41%3A20Z&se=2019-02-27T01%3A46%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
@JeremyKelley , can you please review this PR? Otherwise, I will close if no response. Thanks.

**Comment by Lauragra** [comment]
Closing due to no response from reviewers on this PR.

**Pull request closed without merging**
