### PR TITLE
reducing the image size

### PR DESCRIPTION
**Pull request by aycabas**
Reducing the image size to 1200px, it doesn't appear on the docs.

### CODE REVIEW

**Comment by aycabas** [comment]
Hi @Lauragra, we went live with mgt tutorial yesterday but seems like image sizes were too big, so they didn't appear on docs. Just reduced the size of 2 images in this PR.

**Comment by Lauragra** [comment]
> Hi @Lauragra, we went live with mgt tutorial yesterday but seems like image sizes were too big, so they didn't appear on docs. Just reduced the size of 2 images in this PR.

Which page of the tutorial links to these images so we can preview them on the review site?

**Comment by aycabas** [comment]
> > Hi @Lauragra, we went live with mgt tutorial yesterday but seems like image sizes were too big, so they didn't appear on docs. Just reduced the size of 2 images in this PR.
> 
> Which page of the tutorial links to these images so we can preview them on the review site?

Here is the page for the tutorial: https://docs.microsoft.com/en-us/graph/toolkit/get-started/building-one-productivity-hub

**Comment by Lauragra** [comment]
@aycabas , I see. I can't seem to verify that the image is fixed on the review site. Try this link: https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/building-one-productivity-hub?tutorial-step=1&branch=pr-en-us-18362

I think the image is still not rendering.

**Comment by aycabas** [comment]
Great catch, thanks @Lauragra. I fixed it, an extra dot in the image url was causing the issue. Seems like it's working in the review page now: https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/building-one-productivity-hub?tutorial-step=1&branch=pr-en-us-18362

**Review by Lauragra — APPROVED** [review]

**Pull request merged**
