### PR TITLE
MS Graph connectors docs updates: Updating links + removing preview tags

### PR DESCRIPTION
**Pull request by mecampos**

### CODE REVIEW

**Review by Lauragra — APPROVED** [review]

**Comment by jasonjoh** [comment]
Docs Build status updates of commit _[c14f9ca](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c14f9cab71f57793cf9e16dedadc41326d3b4f3e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-93b4a41f)

<a id="93b4a41f"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109062011101172-13758%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=USuFs585s1qd50d6lzAK7lodZYoLbM0LVWv319lvIuc%3D&st=2021-09-06T20%3A06%3A54Z&se=2021-10-07T20%3A11%3A54Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by jasonjoh** [comment]
Docs Build status updates of commit _[300fe30](https://github.com/microsoftgraph/microsoft-graph-docs/commits/300fe30676c9e6a17f7bed4535d6cae60736a34e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-docsupdates/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13758) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-docsupdates/api-reference/beta/api/externalconnectors-externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-get?view=graph-rest-beta&branch=pr-en-us-13758) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-docsupdates/api-reference/beta/api/externalconnectors-externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-update?view=graph-rest-beta&branch=pr-en-us-13758) (graph-rest-beta) |
[concepts/connecting-external-content-connectors-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-docsupdates/concepts/connecting-external-content-connectors-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-connectors-overview?branch=pr-en-us-13758) |
[concepts/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-docsupdates/concepts/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/overview?branch=pr-en-us-13758) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109062026325565-13758%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=tx8V%2Fw4e12sATQ%2Fk%2Bdz6P77U95DMChCnpW5yfIu2VGI%3D&st=2021-09-06T20%3A23%3A10Z&se=2021-10-07T20%3A28%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by mecampos** [comment]
Hi @Lauragra, could you please confirm the status of this PR, the review was completed, but it wasn't merged. Thanks

**Comment by Lauragra** [comment]
@mecampos , if you're ready to publish, please change the do not merge label to ready to merge and it will be in the publishing queue. Thanks!

**Pull request merged**
