### PR TITLE
feature/auto throttling documentation

### PR DESCRIPTION
**Pull request by baywet**
- - adds a placeholder for throttling documentation generation
- - auto generated update for throttling documentation

### CODE REVIEW

**Comment by baywet** [comment]
@davidmu1 @angelgolfer-ms @Lauragra this is a prototype of automated documentation generation for throttling information. 
I'm close to the final form of the tool. Let me know what you think.

CC @jthake-msft @darrelmiller

**Comment by davidmu1** [comment]
@baywet I understand what you are doing with the automatic generation, I'm curious about how users might quickly find what they are looking for. The comma separated lists in both the headings and notes in the includes are hard to visually scan and I'm not sure search will work on them. I know bulleted lists can get long, but much easier to scan. Can the headings be more generic and the notes be more of a complete list?

**Comment by baywet** [comment]
@davidmu1 : I don't have a "display name" anywhere in the metadata that I could use as the title of each section. This is why I went with the entities approach.
FYI I'm taking the 4 entities with the most properties for the title, and putting all the other ones in the Note below the title (if any).
@dkershaw10 told me there's ongoing work to add display names in the configuration files for other generation efforts, when it is available I'll be able to switch to that information for the section title and a bulleted list below. But I suggest we proceed with what we have now, it's always better than not having the information at all. Thoughts?

**Comment by baywet** [comment]
Thank you @angelgolfer-ms !! This is exactly the kind of feedback I was looking for. I've made some tweaks to the generation process to include most of your feedback. Let me know what you think now!
The only think I haven't included at the moment is to breakdown the page into subpages and make changes in the TOCs, that's because there's two other PRs in progress for Outlook and Directory services and I don't want to run into conflicts.
Additionally, I still have to discover how throttling is done for other API sets not in Exchange/Identity/Teams and document it. I think it'll be better to review this aspect after I've been full circle.

**Comment by angelgolfer-ms** [comment]
> Thank you @angelgolfer-ms !! This is exactly the kind of feedback I was looking for. I've made some tweaks to the generation process to include most of your feedback. Let me know what you think now!
> The only think I haven't included at the moment is to breakdown the page into subpages and make changes in the TOCs, that's because there's two other PRs in progress for Outlook and Directory services and I don't want to run into conflicts.
> Additionally, I still have to discover how throttling is done for other API sets not in Exchange/Identity/Teams and document it. I think it'll be better to review this aspect after I've been full circle.

Hi @baywet , thank you for being receptive to and incorporating my feedback from yesterday! I appreciate your prompt response. The staged topic with those updates showed there's necessity for improvement still, sorry for the inadequate suggestions. I emailed you further feedback, this time with a rendering of the expected outcome. Hopefully with the visualization, we get a better picture and avoid further overhead for you.

**Comment by baywet** [comment]
> Thank you again, @baywet , for working on this automation! The staged display looks good to me!

Thank you @angelgolfer-ms for all the great feedback on this thread and offline!

**Pull request merged**
