### PR TITLE
Update serviceplaninfo.md

### PR DESCRIPTION
**Pull request by Justinha**
Added errorStatus

### CODE REVIEW

**Comment by Justinha** [comment]
#sign-off

**Comment by Lauragra** [comment]
@Justinha , I can't verify that this property is live in the metadata; can you let me know if you're ready to publish or are we waiting for the API to go live?

**Comment by Justinha** [comment]
@Lauragra sorry for delay, yes it's live.

**Comment by Lauragra** [comment]
> @Lauragra sorry for delay, yes it's live.

@Justinha , I can't verify that the property is live in the public metadata. Did it just get deployed, or do you know if it's hidden for some reason?

**Comment by Justinha** [comment]
@Lauragra Sorry, let me confirm.

**Pull request closed without merging**
