### PR TITLE
Adding Working With section and image

### PR DESCRIPTION
**Pull request by polio77**

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[0fda0fa](https://github.com/polio77/microsoft-graph-docs/pull/4264/commits/0fda0fa37f2e99b19814f0da811363fc51bf8dd7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/microsoftgraph/microsoft-graph-docs, working directory: W:\lpi4-s, target branch: master, target branch commit: 811602acc817f0abb99ca879a259efdcb4c4b07f, source branch: 606ad1d47dfa6a3551b5e898f6301c9c/master, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903271700239266-4264%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=9CmNevfyCaajBoNfPAPmbWvweUoC0NkzQ4q3afoP8UQ%3D&st=2019-03-27T16%3A56%3A30Z&se=2019-04-27T17%3A01%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by polio77** [comment]
Closing - will address issues offline

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[0fda0fa](https://github.com/polio77/microsoft-graph-docs/pull/4264/commits/0fda0fa37f2e99b19814f0da811363fc51bf8dd7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/microsoftgraph/microsoft-graph-docs, working directory: W:\o0je-s, target branch: master, target branch commit: 811602acc817f0abb99ca879a259efdcb4c4b07f, source branch: 606ad1d47dfa6a3551b5e898f6301c9c/master, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903271734172865-4264%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=RJMh4oXSy7yr6ys7fL4z7D4MHujCARSv9fnHM307u7w%3D&st=2019-03-27T17%3A30%3A22Z&se=2019-04-27T17%3A35%3A22Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
@polio77 , it looks like you're working from an old fork. Please bring your branch up to date with master and try your PR again. Currently the PR is not passing validation due to merge conflicts. Thanks.

**Comment by Lauragra** [comment]
Closing as this is a dupe of PR #4268.

**Pull request closed without merging**
