### PR TITLE
Update group.md

### PR DESCRIPTION
**Pull request by yyuank**

### CODE REVIEW

**Comment by Lauragra** [comment]
@yyuank , this this PR a dupe of PR #7980 ?

**Comment by yyuank** [comment]
@Lauragra This is to add the same content to V1. 7980 was for beta.

**Comment by Lauragra** [comment]
@yyuank , can you please apply the changes I made to PR 7980 to this PR as well? Thanks.

**Comment by yyuank** [comment]
@Lauragra Just added

**Pull request closed without merging**
