### PR TITLE
graph-2207v1-14955718

### PR DESCRIPTION
**Pull request by Erikre**

### CODE REVIEW

**Comment by Erikre** [comment]
@Lauragra - I don't have write access to resolve the conflicts in this PR. The conflicts are expected, because now that we've published the 2207 beta API, we need to resolve the beta vs. V1.0 additions. Can you help with that?

**Comment by Lauragra** [comment]
> @Lauragra - I don't have write access to resolve the conflicts in this PR. The conflicts are expected, because now that we've published the 2207 beta API, we need to resolve the beta vs. V1.0 additions. Can you help with that?

@Erikre , I can't resolve it in the browser. Can you create a new branch from the main branch and reopen a new PR?

**Comment by Erikre** [comment]
#sign-off

**Comment by Erikre** [comment]
@Lauragra - Please review and merge. Thanks

**Pull request merged**
