### PR TITLE
add new excel graph APIs - get/reply comments

### PR DESCRIPTION
**Pull request by lumine2008**
add new excel graph APIs - get/reply comments

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[8638fbf](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3750/commits/8638fbff0d962f83a4a1763eb016effe173514bb)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 21 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[8638fbf](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3750/commits/8638fbff0d962f83a4a1763eb016effe173514bb)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[8638fbf](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3750/commits/8638fbff0d962f83a4a1763eb016effe173514bb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/raymonlu-excelapi-comments/concepts/changelog.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901100818078856-3750%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=rKjkelnk1EP44dvburE3QYLQ4xeVzpChluuYuf5Hdvg%3D&st=2019-01-10T08%3A16%3A20Z&se=2019-02-10T08%3A21%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
@lumine2008 , are you planning to add a new API topic?

**Comment by Lauragra** [comment]
@lumine2008 , is this still a valid PR, or do we need to close for now? The Changelog entry was for January but I don't see the API docs. Thanks.

**Comment by Lauragra** [comment]
@lumine2008 , I did not see a PR to add these new APIs. Closing this PR. Please reopen to add the API docs and changelog entry when ready.

**Pull request closed without merging**
