### PR TITLE
- adds documentation for the administrative unit delta beta support

### PR DESCRIPTION
**Pull request by baywet**
@anandyadavMSFT I'm trying to close the gaps we have in terms of delta query support across versions.
From the metadata and my tests it looks like delta for administrative units made it to beta but this has never been documented. Can you review the content please?

### CODE REVIEW

**Comment by Lauragra** [comment]
@baywet , can you please take a look at the validation error? We need to get that resolved before we merge. Thanks.

**Comment by baywet** [comment]
@Lauragra I had looked at it, it's not clear to me what's making it fall. And the comment says validation passed. Can you reach out to somebody who had more expertise on that please?

**Comment by Lauragra** [comment]
Okay, let me look into it further.

**Comment by baywet** [comment]
For information this PR has been approved on a separate email thread

**Comment by baywet** [comment]
Hey @Lauragra thanks for the help with the PR. For this commit I think a few things need to be changed:
- application needs the preview tag to be removed (although that's probably going to conflict with the other PR)
- administrative unit, classes, directory object, education user, planner items, scools, service principals and chat messages need the beta links as they are still in preview


https://github.com/microsoftgraph/microsoft-graph-docs/commit/39c3aed046abf2dd5b66661dbefdb3c1092a5f0a

**Comment by Lauragra** [comment]
@baywet , can we let the preview label get removed in the other PR? We'll merge that as soon as we get sign off. For the links, we have new guidance for concept topics not to include the beta version. If there's no v1.0 topic, the link will default to the beta topic. Then when we GA, the link will automatically default to the v1.0 topic, so no need to update URLs in concept topics. We won't do this in the changelog, but I've started removing the version in other concept topics.

**Comment by baywet** [comment]
@Lauragra ok thanks for the additional context. I didn't know about that, it's going to make things simpler. And ok for the other PR, the conflict merge will be when we resolve things.

**Comment by baywet** [comment]
also in a previous comment I was mentioning this PR got an approval by email, so we're good to go as soon as your changes are done.

**Comment by Lauragra** [comment]
@baywet , I'm still trying to figure out the validation error. I pinged engineering yesterday. As soon as we get it to pass validation, we can merge.

**Comment by baywet** [comment]
@Lauragra I figured out what the problem was! It was a casing issue with the type referenced in the sample. See https://github.com/microsoftgraph/microsoft-graph-docs/pull/7692/commits/b583fe740f140b00e2a686d8f22a122eeedfcf57
We should be good to merge now.

**Pull request merged**
