### PR TITLE
add risky users info

### PR DESCRIPTION
**Pull request by cloudhandler**
Adds two new actions for riskyusers API and updates one property

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[288839d](https://github.com/cloudhandler/microsoft-graph-docs/pull/4202/commits/288839d5471f63ab8b0071c4db276c63f0d77825)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/microsoftgraph/microsoft-graph-docs, working directory: W:\pxpi-s, target branch: master, target branch commit: 1335796c6f721fe31005ffd4ad47824504690e31, source branch: acbc5c5d183cd8b4a0b0624394c00e9f/updateriskyusers, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903200015203710-4202%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=mRxOdjflSm4PK8hik9f38V6wTjMxL7i99zobFscxSrI%3D&st=2019-03-20T00%3A11%3A26Z&se=2019-04-20T00%3A16%3A26Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by cloudhandler** [comment]
@dkershaw10 / @Lauragra - can you please help get this merged? Thanks!

**Comment by Lauragra** [comment]
Replaced by PE #4214.

**Comment by lleonard-msft** [comment]
@cloudhandler - It looks like there are merge conflicts that need to be resolved.

**Pull request closed without merging**
