### PR TITLE
Adding new properties for the cloud PC entities

### PR DESCRIPTION
**Pull request by idwilliams**
Through this pull request a set of new properties are being added to the cloud PC entities that are part of Microsoft 365 Lighthouse

### CODE REVIEW

**Comment by idwilliams** [comment]
The changelog has been updated to resolve the merge conflict. Also, there was a duplicate description property in a different part of the changelog that is unrelated to this update. I removed that property to prevent any external complications.

**Review by Lauragra — APPROVED** [review]

**Comment by idwilliams** [comment]
@Lauragra the main branch was just merged with this source branch for this change to resolve the conflicts. Let me know if there are any other changes you would like to see before completing this request.

**Comment by Lauragra** [comment]
> @Lauragra the main branch was just merged with this source branch for this change to resolve the conflicts. Let me know if there are any other changes you would like to see before completing this request.

Can you please check the changelog file? It looks like with the conflict resolution, existing ChangeList items were overwritten or updated. We should be adding a new ChangeList item for this PR without altering any existing entries.

**Review by Lauragra — CHANGES_REQUESTED** [review]
@idwilliams , please take a look at the changelog in this PR before we merge. I think some changes inadvertently got overwritten. I'm going to remove the ready to merge label for now. Thanks.

**Comment by Lauragra** [comment]
@idwilliams , do you still want to publish this PR? If so, please address the issue with the changelog entry, per my previous comment. Thanks.

**Comment by idwilliams** [comment]
@Lauragra good catch, the issues with the changelog should be resolved now.

**Pull request merged**
