### PR TITLE
Adding GCC High Graph API Endpoint Info

### PR DESCRIPTION
**Pull request by SteveWinward**
Adding GCC High specific Graph API endpoint info (graph.microsoft.us).  Previously there was only information on the GCC (not GCC High) endpoint of graph.microsoft.com

### CODE REVIEW

**Comment by dkershaw10** [comment]
@navyasric @negoe Can you folks review this and double check with Adam that this is correct please?  @angelgolfer-ms Not sure I can comment on this.  It seems close.

**Comment by dkershaw10** [comment]
@negoe Can we close this PR? Haven't we separately updated the docs already?

**Comment by SteveWinward** [comment]
@dkershaw10 I'm happy to see this get closed, I just want to make sure that the GCC High endpoint for the Graph API is documented somewhere.  Do you have a link to where this is documented?

**Comment by Lauragra** [comment]
@SteveWinward , looks like it's documented here: https://docs.microsoft.com/en-us/graph/deployments. Please confirm that it's accurate and that we can close the PR. Thanks.

**Comment by dkershaw10** [comment]
@SteveWinward Per Laura, please let us know if this link has the info you are looking for.  I believe that we'll also be publishing a blog post with some more info too.

**Comment by SteveWinward** [comment]
@Lauragra  and @dkershaw10 this is perfect.  Thank you for following up on this.  Please feel free to close this issue now.

**Pull request closed without merging**
