### PR TITLE
Update auth-limit-mailbox-access.md

### PR DESCRIPTION
**Pull request by michelderooij**
Important to mention that for Exchange Web Services, full_access_as_app API permission also honors the Application Access Policy.

### CODE REVIEW

**Comment by jasonjoh** [comment]
Please disregard the earlier message from msftbot. Your pull request was incorrectly flagged.

**Comment by lramosvea** [comment]
Hi @abheek-das could you please take a look at this PR?

**Comment by isvargasmsft** [comment]
Hello @michelderooij, 

My sincere apologies for the delays in our response. Thank you very much for bringing this into our attention. We are working with the Exchange team to properly organize the content and include your suggestions in the documentation. 

Thank you for your patience. Please feel free to email me if you have any further questions. 

Kind regards, 

Isaac Vargas

**Comment by angelgolfer-ms** [comment]
Hi @michelderooij , thank you again for bringing our attention to this oversight in documenting the support. I'll merge your PR in a moment, and will follow shortly to reorganize the rest of the content for greater clarity. Appreciate your patience!

**Pull request merged**
