### PR TITLE
Consolidate known issues for Teams in the Known Issues page

### PR DESCRIPTION
**Pull request by YannickRe**
Moving issues that are mentioned in the docs into the Known Issues page

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[fc69d88](https://github.com/YannickRe/microsoft-graph-docs/pull/4138/commits/fc69d8877de6e4bfbe5158861c1c5a1801cbbcc9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-clone.md](https://github.com/YannickRe/microsoft-graph-docs/blob/teams-knownissues-consolidation/api-reference/beta/api/team-clone.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/YannickRe/microsoft-graph-docs/blob/teams-knownissues-consolidation/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/team-clone.md](https://github.com/YannickRe/microsoft-graph-docs/blob/teams-knownissues-consolidation/api-reference/v1.0/api/team-clone.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/YannickRe/microsoft-graph-docs/blob/teams-knownissues-consolidation/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | |
[concepts/known-issues.md](https://github.com/YannickRe/microsoft-graph-docs/blob/teams-knownissues-consolidation/concepts/known-issues.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903120821273110-4138%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=03u5iQhS3FXenFg2xIFuORXBAVlz2jo0o3scQ8mDRAo%3D&st=2019-03-12T08%3A20%3A16Z&se=2019-04-12T08%3A25%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
@nkramer , please review this PR. Thanks.

**Comment by YannickRe** [comment]
@nkramer I understand but it would be consistent with the other known issues. None of them are mentioned on their API page and only on the Know Issues list.
If it's a known issue, it belongs on the list (otherwise, why have this list?). I do agree that mentioning the issues on the relevant API pages would be an added value, but that's a d change in approach that should be done throughout the whole documentation.

**Comment by Lauragra** [comment]
For reference, this is the guidance for documenting Known issues: https://msgo.azurewebsites.net/add/document/guidelines/known-issues.html. Basically, we centralize them in the Known issues topic. We can reference and link to them from reference topics. If a Known issue doesn't have a timeline to be fixed, we document it as the "default behavior" in the reference topic. Does that help?

**Comment by YannickRe** [comment]
@Lauragra So that means my PR is bringing the documentation in line with the guidelines and it can be merged, right? Or do you expect changes to be made on my side?

**Comment by Lauragra** [comment]
@YannickRe , I think the point is that if we don't have a timeline for fixing the known issues, they are more like "default behavior" and should be documented in the individual topics. If they are short term known issues that we plan to fix and then remove from the topic, the consolidation is okay; Let's make sure that @nkramer signs off on this PR. Thanks.

**Comment by YannickRe** [comment]
Understood, although I strongly feel that they should at least also be on the Known Issues list.

**Comment by Lauragra** [comment]
@nkramer , can you let us know how you'd like to proceed on this PR?

**Comment by Lauragra** [comment]
Closing this PR as it was not approved and does not conform to our guidelines for documenting Known issues. FYI, if there is no timeline for fixing an issue, we document that behavior in the API topics.

**Comment by YannickRe** [comment]
@Lauragra I hope you can rethink your approach on this. I don't care about this particular PR, but I do care about the overall process. Like I stated before: if an issue is known, I firmly believe it belongs at least on the Known Issues page. No user of your documentation knows (or cares for that matter) about that distinction.

It also doesn't make any sense nor are you consistent when I go look at the history of the page. I suggest you go compare the version of 8 months ago (probably the older history got lost due to renames/changing location since I'm sure some issues are on there for longer than those 8 months), and compare it with the current version: https://github.com/microsoftgraph/microsoft-graph-docs/blob/7329c14540cb10ec388791171e94191c4c0e5f5b/concepts/known-issues.md
I can't believe that those issues all have a timeline to be fixed...

I look at the Know Issues page to assess if I need to take action on previously created applications, I follow up the Known Issues page and the Changes page to assess for new functionality and potential issues in already released applications.

@nkramer Completely independent of the PR, I also feel that the "known issue without a timeline to fix" of the /delete/owners thing is a MAJOR bug. This causes data inconsistency between Azure AD and Teams, since Azure AD does behave correctly and only Teams is acting up.
As a result, unknowing developers can cause major havoc on their data while there is no reason to believe Teams will "eventually" catch up with Azure AD again.

**Comment by YannickRe** [comment]
@Lauragra The inline "Known Issues" aren't easily discoverable on the page, they are styled differently for every workload and there is no consistency. Consistency that can be achieved in a couple of ways:
- Document issues on the Known Issues page as well, but it requires double effort in maintenance
- Create some sort of tag with associated styling to document issues inline on the workload page. As a bonus, use the tag to consolidate all the known issues from all pages in the documentation on the Known Issues page while doing a build of your docs.

There are probably more options too, to make this a better experience for all users, contributors and product groups involved.

**Pull request closed without merging**
