### PR TITLE
Update formating in Planner docs

### PR DESCRIPTION
**Pull request by dzhavat**
I'm wondering, are these type of PRs welcome? 

I mean, changing **`plannerplan`** to **`plannerPlan`** seems ok, but what about **`{id}`** to **`{plan-id}`** in order to make it more explicit (and also sometimes to look similar to the example given in the example section)?

### CODE REVIEW

**Comment by Lauragra** [comment]
@erayc-msft , can you take a look and approve if you are okay with the proposed changes? Thanks!

**Comment by dzhavat** [comment]
@Lauragra @erayc-msft Any comments on the question I posted?

**Comment by Lauragra** [comment]
Yes, agree with the change from plannerplan to plannerPlan. I think that the ID change is okay, when the context is unclear. I'd like @erayc-msft or @TarkanSevilmis to approve that change. Thanks.

**Comment by Lauragra** [comment]
@TarkanSevilmis , do you want to merge this update? If so, we'll need to open a new PR since this was opened before the docs migration.

**Comment by TarkanSevilmis** [comment]
This seems fine to merge. For some reason the original notification for this is missing from my inbox.

**Comment by Lauragra** [comment]
@TarkanSevilmis , thanks. FYI, we'll open a new PR with these changes and close this one since we can't merge it.

**Comment by Lauragra** [comment]
Created PR #5201 to merge these changes. Thanks.

**Pull request closed without merging**
