### PR TITLE
adding GroupMember.Read.All as least privileged permission for list groups, get groups, and group delta in beta and v1

### PR DESCRIPTION
**Pull request by Jordanndahl**

### CODE REVIEW

**Comment by Jordanndahl** [comment]
@davidmu1 @CelesteDG Can either of you provide help to solve this conflict?

**Review by davidmu1 — APPROVED** [review]

**Comment by Lauragra** [comment]
@Jordanndahl , please take care of the merge conflicts in this PR. Not sure if there is an issue with your branch getting out of date?

**Comment by CelesteDG** [comment]
@Jordanndahl - Is this still a PR in progress / still needed or has it gone stale and should be closed? Looks like it was opened way back in November so if it's still active the branch needs to take in all the new changes in main to resolve the merge conflicts.

CC @davidmu1

**Comment by Jordanndahl** [comment]
> @Jordanndahl - Is this still a PR in progress / still needed or has it gone stale and should be closed? Looks like it was opened way back in November so if it's still active the branch needs to take in all the new changes in main to resolve the merge conflicts.
> 
> CC @davidmu1

@CelesteDG looks like these changes have been made in the documentation. I believe this is stale.

**Comment by CelesteDG** [comment]
Thank you, @Jordanndahl - Okay if I go ahead and close this PR based on your comment?

**Comment by Jordanndahl** [comment]
@CelesteDG Yup, fine to close!

**Comment by CelesteDG** [comment]
Per agreement with @Jordanndahl - Closing this PR as the changes have already been made and PR is no longer needed.

**Pull request closed without merging**
