### PR TITLE
Adding passwordsinglesignonsettings to servicePrincipal

### PR DESCRIPTION
**Pull request by luleonpla**

### CODE REVIEW

**Comment by luleonpla** [comment]
@Lauragra I have added the changelog. I'm not sure why is complaining for the link since that's the path for serviceprincipal doc https://docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0

**Comment by luleonpla** [comment]
@Lauragra I fixed the conflict but still see the warning for the links :(

**Comment by Lauragra** [comment]
@luleonpla , the warnings should be fixed now.

**Comment by luleonpla** [comment]
Thank you @Lauragra. I see I was missing a "/". 

This is good from my side to be published.

**Pull request merged**
