### PR TITLE
Update Microsoft.DirectoryServices.json

### PR DESCRIPTION
**Pull request by arpitha-dhanapathi**
Updating Changelog for verifiedPublisher property added to the servicePrincipal object

### CODE REVIEW

**Comment by FaithOmbongi** [comment]
Hi @arpitha-dhanapathi - The **verifiedPublisher** property was been live for almost 2 years and a changelog object was added at the time via https://github.com/microsoftgraph/microsoft-graph-docs/pull/9827. Any reason why you want to add another changelog for the property?

**Comment by arpitha-dhanapathi** [comment]
The verifiedPublisher property was not part of servicePrinciple object in the code (missed), but the docs were already reflecting as if it was there.
Now, to checkin the required code changes, we need a changeLog PR which is what I have added (I didn’t make any doc changes though, since it’s already been done)

Best
Arpitha

On Aug 12, 2022, at 2:42 PM, Faith Moraa Ombongi ***@***.***> wrote:

﻿

Hi @arpitha-dhanapathi<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Farpitha-dhanapathi&data=05%7C01%7CArpitha.Dhanapathi%40microsoft.com%7Cf14df07b4f6c4f6bf90208da7c42ce06%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637958923634878074%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XlGuxoZ9FjJ00%2FfWWkKqPutmcLZHO6xDlgq8vU7q00s%3D&reserved=0> - The verifiedPublisher property has been live for almost 2 years and a changelog object was added at the time via #9827<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoftgraph%2Fmicrosoft-graph-docs%2Fpull%2F9827&data=05%7C01%7CArpitha.Dhanapathi%40microsoft.com%7Cf14df07b4f6c4f6bf90208da7c42ce06%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637958923634878074%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zGydJzVVjCYSn395pkTCz53%2BU3WpY%2FzWP8Th8ve3md8%3D&reserved=0>. Any reason why you want to add another changelog for the property?

**Comment by FaithOmbongi** [comment]
@arpitha-dhanapathi - Then I recommend that you use the old PR number for your schema validation and close this PR. This is the old PR https://github.com/microsoftgraph/microsoft-graph-docs/pull/9827. LMK if this remains a blocker for you.

**Comment by FaithOmbongi** [comment]
Hi @arpitha-dhanapathi - As per my last feedback, we'll not need to publish this PR. I'll close it as part of repo hygiene.

**Pull request closed without merging**
