### PR TITLE
Update dataPolicyOperation with progress

### PR DESCRIPTION
**Pull request by gababu**
Update dataPolicyOperation with progress property

### CODE REVIEW

**Comment by jthake-msft** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/datapolicyoperation.md](https://github.com/gababu/microsoft-graph-docs/blob/patch-3/api-reference/beta/resources/datapolicyoperation.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201811151842048740-3396%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=B%2B09gMtRAmdxJ4QypF9fWeirjxzbF8Oh7yLs2NYcNlE%3D&st=2018-11-15T18%3A39%3A12Z&se=2018-12-16T18%3A44%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/datapolicyoperation.md](https://github.com/gababu/microsoft-graph-docs/blob/patch-3/api-reference/beta/resources/datapolicyoperation.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201811151919411053-3396%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=1XwkQ%2FyxnEQGoj1214KDfxgBbqgtLjDNJWFFS%2FjOYWM%3D&st=2018-11-15T19%3A16%3A56Z&se=2018-12-16T19%3A21%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by gababu** [comment]
@lleonard-msft @dkershaw10  - Please review this PR

**Comment by jthake-msft** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/datapolicyoperation.md](https://github.com/gababu/microsoft-graph-docs/blob/patch-3/api-reference/beta/resources/datapolicyoperation.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201812041840148327-3396%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=IaMo1B16zS54DHWelFMVAzbS1GyDAHq7VObqBzMuLSA%3D&st=2018-12-04T18%3A38%3A15Z&se=2019-01-04T18%3A43%3A15Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
