### PR TITLE
Update defaultuserrolepermissions.md

### PR DESCRIPTION
**Pull request by myra-ramdenbourg**
Updating the property and Json representation for Tenant creation lockdown feature

### CODE REVIEW

**Comment by myra-ramdenbourg** [comment]
Hi @FaithOmbongi and @rolyon, could you please help me get this change merged? Thanks!

**Comment by FaithOmbongi** [comment]
Hi @myra-ramdenbourg - Please do the following to help us schedule this work for review:
1. Create a content review work item at https://aka.ms/msgraph-identity-workitem and add the links to the API.md and Schema PR in the work item description.
2. When you're ready for this PR to be reviewed add the **ready for content review** label.

Hi @msewaweru - kindly assist to review this PR when it's ready to. Thanks.

**Comment by myra-ramdenbourg** [comment]
This is the work item request for the doc review: https://dev.azure.com/msft-skilling/Content/_workitems/edit/80995

**Review by msewaweru — APPROVED** [review]
LGTM! Thanks @myra-ramdenbourg.

**Pull request merged**
