### PR TITLE
Beta calls, creation and get and base examples updated

### PR DESCRIPTION
**Pull request by takanapa**
Update examples in Post calls and Get calls and updated information provided

### CODE REVIEW

**Comment by Lauragra** [comment]
@takanapa, please reach out to me internally regarding this PR. Thanks.

**Comment by Lauragra** [comment]
@VinodRavichandran , please review this PR.

**Comment by takanapa** [comment]
Abandoning this PR per internal discussion, for a larger set of docs for same workload planning to send a single PR

**Comment by Lauragra** [comment]
@takanapa , @VinodRavichandran , what is the merge status of this PR? It has a number of merge conflicts; please resolve and/or close the PR.

**Pull request closed without merging**
