### PR TITLE
Added section about extension attributes in delta query

### PR DESCRIPTION
**Pull request by piotrci**

### CODE REVIEW

**Comment by jthake-msft** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user_delta.md](https://github.com/piotrci/microsoft-graph-docs/blob/ExtensionAttributesDeltaQuery/api-reference/beta/api/user_delta.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fuser_delta.md)
[api-reference/v1.0/api/user_delta.md](https://github.com/piotrci/microsoft-graph-docs/blob/ExtensionAttributesDeltaQuery/api-reference/v1.0/api/user_delta.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fv1.0%2Fapi%2Fuser_delta.md)

<a name="api-reference%2Fbeta%2Fapi%2Fuser_delta.md"></a>
### [api-reference/beta/api/user_delta.md](https://github.com/piotrci/microsoft-graph-docs/blob/ExtensionAttributesDeltaQuery/api-reference/beta/api/user_delta.md)
 - **Line 5**: **[Warning]** Invalid file link:(~/../concepts/delta_query_overview.md).
 - **Line 9**: **[Warning]** Invalid file link:(~/../concepts/permissions_reference.md).
 - **Line 37**: **[Warning]** Invalid file link:(~/../concepts/delta_query_overview.md).
 - **Line 38**: **[Warning]** Invalid file link:(~/../concepts/delta_query_overview.md).
 - **Line 236**: **[Warning]** Invalid file link:(~/../concepts/delta_query_overview.md).
 - **Line 237**: **[Warning]** Invalid file link:(~/../concepts/delta_query_users.md).

<a name="api-reference%2Fv1.0%2Fapi%2Fuser_delta.md"></a>
### [api-reference/v1.0/api/user_delta.md](https://github.com/piotrci/microsoft-graph-docs/blob/ExtensionAttributesDeltaQuery/api-reference/v1.0/api/user_delta.md)
 - **Line 3**: **[Warning]** Invalid file link:(~/../concepts/delta_query_overview.md).
 - **Line 7**: **[Warning]** Invalid file link:(~/../concepts/permissions_reference.md).
 - **Line 35**: **[Warning]** Invalid file link:(~/../concepts/delta_query_overview.md).
 - **Line 36**: **[Warning]** Invalid file link:(~/../concepts/delta_query_overview.md).
 - **Line 234**: **[Warning]** Invalid file link:(~/../concepts/delta_query_overview.md).
 - **Line 235**: **[Warning]** Invalid file link:(~/../concepts/delta_query_users.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201811210124030805-3452%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=lmf6QWxT3vdDxT1uEVsCqC1tFnqM9cvWtC8JEggHCak%3D&st=2018-11-21T01%3A25%3A02Z&se=2018-12-22T01%3A30%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-delta.md](https://github.com/piotrci/microsoft-graph-docs/blob/ExtensionAttributesDeltaQuery/api-reference/beta/api/user-delta.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fuser-delta.md)
[api-reference/v1.0/api/user-delta.md](https://github.com/piotrci/microsoft-graph-docs/blob/ExtensionAttributesDeltaQuery/api-reference/v1.0/api/user-delta.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fv1.0%2Fapi%2Fuser-delta.md)

<a name="api-reference%2Fbeta%2Fapi%2Fuser-delta.md"></a>
### [api-reference/beta/api/user-delta.md](https://github.com/piotrci/microsoft-graph-docs/blob/ExtensionAttributesDeltaQuery/api-reference/beta/api/user-delta.md)
 - **Line 241**: **[Warning]** Invalid file link:(~/../concepts/delta_query_overview.md).
 - **Line 242**: **[Warning]** Invalid file link:(~/../concepts/delta_query_users.md).

<a name="api-reference%2Fv1.0%2Fapi%2Fuser-delta.md"></a>
### [api-reference/v1.0/api/user-delta.md](https://github.com/piotrci/microsoft-graph-docs/blob/ExtensionAttributesDeltaQuery/api-reference/v1.0/api/user-delta.md)
 - **Line 239**: **[Warning]** Invalid file link:(~/../concepts/delta_query_overview.md).
 - **Line 240**: **[Warning]** Invalid file link:(~/../concepts/delta_query_users.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201811282301565318-3452%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=O7Ohgj5CP3%2FBxdqZro8zzVcIDYbgpeyhz10dtPFDJEM%3D&st=2018-11-28T23%3A00%3A17Z&se=2018-12-29T23%3A05%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
@dkershaw10 , @piotrci , what do we want to do with this PR? If we still want this update, we'll need to close this one and open a new one that's compatible with the new documentation standards.

**Comment by Lauragra** [comment]
@piotrci, I'm closing this PR as we don't support custom H2s in API topics. Please add this content to the delta query conceptual content: https://docs.microsoft.com/en-us/graph/delta-query-overview. Thanks.

**Pull request closed without merging**
