### PR TITLE
Changelog for deprecated APIs

### PR DESCRIPTION
**Pull request by besiler**
PR Number: 6386954

### CODE REVIEW

**Comment by FaithOmbongi** [comment]
Hi @besiler - could you share the related schema PR number? Not the full link, just the PR number. Thanks.

**Comment by besiler** [comment]
> Hi @besiler - could you share the related schema PR number? Not the full link, just the PR number. Thanks.

@FaithOmbongi  the number is 6386954

**Comment by Lauragra** [comment]
@besiler , can you please reach out to me internally to share the location of your PR? I'm not finding it. Is there a docs PR associated with this changelog entry? Thanks.

**Comment by besiler** [comment]
> @besiler , can you please reach out to me internally to share the location of your PR? I'm not finding it. Is there a docs PR associated with this changelog entry? Thanks.

I'll Teams you and Faith

**Review by Lauragra — APPROVED** [review]

**Comment by Lauragra** [comment]
@BenAlfasi , we decided not to publish this PR so I'm going to go ahead and close. Thanks.

**Pull request closed without merging**
