### PR TITLE
update permissions-reference.md

### PR DESCRIPTION
**Pull request by bhartono**
added the following permissions:

team.readbasic.all
teamsettings.read.all
teamsettings.readwrite.all
channel.readbasic.all
channel.create
channel.delete.all
channelsettings.read.all
channelsettings.readwrite.all

chat.readbasic
chat.readbasic.all
chat.send
chat.send.all

channelmessage.read.all
channelmessage.send
channelmessage.edit
channelmessage.delete

### CODE REVIEW

**Comment by bhartono** [comment]
@nkramer / @Lauragra , please review and approve when appropriate - somehow github no longer allow me to add reviewer from the top right section anymore.

**Comment by bhartono** [comment]
> I assume you're gonna check this until the permissions actually do something? If we don't have APIs that use them when we check in, let's add the disclaimer text about how they are in private preview.

I've added the disclaimer text that they are in private preview

**Comment by bhartono** [comment]
@Lauragra please merge, changes are pushed to prod already

**Comment by Lauragra** [comment]
@bhartono , please follow the standard workflow and apply labels so your PRs will show up in my queries. I set *ready to merge* on this so we can get it in today.

**Comment by bhartono** [comment]
> @bhartono , please follow the standard workflow and apply labels so your PRs will show up in my queries. I set _ready to merge_ on this so we can get it in today.

will label 'ready to merge' for the next one. thank you for setting the label on this one.

**Pull request merged**
