### PR TITLE
Updated Comms API page

### PR DESCRIPTION
**Pull request by VinodRavichandran**
- renamed calls-api-overview to communications-api-overview
- updated content
- Fixed links

### CODE REVIEW

**Comment by VinodRavichandran** [comment]
Hi @Lauragra, Can you let me know why API doctor stage failed? It says 'failed with poweshell code 1', not sure what that means

**Comment by Lauragra** [comment]
@VinodRavichandran , I fixed the validation errors - we had a missing metadata attribute and a broken link caused by renaming the file.

**Comment by Lauragra** [comment]
@VinodRavichandran , do we need to wait for PR #3323 to be ready and merge both PRs at once? Otherwise this is ready to go. Thanks.

**Comment by VinodRavichandran** [comment]
Hi @Lauragra, you can go ahead with this change, shouldn't break anything not has any dependency.

**Pull request merged**
