### PR TITLE
Update create-onlinemeeting-user-token-csharp-snippets.md

### PR DESCRIPTION
**Pull request by ravi16a87**
There is no documentation available on "AdditionalData" property and how to use this to override default OnlineMeeting Properties. Hence proposing these changes.

### CODE REVIEW

**Comment by ravi16a87** [comment]
Hello @andrueastman @Lauragra , did you get a chance to look at this pull request?

**Comment by andrueastman** [comment]
Hey @ravi16a87,

Apologies for the delayed response. 
As the C# snippets are autogenerated from the HTTP example, merging this PR will lead to the changes eventually being overridden. 

Since this is an issue with a missing property in the HTTP example, can you only update the HTTP example in the docs with the missing example? The snippet generator will pick this up and update the sample on its next run after this.

**Comment by ravi16a87** [comment]
Hi @andrueastman , Thanks for your reply. Sure I will do it and create a new PR.

**Comment by andrueastman** [comment]
No worries @ravi16a87. If it's okay, I'll close this for now as you will create a separate PR for this.

**Comment by ravi16a87** [comment]
Hello @andrueastman , With respect to HTTPS you can directly override like this :
{
    "startDateTime": "2022-07-12T14:30:34.2444915-07:00",
    "endDateTime": "2022-07-12T15:00:34.2464912-07:00",
    "subject": "User Token Meeting",
    "allowMeetingChat": "disabled"
}

but when it comes to c# , we cannot pass object like this, we need to have additional data object and pass properties in that object to override the properties

**Comment by andrueastman** [comment]
Thanks @ravi16a87.

I believe the C# SDK has the property for "allowMeetingChat" as seen [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/5da2eb3285030ee1ece1c0d7870a19e164c71bc2/src/Microsoft.Graph/Generated/model/OnlineMeeting.cs#L50). So, it might not be necessary to use the additionalData bag in this scenario. 

The snippet generator will therefore be able to generate the correct snippet as below once the PR is merged. 

```cs
            var onlineMeeting = new OnlineMeeting
            {
                StartDateTime = DateTimeOffset.Parse("2022-07-12T21:30:34.2444915+00:00"),
                EndDateTime = DateTimeOffset.Parse("2022-07-12T22:00:34.2464912+00:00"),
                Subject = "User Token Meeting",
                AllowMeetingChat = MeetingChatMode.Disabled
            };

            await graphClient.Me.OnlineMeetings
                .Request()
                .AddAsync(onlineMeeting);
```

**Pull request closed without merging**
