### PR TITLE
Promote riskDetection & riskyUsers to v1.0

### PR DESCRIPTION
**Pull request by cloudhandler**

### CODE REVIEW

**Comment by cloudhandler** [comment]
@Lauragra - we're ready to publish, I followed the instructions for the v1.0 promotion docs but have a bunch of errors I'm not sure how to fix. Can you please assist?

**Comment by cloudhandler** [comment]
Hey @Lauragra - I'm getting an error on the Error-InvalidTocFile that I'm not sure how to fix?

**Comment by Lauragra** [comment]
> Hey @Lauragra - I'm getting an error on the Error-InvalidTocFile that I'm not sure how to fix?

Can you try renaming the file in v1.0? We use all lowercase for file names. 
image

**Comment by cloudhandler** [comment]
@Lauragra - we need to make a change, will be moving these under a new /identityProtection segment. Will update the pr once I know more

**Comment by cloudhandler** [comment]
Made some changes to the schema, generated a new pr: https://github.com/microsoftgraph/microsoft-graph-docs/pull/8816

**Pull request closed without merging**
