### PR TITLE
it's is abbreviation for it is. Should be its here

### PR DESCRIPTION
**Pull request by nfegan**
Just removed the apostrophe. Use of "it's" should be "its" in that sentence. "it's" is abbreviation for "it is".

### CODE REVIEW

**Comment by jthake-msft** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/driveitem_get_content_format.md](https://github.com/nfegan/microsoft-graph-docs/blob/fix-typo/api-reference/v1.0/api/driveitem_get_content_format.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fv1.0%2Fapi%2Fdriveitem_get_content_format.md)

<a name="api-reference%2Fv1.0%2Fapi%2Fdriveitem_get_content_format.md"></a>
### [api-reference/v1.0/api/driveitem_get_content_format.md](https://github.com/nfegan/microsoft-graph-docs/blob/fix-typo/api-reference/v1.0/api/driveitem_get_content_format.md)
 - **Line 73**: **[Warning]** Invalid file link:(~/../concepts/errors.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201811202127124710-3447%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Qh9qtjCWle5v8ujnaN6otSI9Zdo611lerXCMwymn0go%3D&st=2018-11-20T21%3A25%3A00Z&se=2018-12-21T21%3A30%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
Thanks for contribution @nfegan . 

There is actually a beta version of the same file located
api-reference/beta/api/driveitem_get_content_format.md

would you mind updating your PR to be inclusive of this if possible? That way you get contribution, rather than me doing it. Totally up to you...

**Comment by jthake-msft** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem_get_content_format.md](https://github.com/nfegan/microsoft-graph-docs/blob/fix-typo/api-reference/beta/api/driveitem_get_content_format.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fdriveitem_get_content_format.md)
[api-reference/v1.0/api/driveitem_get_content_format.md](https://github.com/nfegan/microsoft-graph-docs/blob/fix-typo/api-reference/v1.0/api/driveitem_get_content_format.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fv1.0%2Fapi%2Fdriveitem_get_content_format.md)

<a name="api-reference%2Fbeta%2Fapi%2Fdriveitem_get_content_format.md"></a>
### [api-reference/beta/api/driveitem_get_content_format.md](https://github.com/nfegan/microsoft-graph-docs/blob/fix-typo/api-reference/beta/api/driveitem_get_content_format.md)
 - **Line 76**: **[Warning]** Invalid file link:(~/../concepts/errors.md).

<a name="api-reference%2Fv1.0%2Fapi%2Fdriveitem_get_content_format.md"></a>
### [api-reference/v1.0/api/driveitem_get_content_format.md](https://github.com/nfegan/microsoft-graph-docs/blob/fix-typo/api-reference/v1.0/api/driveitem_get_content_format.md)
 - **Line 73**: **[Warning]** Invalid file link:(~/../concepts/errors.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201811262106122750-3447%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=uGTWBE7GMAjmG%2B2BZe7SYfZuw8MdJSMi6ZDTE61b7n4%3D&st=2018-11-26T21%3A04%3A31Z&se=2018-12-27T21%3A09%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
Thanks. This PR had a merge conflict following our migration so I created a new PR, #3580, to make this fix, and will close this one.

**Pull request closed without merging**
