### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by yyuank**

### CODE REVIEW

**Comment by Lauragra** [comment]
@yyuank  , what is the merge status of this PR? Please also include a changelog entry.

**Comment by yyuank** [comment]
@Lauragra This property is not in v1 yet. To move the property to V1, we need to include the PR number for schema review, so I created this PR. I'll update the status of this PR and add a changelog entry, once engineering work is complete. Thanks!!

**Comment by Lauragra** [comment]
> @Lauragra This property is not in v1 yet. To move the property to V1, we need to include the PR number for schema review, so I created this PR. I'll update the status of this PR and add a changelog entry, once engineering work is complete. Thanks!!

Okay, thanks. In the future, please set the **do not merge** label on the PR. When the API ships, change the label to **ready to merge**.

**Comment by jasonjoh** [comment]
@yyuank Given the name of this PR, I'm guessing you added these files using the "Upload files" button on GitHub? We're asking contributors not to do that because it introduces bad line endings into the repository by bypassing a git client. I've fixed it for this PR so no action is needed.

@Lauragra it's a good idea to watch for this when you see PR's with this title. Catching this before it merges into master saves a lot of headache down the road. You can fix it very simply by opening the PR with [GitHub Desktop](https://desktop.github.com/). It will detect the file as a full-file change, and you can just commit and push.

**Comment by yyuank** [comment]
Changelog PR: https://github.com/microsoftgraph/microsoft-graph-docs/pull/8531

**Comment by Lauragra** [comment]
> Changelog PR: #8531

Please do not create separate PRs for the changelog entries. As I mentioned on the other PR, you need an authoring branch, and you can make all changes/updates in that branch and submit a single PR. I will have to stop accepting these in the future as each separate PR takes time to process and this becomes unsustainable. Thanks.

**Comment by Lauragra** [comment]
> @yyuank Given the name of this PR, I'm guessing you added these files using the "Upload files" button on GitHub? We're asking contributors not to do that because it introduces bad line endings into the repository by bypassing a git client. I've fixed it for this PR so no action is needed.
> 
> @Lauragra it's a good idea to watch for this when you see PR's with this title. Catching this before it merges into master saves a lot of headache down the road. You can fix it very simply by opening the PR with [GitHub Desktop](https://desktop.github.com/). It will detect the file as a full-file change, and you can just commit and push.

@yyuank , please follow our authoring process, documented here: https://msgo.azurewebsites.net/add/document/manage-content/create-new-documentation.html. Please do not upload files directly and that causes errors that block us from publishing docs. Can you please close and recreate this PR following the correct process? Let the Microsoft Graph Docs v-team know if you need help. Thanks.

**Pull request closed without merging**
