### PR TITLE
Add new reviewed properties to EduAssignments docs

### PR DESCRIPTION
**Pull request by dipakboyed**

### CODE REVIEW

**Comment by dipakboyed** [comment]
Hi @Lauragra , these changes were deployed yesterday, the content is now ready to merge

**Comment by dipakboyed** [comment]
Hi @Lauragra , do you know what is the deployment cadence and when the update of docs is going to happen now that the changes have been merged? (still don't see changes live in prod)

**Comment by Lauragra** [comment]
@dipakboyed , yes, I merged the PR into master but we haven't done a merge into live to publish. Generally those happen at the end of every business day. If you need your changes pushed out sooner, LMK and I can do an OOB publish.

**Comment by dipakboyed** [comment]
end of day push is good at this point. Thanks @Lauragra 
bitmoji

**Pull request merged**
