### PR TITLE
(Ready to merge) Document configuring Word/Excel/PowerPoint/PDF tabs in Teams

### PR DESCRIPTION
**Pull request by nkramer**

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[3bb5851](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3811/commits/3bb58515acc5d920eb764928421ed796878d83c6)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[3bb5851](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3811/commits/3bb58515acc5d920eb764928421ed796878d83c6)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[3bb5851](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3811/commits/3bb58515acc5d920eb764928421ed796878d83c6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-configuring-builtin-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nkramer-patch-2/concepts/teams-configuring-builtin-tabs.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901172137562390-3811%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=cMbNQzwdZ3zYAso2G%2FNQuA7IgAC7CtrJNl%2BxyhRUIcY%3D&st=2019-01-17T21%3A35%3A59Z&se=2019-02-17T21%3A40%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[2cf0ac8](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3811/commits/2cf0ac80c4fe7e848e366d106842095e127cc898)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

**Comment by Lauragra** [comment]
@nkramer , should we add this topic to the TOC as a child under https://docs.microsoft.com/en-us/graph/teams-concept-overview?

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[2cf0ac8](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3811/commits/2cf0ac80c4fe7e848e366d106842095e127cc898)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[2cf0ac8](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3811/commits/2cf0ac80c4fe7e848e366d106842095e127cc898)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-configuring-builtin-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nkramer-patch-2/concepts/teams-configuring-builtin-tabs.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901172214541717-3811%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=IcUzfeur0mqHmYC4nqk4I31jqtK1Cl3UEMHuUTCeaRQ%3D&st=2019-01-17T22%3A12%3A53Z&se=2019-02-17T22%3A17%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[72a0415](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3811/commits/72a0415319db9f5eae97719a2e4bed34439d91f0)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[72a0415](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3811/commits/72a0415319db9f5eae97719a2e4bed34439d91f0)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[72a0415](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3811/commits/72a0415319db9f5eae97719a2e4bed34439d91f0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-configuring-builtin-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nkramer-patch-2/concepts/teams-configuring-builtin-tabs.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901172310496919-3811%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=4ZubuZjU2q7%2F9tmpZGJJgFSg4Z1tVWCf77I4vTR1m5Q%3D&st=2019-01-17T23%3A09%3A03Z&se=2019-02-17T23%3A14%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
