### PR TITLE
Update sortOrderIndex value in JSON representation

### PR DESCRIPTION
**Pull request by tony-xia**
The type of sortOrderIndex is int rather than string

### CODE REVIEW

**Comment by jthake-msft** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamstab.md](https://github.com/tony-xia/microsoft-graph-docs/blob/sortOrderIndex-type/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/teamstab.md](https://github.com/tony-xia/microsoft-graph-docs/blob/sortOrderIndex-type/api-reference/v1.0/resources/teamstab.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201812071338094965-3576%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=zEtSvcV9bRz95akRn%2FmK5sU3WHHAytKiBVt8Jrx2xyc%3D&st=2018-12-07T13%3A36%3A17Z&se=2019-01-07T13%3A41%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
@nkramer , can you please review/approve this PR?

**Comment by tony-xia** [comment]
any update? thanks

**Comment by nkramer** [comment]
Actually in the code it's string, not int. I don't know whether it should have been, or whether it's practical to change it at this point.

**Comment by Lauragra** [comment]
Okay, thanks; I'll close this PR.

**Comment by nkramer** [comment]
Apparently there are some edge cases where we return a non-integer today.

**Comment by tony-xia** [comment]
@Lauragra @nkramer it confuses me more. please check the below links and screenshots.
https://docs.microsoft.com/en-us/graph/api/teamstab-list?view=graph-rest-beta
image

https://docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta
image

Please review this PR again and looking forward to your reply. thanks

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[3982fad](https://github.com/tony-xia/microsoft-graph-docs/pull/3576/commits/3982fad932f1d63f1d059e355dbc80671c412f4c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamstab.md](https://github.com/tony-xia/microsoft-graph-docs/blob/sortOrderIndex-type/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/teamstab.md](https://github.com/tony-xia/microsoft-graph-docs/blob/sortOrderIndex-type/api-reference/v1.0/resources/teamstab.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201812180526402123-3576%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=5c%2Flho9yL0lATpTPsGAtZbkzrut9L%2FMLJhvxxnm%2FsY4%3D&st=2018-12-18T05%3A31%3A38Z&se=2019-01-18T05%3A36%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by tony-xia** [comment]
I tried GraphExplorer, it looks like `sortOrderIndex` is a string in beta version. So, could I raise another PR to update the docs for changing the type from `int` to `string`?

**Comment by Lauragra** [comment]
@nkramer , are we ready to merge this PR?

**Comment by nkramer** [comment]
To accurately reflect the product, we need to remove sortOrderIndex from v1.0 docs, and update all beta samples to use sortOrderIndex as a string.

**Comment by tony-xia** [comment]
@nkramer thanks for your feedback. I will update this PR.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[94a7154](https://github.com/tony-xia/microsoft-graph-docs/pull/3576/commits/94a715472b117ed6864af28f58706fff879259b3)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[94a7154](https://github.com/tony-xia/microsoft-graph-docs/pull/3576/commits/94a715472b117ed6864af28f58706fff879259b3)_: 

### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/microsoftgraph/microsoft-graph-docs, working directory: W:\yjag-s, target branch: master, target branch commit: 28113a56d65a05fd8b742523736e10c09af64cd6, source branch: 9c2f6d793283644db9ffdccabb6d170f/sortOrderIndex-type, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901201137568560-3576%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=sCKW1wn47QDW2B4txlxt7BQRLI6Yi%2FPY1FoU2nq%2B1ug%3D&st=2019-01-20T11%3A33%3A54Z&se=2019-02-20T11%3A38%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by tony-xia** [comment]
@nkramer @Lauragra I raised a new PR for the fix. Please review it. thanks
https://github.com/microsoftgraph/microsoft-graph-docs/pull/3827

I am going to close this one.

**Pull request closed without merging**
