### PR TITLE
Update education-concept-overview.md

### PR DESCRIPTION
**Pull request by mmast-msft**
Changed hardcoded links to relative to resolve breaks.

### CODE REVIEW

**Comment by jthake-msft** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-concept-overview.md](https://github.com/mmast-msft/microsoft-graph-docs/blob/patch-1/concepts/education-concept-overview.md) | :warning:Warning | | [Details](#user-content-concepts%2Feducation-concept-overview.md)

<a name="concepts%2Feducation-concept-overview.md"></a>
### [concepts/education-concept-overview.md](https://github.com/mmast-msft/microsoft-graph-docs/blob/patch-1/concepts/education-concept-overview.md)
 - **Line 17**: **[Warning]** Invalid file link:(~/../api-reference/v1.0/api/educationschool_list_classes).
 - **Line 18**: **[Warning]** Invalid file link:(~/../api-reference/v1.0/api/educationclass_list_members).
 - **Line 19**: **[Warning]** Invalid file link:(~/../api-reference/v1.0/api/educationuser_list_classes).
 - **Line 27**: **[Warning]** Invalid file link:(~/../../../microsoftteams/platform/concepts/apps/apps-overview).
 - **Line 39**: **[Warning]** Invalid file link:(~/../api-reference/beta/api/educationclass_post_assignments).
 - **Line 40**: **[Warning]** Invalid file link:(~/../api-reference/beta/api/educationsubmission_update).
 - **Line 41**: **[Warning]** Invalid file link:(~/../api-reference/beta/api/educationclass_list_assignments).
 - **Line 46**: **[Warning]** Invalid file link:(~/../api-reference/beta/resources/educationsynchronizationprofile).
 - **Line 50**: **[Warning]** Invalid file link:(~/../api-reference/beta/api/educationsynchronizationprofile_post).
 - **Line 51**: **[Warning]** Invalid file link:(~/../api-reference/beta/api/educationsynchronizationprofile_resume).
 - **Line 51**: **[Warning]** Invalid file link:(~/../api-reference/beta/api/educationsynchronizationprofile_pause).
 - **Line 51**: **[Warning]** Invalid file link:(~/../api-reference/beta/api/educationsynchronizationprofile_reset).
 - **Line 56**: **[Warning]** Invalid file link:(~/../api-reference/v1.0/resources/education-overview.md).
 - **Line 57**: **[Warning]** Invalid file link:(~/../api-reference/beta/resources/education-overview.md).
 - **Line 63**: **[Warning]** Invalid file link:(~/../api-reference/v1.0/resources/education-overview).
 - **Line 64**: **[Warning]** Invalid file link:(~/../api-reference/beta/resources/educationassignment).
 - **Line 65**: **[Warning]** Invalid file link:(~/../api-reference/beta/resources/educationsynchronizationprofile).
 - **Line 66**: **[Warning]** Invalid file link:(~/../../graph-explorer).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201811201801424566-3438%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=CcLpr7niZP95gZ%2BaPjyv%2Fs38fVLHM5eDslcf%2BFjEcSM%3D&st=2018-11-20T17%3A59%3A44Z&se=2018-12-21T18%3A04%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-concept-overview.md](https://github.com/mmast-msft/microsoft-graph-docs/blob/patch-1/concepts/education-concept-overview.md) | :warning:Warning | | [Details](#user-content-concepts%2Feducation-concept-overview.md)

<a name="concepts%2Feducation-concept-overview.md"></a>
### [concepts/education-concept-overview.md](https://github.com/mmast-msft/microsoft-graph-docs/blob/patch-1/concepts/education-concept-overview.md)
 - **Line 17**: **[Warning]** Invalid file link:(~/../api-reference/v1.0/api/educationschool_list_classes).
 - **Line 18**: **[Warning]** Invalid file link:(~/../api-reference/v1.0/api/educationclass_list_members).
 - **Line 19**: **[Warning]** Invalid file link:(~/../api-reference/v1.0/api/educationuser_list_classes).
 - **Line 27**: **[Warning]** Invalid file link:(~/../../../microsoftteams/platform/concepts/apps/apps-overview).
 - **Line 39**: **[Warning]** Invalid file link:(~/../api-reference/beta/api/educationclass_post_assignments).
 - **Line 40**: **[Warning]** Invalid file link:(~/../api-reference/beta/api/educationsubmission_update).
 - **Line 41**: **[Warning]** Invalid file link:(~/../api-reference/beta/api/educationclass_list_assignments).
 - **Line 46**: **[Warning]** Invalid file link:(~/../api-reference/beta/resources/educationsynchronizationprofile).
 - **Line 50**: **[Warning]** Invalid file link:(~/../api-reference/beta/api/educationsynchronizationprofile_post).
 - **Line 51**: **[Warning]** Invalid file link:(~/../api-reference/beta/api/educationsynchronizationprofile_resume).
 - **Line 51**: **[Warning]** Invalid file link:(~/../api-reference/beta/api/educationsynchronizationprofile_pause).
 - **Line 51**: **[Warning]** Invalid file link:(~/../api-reference/beta/api/educationsynchronizationprofile_reset).
 - **Line 56**: **[Warning]** Invalid file link:(~/../api-reference/v1.0/resources/education-overview.md).
 - **Line 57**: **[Warning]** Invalid file link:(~/../api-reference/beta/resources/education-overview.md).
 - **Line 63**: **[Warning]** Invalid file link:(~/../api-reference/v1.0/resources/education-overview).
 - **Line 64**: **[Warning]** Invalid file link:(~/../api-reference/beta/resources/educationassignment).
 - **Line 65**: **[Warning]** Invalid file link:(~/../api-reference/beta/resources/educationsynchronizationprofile).
 - **Line 66**: **[Warning]** Invalid file link:(~/../../graph-explorer).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201811211549356014-3438%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=xQ8zmaVUyak3VTcdv9H4H9bHR15flzFra%2FNqHFj61Sk%3D&st=2018-11-21T15%3A47%3A17Z&se=2018-12-22T15%3A52%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-concept-overview.md](https://github.com/mmast-msft/microsoft-graph-docs/blob/patch-1/concepts/education-concept-overview.md) | :warning:Warning | | [Details](#user-content-concepts%2Feducation-concept-overview.md)

<a name="concepts%2Feducation-concept-overview.md"></a>
### [concepts/education-concept-overview.md](https://github.com/mmast-msft/microsoft-graph-docs/blob/patch-1/concepts/education-concept-overview.md)
 - **Line 17**: **[Warning]** Invalid file link:(~/../api-reference/v1.0/api/educationschool_list_classes.md).
 - **Line 18**: **[Warning]** Invalid file link:(~/../api-reference/v1.0/api/educationclass_list_members.md).
 - **Line 19**: **[Warning]** Invalid file link:(~/../api-reference/v1.0/api/educationuser_list_classes.md).
 - **Line 39**: **[Warning]** Invalid file link:(~/../api-reference/beta/api/educationclass_post_assignments.md).
 - **Line 40**: **[Warning]** Invalid file link:(~/../api-reference/beta/api/educationsubmission_update.md).
 - **Line 41**: **[Warning]** Invalid file link:(~/../api-reference/beta/api/educationclass_list_assignments.md).
 - **Line 46**: **[Warning]** Invalid file link:(~/../api-reference/beta/resources/educationsynchronizationprofile.md).
 - **Line 50**: **[Warning]** Invalid file link:(~/../api-reference/beta/api/educationsynchronizationprofile_post.md).
 - **Line 51**: **[Warning]** Invalid file link:(~/../api-reference/beta/api/educationsynchronizationprofile_reset.md).
 - **Line 51**: **[Warning]** Invalid file link:(~/../api-reference/beta/api/educationsynchronizationprofile_resume.md).
 - **Line 51**: **[Warning]** Invalid file link:(~/../api-reference/beta/api/educationsynchronizationprofile_pause.md).
 - **Line 56**: **[Warning]** Invalid file link:(~/../api-reference/v1.0/resources/education-overview.md).
 - **Line 57**: **[Warning]** Invalid file link:(~/../api-reference/beta/resources/education-overview.md).
 - **Line 63**: **[Warning]** Invalid file link:(~/../api-reference/v1.0/resources/education-overview.md).
 - **Line 64**: **[Warning]** Invalid file link:(~/../api-reference/beta/resources/educationassignment.md).
 - **Line 65**: **[Warning]** Invalid file link:(~/../api-reference/beta/resources/educationsynchronizationprofile.md).
 - **Line 66**: **[Warning]** Invalid file link:(~/../../graph-explorer).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201811211553217014-3438%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=KJBL1LcE8%2BAoV8mnL1v2J27AS4MAtAcjbwGl%2BWuneZ4%3D&st=2018-11-21T15%3A51%3A10Z&se=2018-12-22T15%3A56%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-concept-overview.md](https://github.com/mmast-msft/microsoft-graph-docs/blob/patch-1/concepts/education-concept-overview.md) | :warning:Warning | | [Details](#user-content-concepts%2Feducation-concept-overview.md)

<a name="concepts%2Feducation-concept-overview.md"></a>
### [concepts/education-concept-overview.md](https://github.com/mmast-msft/microsoft-graph-docs/blob/patch-1/concepts/education-concept-overview.md)
 - **Line 17**: **[Warning]** Invalid file link:(~/../api-reference/v1.0/api/educationschool_list_classes.md).
 - **Line 18**: **[Warning]** Invalid file link:(~/../api-reference/v1.0/api/educationclass_list_members.md).
 - **Line 19**: **[Warning]** Invalid file link:(~/../api-reference/v1.0/api/educationuser_list_classes.md).
 - **Line 39**: **[Warning]** Invalid file link:(~/../api-reference/beta/api/educationclass_post_assignments.md).
 - **Line 40**: **[Warning]** Invalid file link:(~/../api-reference/beta/api/educationsubmission_update.md).
 - **Line 41**: **[Warning]** Invalid file link:(~/../api-reference/beta/api/educationclass_list_assignments.md).
 - **Line 46**: **[Warning]** Invalid file link:(~/../api-reference/beta/resources/educationsynchronizationprofile.md).
 - **Line 50**: **[Warning]** Invalid file link:(~/../api-reference/beta/api/educationsynchronizationprofile_post.md).
 - **Line 51**: **[Warning]** Invalid file link:(~/../api-reference/beta/api/educationsynchronizationprofile_reset.md).
 - **Line 51**: **[Warning]** Invalid file link:(~/../api-reference/beta/api/educationsynchronizationprofile_resume.md).
 - **Line 51**: **[Warning]** Invalid file link:(~/../api-reference/beta/api/educationsynchronizationprofile_pause.md).
 - **Line 56**: **[Warning]** Invalid file link:(~/../api-reference/v1.0/resources/education-overview.md).
 - **Line 57**: **[Warning]** Invalid file link:(~/../api-reference/beta/resources/education-overview.md).
 - **Line 63**: **[Warning]** Invalid file link:(~/../api-reference/v1.0/resources/education-overview.md).
 - **Line 64**: **[Warning]** Invalid file link:(~/../api-reference/beta/resources/educationassignment.md).
 - **Line 65**: **[Warning]** Invalid file link:(~/../api-reference/beta/resources/educationsynchronizationprofile.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201811211601272840-3438%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=vNg5EEzwE%2BRkjt4TVDXWQfHK%2BtCzS2R3hEhOXI70SAo%3D&st=2018-11-21T15%3A59%3A04Z&se=2018-12-22T16%3A04%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mmast-msft** [comment]
Made requested changes:
.md extension added to relative links.   Teams link reverted.

**Pull request merged**
