### PR TITLE
Add a call-out for not relying on ordering

### PR DESCRIPTION
**Pull request by psibernetic**
This PR clarifies ordering in Delta queries in two ways. 

First, it notes that $orderby is not a supported OData query parameter, this is assumed since no documentation lists it as supported on any Delta query page.

Secondly, it notes that the sequence of events should not be relied upon. This was informed from the related page on [groups delta queries](https://docs.microsoft.com/en-us/graph/delta-query-groups#paging-through-members-in-a-large-group). 

Excerpt under best practices:
> It is best not to assume a specific sequence of the responses. Assume that the same group could show up anywhere in the nextLink sequence and handle that in your merge logic.

Related to #3652

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[7a912c6](https://github.com/psibernetic/microsoft-graph-docs/pull/3690/commits/7a912c6164c802d15e658eb39e5053ae9708f630)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 20 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[7a912c6](https://github.com/psibernetic/microsoft-graph-docs/pull/3690/commits/7a912c6164c802d15e658eb39e5053ae9708f630)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[3ed558d](https://github.com/psibernetic/microsoft-graph-docs/pull/3690/commits/3ed558dfd328e5c00e834f530827c1961143d5fd)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 20 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[3ed558d](https://github.com/psibernetic/microsoft-graph-docs/pull/3690/commits/3ed558dfd328e5c00e834f530827c1961143d5fd)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[3ed558d](https://github.com/psibernetic/microsoft-graph-docs/pull/3690/commits/3ed558dfd328e5c00e834f530827c1961143d5fd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/delta-query-overview.md](https://github.com/psibernetic/microsoft-graph-docs/blob/patch-1/concepts/delta-query-overview.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901071931362926-3690%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=gn%2BeXP%2Bddwui5X5hKHDNr5l%2BswX6Yecj4YDSDyZ5NCQ%3D&st=2019-01-07T19%3A30%3A24Z&se=2019-02-07T19%3A35%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
@piotrci , are we ready to merge this PR? Thanks.

**Comment by Lauragra** [comment]
Created PR #5204 to merge this update.

**Pull request closed without merging**
