### PR TITLE
fix or remove broken links through changelog/Microsoft.Intune.json: L…

### PR DESCRIPTION
**Pull request by dodaromike**
This work is only half done, now through changelog/Microsoft.Intune.json: Line(s) 382, but I am assigned PR reviews, so I'd like to get these broken links removed or repaired and continue later with remaining broken links.

### CODE REVIEW

**Comment by Lauragra** [comment]
@dodaromike , ignoring Intune for a moment, can you fix up the link errors mentioned in the other files in the PR? Thanks.

**Comment by dodaromike** [comment]
@Lauragra Without InTune the list is very manageable.  I can finish it off tomorrow.

**Comment by Lauragra** [comment]
> @Lauragra Without InTune the list is very manageable. I can finish it off tomorrow.

Thanks! I'm asking Jaiprakash if he can help with the Intune links.

**Comment by dodaromike** [comment]
@Lauragra ChangeLog shows all but InTune are links fixed.  Ready for another review.

**Comment by Lauragra** [comment]
> @Lauragra ChangeLog shows all but InTune are links fixed. Ready for another review. I can't find the Re-request icon.



> @Lauragra ChangeLog shows all but InTune are links fixed. Ready for another review. I can't find the Re-request icon.

@dodaromike , all else looks good. How are we handling the Intune file? @jaiprakashmb , FYI, this PR is starting to make fixes to the broken links in the Intune file; do you want us to proceed or will you fix on your end?

**Pull request merged**
