### PR TITLE
Update group-list-threads.md

### PR DESCRIPTION
**Pull request by ArunMSFT**
Update API response with right default fields

### CODE REVIEW

**Comment by Lauragra** [comment]
@ArunMSFT , please update the beta topic as well. Thanks.

**Comment by ArunMSFT** [comment]
> @ArunMSFT , please update the beta topic as well. Thanks.

@Lauragra Sure, will update and resubmit. Otherwise are these updates good.

**Comment by ArunMSFT** [comment]
Updated both beta and v1

**Review by Lauragra — APPROVED** [review]

**Comment by Lauragra** [comment]
@ArunMSFT , do you want to publish this PR? If so, please remove the Draft status. Thanks.

**Comment by jasonjoh** [comment]
Docs Build status updates of commit _[924793c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/924793c29da8f511a2029dc5c93671bf0b6b884a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-threads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArunMSFT-patch-3/api-reference/v1.0/api/group-list-threads.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-threads?view=graph-rest-1.0&branch=pr-en-us-13582) (>= graph-rest-1.0) | [Details](#user-content-4b20a82443f4d816181c2706d9e0fc50-084b7c85)
[api-reference/beta/api/group-list-threads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArunMSFT-patch-3/api-reference/beta/api/group-list-threads.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-threads?view=graph-rest-beta&branch=pr-en-us-13582) (graph-rest-beta) |

<a id="4b20a82443f4d816181c2706d9e0fc50-084b7c85"></a>
### [api-reference/v1.0/api/group-list-threads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArunMSFT-patch-3/api-reference/v1.0/api/group-list-threads.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List threads - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/conversation-list-threads.md(2,8), v1.0/api/group-list-threads.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List threads' is duplicated with other articles: 'v1.0/api/conversation-list-threads.md(10,1), v1.0/api/group-list-threads.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109011122269349-13582%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=m5XKg4AvBLyJlfPCIW2KhqzSBOi0DJnDt7lnWUVA6fk%3D&st=2021-09-01T11%3A21%3A22Z&se=2021-10-02T11%3A26%3A22Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by isvargasmsft** [comment]
@ArunMSFT could you please share the status of this PR? If you want to merge it, would you be so kind to remove the Draft status, please?

**Pull request merged**
