### PR TITLE
Update group-post-owners.md

### PR DESCRIPTION
**Pull request by developermessaging**

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[60e3767](https://github.com/developermessaging/microsoft-graph-docs/pull/3649/commits/60e3767406ea8fa902220f476f105b18c9d895d6)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 19 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[60e3767](https://github.com/developermessaging/microsoft-graph-docs/pull/3649/commits/60e3767406ea8fa902220f476f105b18c9d895d6)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[60e3767](https://github.com/developermessaging/microsoft-graph-docs/pull/3649/commits/60e3767406ea8fa902220f476f105b18c9d895d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-post-owners.md](https://github.com/developermessaging/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/api/group-post-owners.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201812171539318175-3649%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=pIWcH%2FAsI8rpscaVm%2FXhuneEH6z7l9khn4je84dqL%2Fk%3D&st=2018-12-17T15%3A38%3A24Z&se=2019-01-17T15%3A43%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[585425a](https://github.com/developermessaging/microsoft-graph-docs/pull/3649/commits/585425a70e0d48fcf47e9c714063dde7e51f6230)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 20 sec(s)_

**Comment by Lauragra** [comment]
@developermessaging , please make the same update to the beta version of this topic. Thanks.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[585425a](https://github.com/developermessaging/microsoft-graph-docs/pull/3649/commits/585425a70e0d48fcf47e9c714063dde7e51f6230)_: 

:clock10: **Full build**: average full build time is _7 min(s) 40 sec(s)_ [calculated from last _31_ build(s)]

> Note: A full build takes more time than an incremental build.  This is the expected behavior of the build system.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[585425a](https://github.com/developermessaging/microsoft-graph-docs/pull/3649/commits/585425a70e0d48fcf47e9c714063dde7e51f6230)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-post-owners.md](https://github.com/developermessaging/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/api/group-post-owners.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201812171901382759-3649%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=9%2FpazvicQvtmcbc%2FXhcH%2F6D1MjJKkQ3tC4Mw1pybzCI%3D&st=2018-12-17T19%3A06%3A24Z&se=2019-01-17T19%3A11%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[15d56a3](https://github.com/developermessaging/microsoft-graph-docs/pull/3649/commits/15d56a3e2399b32d749615cc5c4baab1c80822ca)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 20 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[15d56a3](https://github.com/developermessaging/microsoft-graph-docs/pull/3649/commits/15d56a3e2399b32d749615cc5c4baab1c80822ca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-post-owners.md](https://github.com/developermessaging/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/api/group-post-owners.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201812180021468007-3649%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=eK%2F1%2FRQineP4EbNCtAn1vtHfLggcFwoG2JtGFA8xTns%3D&st=2018-12-18T00%3A27%3A22Z&se=2019-01-18T00%3A32%3A22Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[2096cf8](https://github.com/developermessaging/microsoft-graph-docs/pull/3649/commits/2096cf8045ee043eec5bc1613f484f82baca588e)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 20 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[2096cf8](https://github.com/developermessaging/microsoft-graph-docs/pull/3649/commits/2096cf8045ee043eec5bc1613f484f82baca588e)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[2096cf8](https://github.com/developermessaging/microsoft-graph-docs/pull/3649/commits/2096cf8045ee043eec5bc1613f484f82baca588e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-post-owners.md](https://github.com/developermessaging/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/api/group-post-owners.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201812180033447522-3649%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=GiR2VhA4DeL6WpG%2FjTLBGr5QR6uMObEuvEao8Qvod2c%3D&st=2018-12-18T00%3A32%3A16Z&se=2019-01-18T00%3A37%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
