### PR TITLE
Typo in documentation of microsoft.graph.objectIdentity

### PR DESCRIPTION
**Pull request by alexismeneses**
Seems there's a typo in the results of MS GRAPH API v1.0.
I think that the doc should reflect that typo in accordance.

Identities are returned with a `signInType` starting with `emailAdress` (one 'd') and not `emailAddress` (double 'd').

Anonymized example of API below

    "identities": [
        {
            "signInType": "emailAdress1",
            "issuer": "contoso.onmicrosoft.com",
            "issuerAssignedId": "john.doe@other-domain.com"
        },
        {
            "signInType": "emailAdress",
            "issuer": "contoso.onmicrosoft.com",
            "issuerAssignedId": "john.doe@domain.com"
        },
        {
            "signInType": "userPrincipalName",
            "issuer": "contoso.onmicrosoft.com",
            "issuerAssignedId": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeee4@contoso.onmicrosoft.com"
        }
    ]

### CODE REVIEW

**Comment by Lauragra** [comment]
@jpettere , can you please follow up? @alexismeneses , thanks for submitting the fix. Let's see if we can follow up on the typo before we update the docs; either way it can be misleading to users.

**Comment by FaithOmbongi** [comment]
Thank you @alexismeneses for your PR. Seems that you specified the value for **signInType** to `emailAdress`/`emailAdress1` in during your create/update process. The value of **signInType** property can be set to a custom string so you can call it _almost_ anything.

No updates required for the page.

**Comment by alexismeneses** [comment]
Good spot @FaithOmbongi. Really thought it was built-in values. Turns out a typo in our code. Really sorry for the inconvenience.

**Comment by FaithOmbongi** [comment]
It's not a problem @alexismeneses. We welcome your contributions anytime.

**Pull request closed without merging**
