### PR TITLE
new groups permissions scopes

### PR DESCRIPTION
**Pull request by krbain**

### CODE REVIEW

**Comment by krbain** [comment]
#hold-off

**Comment by Lauragra** [comment]
@krbain , what is the merge status of this PR? Does this permissions update warrant a changelog entry?

**Comment by Jackson-Woods** [comment]
These permissions are now live in PROD and available via the Azure portal. Please let me know how I can help advance the PR so that documentation is available as soon as possible.

**Comment by dkershaw10** [comment]
I'm ready to sign-off but  I think this still needs a changelog entry (and probably warrants a blog post).
I fixed the merge conflict for the permissions topic

**Comment by krbain** [comment]
#sign-off

**Comment by krbain** [comment]
@Lauragra can you please help get this merged?

**Pull request merged**
