### PR TITLE
Changes User.ReadBasic.All

### PR DESCRIPTION
**Pull request by dodaromike**
Remove User.ReadBasic.All permission from Application rows.

### CODE REVIEW

**Comment by Lauragra** [comment]
@dodaromike , I'll merge this PR; I assume you have a follow up PR coming to make the fixes in v1.0? Thanks.

**Comment by darrelmiller** [comment]
Why are these permissions being removed?  I have customers telling me that they are currently using these permissions?

**Comment by dodaromike** [comment]
@darrelmiller Here is the correspondence that led to this change.  I'll forward the email thread to you.

Hi MS graph doc experts,
 
We recently discovered a security vulnerability in the new user application permission User.ReadBasic.All. In order not to break existing apps that have configured this permission, we decided to hide it from external 3rd party apps. The permission is already hidden, and customers can't find it from Azure portal. 
 
I worked with Faith to remove it from the Permission page: [https://learn.microsoft.com/en-us/graph/permissions-reference#user-permissions](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fgraph%2Fpermissions-reference%23user-permissions&data=05%7C01%7Cv-dodaromike%40microsoft.com%7Cfc39c397c19c4cacd9c508db1e8b6778%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638137356324919974%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=v28hFFKYz3ryCzbVmkoBJPEQ9Mgjas3K1zhah2sOfYs%3D&reserved=0). However, Faith let me know that there are more than 50 instances of the User.ReadBasic.All application permissions in the API reference docs.

**Comment by onitake** [comment]
If you haven't already, you should also make sure this change appears in the changelog: https://developer.microsoft.com/en-us/graph/changelog/?search=user.readbasic

**Pull request merged**
