### PR TITLE
Update instance annotation

### PR DESCRIPTION
**Pull request by BarryShehadeh**
Update Bundles conflictBehavior instance annotation from OneDrive's one to the graph's one.

### CODE REVIEW

**Comment by Lauragra** [comment]
Yes, they're autogenerated. @darrelmiller , @andrueastman , can you please review?

**Comment by Lauragra** [comment]
@BarryShehadeh , can you please remove the updates to the snippet files from this PR? When we merge the updates to the examples, the snippet generation process should pick up the changes - right @andrueastman ?

**Comment by andrueastman** [comment]
@Lauragra That is correct

**Comment by Lauragra** [comment]
Thanks. @BarryShehadeh , please remove the snippet updates from your PR so we can get this one merged in.

**Comment by BarryShehadeh** [comment]
@Lauragra Should be good.

**Pull request merged**
