### PR TITLE
Update per PR #1826.

### PR DESCRIPTION
**Pull request by Lauragra**

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[be091bb](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3870/commits/be091bb959f2491ea97c300b9225787688c70169)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

**Comment by Lauragra** [comment]
@kevklam , @JeremyKelley , is this still a known issue? If so, please approve.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[be091bb](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3870/commits/be091bb959f2491ea97c300b9225787688c70169)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 56 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[be091bb](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3870/commits/be091bb959f2491ea97c300b9225787688c70169)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lauragra-pr1826/concepts/known-issues.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901261645563680-3870%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=KCTnLVqyLXTOz4XKbpbUw1EpnFDrCmL78CmqqOVQVdM%3D&st=2019-01-26T16%3A44%3A19Z&se=2019-02-26T16%3A49%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
@JeremyKelley , is this still a known issue?

**Comment by kking1991** [comment]
Is this getting fixed soon? Has this change affected the max file size limit of the copy request?

**Comment by Lauragra** [comment]
@JeremyKelley can you please review this PR? Otherwise I will close if no response. Thanks.

**Comment by Lauragra** [comment]
Closing because this hasn't been reviewed/signed off.

**Pull request closed without merging**
