### PR TITLE
Update user-list.md

### PR DESCRIPTION
**Pull request by rrperkin**
Add text "The `$count` and `$search` parameters are currently not available in Azure AD B2C tenants" in examples. See https://github.com/microsoftgraph/microsoft-graph-docs/issues/15067

### CODE REVIEW

**Comment by rrperkin** [comment]
https://github.com/microsoftgraph/microsoft-graph-docs/issues/15067

**Comment by Lauragra** [comment]
@rrperkin , do we need to make the same update to the version of the file in the /beta folder? @FaithOmbongi , FYI, please verify.

**Comment by rrperkin** [comment]
Probably, yeah. The results were the same on the beta endpoint but I only sent a PR for 1.0

Rob

**Review by FaithOmbongi — APPROVED** [review]
Thanks, @rrperkin for raising this PR. I've pushed a minor commit to change the note format.

If you wish to, you can also make the same changes to the beta version of this doc.

**Pull request merged**
