### PR TITLE
[Ready to merge] Promote 'socketio' from beta to v1.0

### PR DESCRIPTION
**Pull request by kevklam**

### CODE REVIEW

**Comment by kevklam** [comment]
Expected go-live is next Wednesday assuming the rest of the publishing process goes smoothly

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[0ceb164](https://github.com/kevklam/microsoft-graph-docs/pull/4158/commits/0ceb16426b2fe1f6e8e6dd17e762faa174e4c020)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/driveitem.md](https://github.com/kevklam/microsoft-graph-docs/blob/kevinlam-socketio/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/driveItem-subscriptions-socketio.md](https://github.com/kevklam/microsoft-graph-docs/blob/kevinlam-socketio/api-reference/v1.0/api/driveItem-subscriptions-socketio.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/driveitem.md](https://github.com/kevklam/microsoft-graph-docs/blob/kevinlam-socketio/api-reference/v1.0/resources/driveitem.md) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/kevklam/microsoft-graph-docs/blob/kevinlam-socketio/concepts/changelog.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903132147292196-4158%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=jN%2Fs8dS8m0Sx%2BsI%2BoTMZ6DSUWuYJ9p%2BB%2BdJJSiYoYqQ%3D&st=2019-03-13T21%3A46%3A46Z&se=2019-04-13T21%3A51%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
@kevklam , please add the "do not merge" or "ready to merge" label to this PR as appropriate. Let me know if you have a timeline for publishing live.

**Comment by kevklam** [comment]
Expecting to be published next Wednesday, will update the label when appropriate. Thanks!

**Comment by kevklam** [comment]
@Lauragra This is now live :)

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[c723282](https://github.com/kevklam/microsoft-graph-docs/pull/4158/commits/c723282b8dbff13733a990f2fed4b76b8ca80f0e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/driveitem.md](https://github.com/kevklam/microsoft-graph-docs/blob/kevinlam-socketio/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/driveItem-subscriptions-socketio.md](https://github.com/kevklam/microsoft-graph-docs/blob/kevinlam-socketio/api-reference/v1.0/api/driveItem-subscriptions-socketio.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/driveitem.md](https://github.com/kevklam/microsoft-graph-docs/blob/kevinlam-socketio/api-reference/v1.0/resources/driveitem.md) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/kevklam/microsoft-graph-docs/blob/kevinlam-socketio/concepts/changelog.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903220044201788-4158%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=nsgOZamQGPLoCdPIylZDMr6kly5GCjWSAgZI8DxThIo%3D&st=2019-03-22T00%3A43%3A38Z&se=2019-04-22T00%3A48%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
@kevklam , can you look into the API Doctor error?

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[6e5219e](https://github.com/kevklam/microsoft-graph-docs/pull/4158/commits/6e5219e600b00e196821a71b2be36fd93b8e45d3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/driveitem.md](https://github.com/kevklam/microsoft-graph-docs/blob/kevinlam-socketio/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/driveItem-subscriptions-socketio.md](https://github.com/kevklam/microsoft-graph-docs/blob/kevinlam-socketio/api-reference/v1.0/api/driveItem-subscriptions-socketio.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/driveitem.md](https://github.com/kevklam/microsoft-graph-docs/blob/kevinlam-socketio/api-reference/v1.0/resources/driveitem.md) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/kevklam/microsoft-graph-docs/blob/kevinlam-socketio/concepts/changelog.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903220057119158-4158%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=abSfzcNvksaHhDJPhcBangC%2F1WWaMb%2BYV%2BWbNBotIhg%3D&st=2019-03-22T00%3A56%3A07Z&se=2019-04-22T01%3A01%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[4e295bf](https://github.com/kevklam/microsoft-graph-docs/pull/4158/commits/4e295bf03f348c63b345451439b68fa53ce2f370)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/driveitem.md](https://github.com/kevklam/microsoft-graph-docs/blob/kevinlam-socketio/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/driveItem-subscriptions-socketio.md](https://github.com/kevklam/microsoft-graph-docs/blob/kevinlam-socketio/api-reference/v1.0/api/driveItem-subscriptions-socketio.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/driveitem.md](https://github.com/kevklam/microsoft-graph-docs/blob/kevinlam-socketio/api-reference/v1.0/resources/driveitem.md) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/kevklam/microsoft-graph-docs/blob/kevinlam-socketio/concepts/changelog.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903220114001162-4158%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=x8bXWgop%2B6Ccv8a84ONGhbDcSI7I400XWkRs1llY7TI%3D&st=2019-03-22T01%3A12%3A57Z&se=2019-04-22T01%3A17%3A57Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
