### PR TITLE
Create include file for intro text to property table in update topics

### PR DESCRIPTION
**Pull request by jasonjoh**

### CODE REVIEW

**Comment by jasonjoh** [comment]
Docs Build status updates of commit _[3906107](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3906107a961163e4ea103cbe7857a7d5d5a22d2f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-update-property-table-intro/api-reference/v1.0/api/event-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&branch=pr-en-us-14123) (>= graph-rest-1.0) | [Details](#user-content-6758276e5586e129e1f8b6cb63cd1969-05a7275d)
[api-reference/includes/update-property-table-intro.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-update-property-table-intro/api-reference/includes/update-property-table-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&branch=pr-en-us-14123) (>= graph-rest-1.0) |

<a id="6758276e5586e129e1f8b6cb63cd1969-05a7275d"></a>
### [api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-update-property-table-intro/api-reference/v1.0/api/event-update.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-update.md(2,8), v1.0/api/group-update-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update event' is duplicated with other articles: 'v1.0/api/event-update.md(10,1), v1.0/api/group-update-event.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109021907354521-14123%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=HSKbqN2CHGSM5bMjlAIqZIUNT0JKmz%2BC7xy7G72NXv8%3D&st=2021-09-02T19%3A05%3A40Z&se=2021-10-03T19%3A10%3A40Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by jasonjoh** [comment]
Docs Build status updates of commit _[f4eb9bf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f4eb9bf6aa90fb4046c70400a496390bc5f26479)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-update-property-table-intro/api-reference/v1.0/api/event-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&branch=pr-en-us-14123) (>= graph-rest-1.0) | [Details](#user-content-6758276e5586e129e1f8b6cb63cd1969-9260b05a)
[api-reference/includes/update-property-table-intro.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-update-property-table-intro/api-reference/includes/update-property-table-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&branch=pr-en-us-14123) (>= graph-rest-1.0) |

<a id="6758276e5586e129e1f8b6cb63cd1969-9260b05a"></a>
### [api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-update-property-table-intro/api-reference/v1.0/api/event-update.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-update.md(2,8), v1.0/api/group-update-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update event' is duplicated with other articles: 'v1.0/api/event-update.md(10,1), v1.0/api/group-update-event.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109021925156905-14123%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=Q3Iif2hF6c%2B5jwk9MUpPl8ou2buv9P8xjeXoctq1ZLA%3D&st=2021-09-02T19%3A21%3A53Z&se=2021-10-03T19%3A26%3A53Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by jasonjoh** [comment]
Docs Build status updates of commit _[60505ce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/60505cee8408630fa25a980347ad1a4e15043480)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-update-property-table-intro/api-reference/v1.0/api/event-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&branch=pr-en-us-14123) (>= graph-rest-1.0) | [Details](#user-content-6758276e5586e129e1f8b6cb63cd1969-4ea19a6d)
[api-reference/includes/update-property-table-intro.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-update-property-table-intro/api-reference/includes/update-property-table-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&branch=pr-en-us-14123) (>= graph-rest-1.0) |

<a id="6758276e5586e129e1f8b6cb63cd1969-4ea19a6d"></a>
### [api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-update-property-table-intro/api-reference/v1.0/api/event-update.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-update.md(2,8), v1.0/api/group-update-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update event' is duplicated with other articles: 'v1.0/api/event-update.md(10,1), v1.0/api/group-update-event.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109021930335582-14123%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=kRNQw%2Bdh8nDOSt3Xs9f%2FV7Y8mTc%2B4IrX5k69gmk1Qwg%3D&st=2021-09-02T19%3A27%3A11Z&se=2021-10-03T19%3A32%3A11Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by jasonjoh** [comment]
Docs Build status updates of commit _[3aa7bd8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3aa7bd8fe5d20ca37ab7082c93ecfb9f44484004)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-update-property-table-intro/api-reference/v1.0/api/event-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&branch=pr-en-us-14123) (>= graph-rest-1.0) | [Details](#user-content-6758276e5586e129e1f8b6cb63cd1969-c93f6d5d)
[api-reference/includes/update-property-table-intro.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-update-property-table-intro/api-reference/includes/update-property-table-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&branch=pr-en-us-14123) (>= graph-rest-1.0) |

<a id="6758276e5586e129e1f8b6cb63cd1969-c93f6d5d"></a>
### [api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-update-property-table-intro/api-reference/v1.0/api/event-update.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-update.md(2,8), v1.0/api/group-update-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update event' is duplicated with other articles: 'v1.0/api/event-update.md(10,1), v1.0/api/group-update-event.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109021936206584-14123%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=2qaFXT4jdxMNMz5uGADlvVnkizQLPBo8s4SuNykFhEY%3D&st=2021-09-02T19%3A33%3A56Z&se=2021-10-03T19%3A38%3A56Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by angelgolfer-ms — COMMENTED** [review]
@jasonjoh , the boilerplate and its incorporation look good to me. Thanks. Please merge when you're ready.

**Pull request merged**
