### PR TITLE
Adding note for non-gallery creation

### PR DESCRIPTION
**Pull request by luleonpla**

### CODE REVIEW

**Comment by luleonpla** [comment]
#sign-off

**Comment by Lauragra** [comment]
@luleonpla , are you ready to merge this PR? We go by PR labels rather than #sign-off.

**Comment by luleonpla** [comment]
#sign-off

**Comment by luleonpla** [comment]
@Lauragra we're ready to merge this. If you have doc on how I can let you know next time when a PR is ready, please share. I don't see a way to add a label or what label to add.

**Comment by Lauragra** [comment]
> @Lauragra we're ready to merge this. If you have doc on how I can let you know next time when a PR is ready, please share. I don't see a way to add a label or what label to add.

@luleonpla , we set the Ready to merge label to notify that a PR is ready to publish. If you don't have access to set labels, please make sure that you follow the Get started steps here to be added as a contributor: https://msgo.azurewebsites.net/add/document/manage-content/get-started-with-github.html#get-started-steps.

**Pull request merged**
