### PR TITLE
Updates per PR #2818

### PR DESCRIPTION
**Pull request by Lauragra**

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[1ecc114](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3906/commits/1ecc114c4687d49d5276ecaf0734d44ba72c1f9e)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 23 sec(s)_

**Comment by Lauragra** [comment]
@Jackson-Woods , do we want to go ahead and merge in this change?

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[1ecc114](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3906/commits/1ecc114c4687d49d5276ecaf0734d44ba72c1f9e)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 57 sec(s)_

**Comment by Jackson-Woods** [comment]
@Lauragra Yes, let's go ahead and merge this.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[1ecc114](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3906/commits/1ecc114c4687d49d5276ecaf0734d44ba72c1f9e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lauragra-pr2818/api-reference/beta/api/driveitem-delta.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/driveitem-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lauragra-pr2818/api-reference/v1.0/api/driveitem-delta.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902012252273257-3906%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=lIy%2BT0n9v2EZkNg5tmVoG9pfz%2Fk7xgqvMolTim0wUjY%3D&st=2019-02-01T22%3A51%3A18Z&se=2019-03-04T22%3A56%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
