### PR TITLE
Team.primarychannel

### PR DESCRIPTION
**Pull request by nkramer**

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[6935171](https://github.com/microsoftgraph/microsoft-graph-docs/pull/4128/commits/693517169a104c43e4260bedbe0e8535019eb6ab)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 26 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[6935171](https://github.com/microsoftgraph/microsoft-graph-docs/pull/4128/commits/693517169a104c43e4260bedbe0e8535019eb6ab)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/microsoftgraph/microsoft-graph-docs, working directory: W:\ji0t-s, target branch: master, target branch commit: c50aa98f148d65a2aca707177f8a299e4aea2ef7, source branch: nkramer-primarychannel, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903092010599989-4128%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=kK88vRLAvvXrV1CpFjDqqouzt5x%2B9MujdRsBdFGzCe8%3D&st=2019-03-09T20%3A07%3A01Z&se=2019-04-09T20%3A12%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[fc4cda2](https://github.com/microsoftgraph/microsoft-graph-docs/pull/4128/commits/fc4cda253b0e38f44c36069194d2fd0ffd453116)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/microsoftgraph/microsoft-graph-docs, working directory: W:\43gp-s, target branch: master, target branch commit: 724643f3b3c3a19ee109797a48ca6a011ade5eb3, source branch: nkramer-primarychannel, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903252201008894-4128%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=54RVSe7DLONkKKERyX%2FyYWI17H0zPdlHQfaUtE0Sdos%3D&st=2019-03-25T21%3A56%3A53Z&se=2019-04-25T22%3A01%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
@nkramer , @clearab , can we merge this PR? The new property is live in beta.

**Pull request merged**
