### PR TITLE
Update user_list_owneddevices.md [Permission for native apps]

### PR DESCRIPTION
**Pull request by magickaichen**
Added the permission requirement for native apps, this api will not work until Directory.AccessAsUser.All is granted.

### CODE REVIEW

**Comment by magickaichen** [comment]
Are you guys gonna review this simple PR?

**Comment by magickaichen** [comment]
Thanks!

**Comment by magickaichen** [comment]
So it's already February and no one wants to look at it....

**Comment by PatAltimore** [comment]
@magickaichen Sorry for the delay in reviewing your contribution. I checked the permissions. For delegated, there is a mistake in the list of permissions.  From least to most privileged it would be Directory.Read.All, Directory.ReadWrite.All, Directory.AccessAsUser.All.

Directory.AccessAsUser.All isn't always required. You can use Directory.Read.All, or Directory.ReadWrite.All.

Therefore, the note wouldn't be accurate.  If you want to remove User.Read.All, User.ReadWrite.All from delegated and application permissions, I can accept that contribution.

Or you can close the PR and I can make the change if you like.

Thanks again,
Pat

**Comment by magickaichen** [comment]
I removed incorrect permissions and also removed the note since it is not accurate anymore, let me know if I need to change anything else, thanks!

**Pull request merged**
