### PR TITLE
adding support for resetRedemption on v1.0

### PR DESCRIPTION
**Pull request by aybankaMSFT**
updating files for adding support for resetRedemption on v1.0

Schema PR: 6929725
The schema changes are live @ the time of reviewing this docs PR.

### CODE REVIEW

**Comment by Lauragra** [comment]
@aybankaMSFT , please follow the Get started steps to set yourself up to be a contributor to the repo, and follow our content workflow. When you're ready for us to review this PR, please set the ready for content review label.

https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211776/Get-started

**Comment by aybankaMSFT** [comment]
@Lauragra all engineering items are ready, I have updated the tag as ready for review. Please review and merge if everything else looks good. thanks

**Comment by aybankaMSFT** [comment]
closed by mistake. hence re-opened.

**Review by FaithOmbongi — APPROVED** [review]
Thank you @aybankaMSFT for your work on this PR. Approved for merge.
I see both the schema and API are live. If you're ready to publish these docs, replace the **do not merge** label with the **ready to merge** and the PR will be merged @ EOD.

**Pull request merged**
