### PR TITLE
Update group.md

### PR DESCRIPTION
**Pull request by yyuank**

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[101bbfe](https://github.com/yyuank/microsoft-graph-docs/pull/3795/commits/101bbfe17e0d24dede3824b685b7bd086329737f)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[101bbfe](https://github.com/yyuank/microsoft-graph-docs/pull/3795/commits/101bbfe17e0d24dede3824b685b7bd086329737f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/group.md](https://github.com/yyuank/microsoft-graph-docs/blob/patch-1/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901160115342729-3795%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=W9SGf3pPpMDkypnI7wBtDfsXa9SxS06hDY0UvHursWc%3D&st=2019-01-16T01%3A13%3A38Z&se=2019-02-16T01%3A18%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
@yyuank , is this new property now in the schema? Please set the appropriate tag to indicate whether this PR is ready to merge. Thanks.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[bbd8199](https://github.com/yyuank/microsoft-graph-docs/pull/3795/commits/bbd81996414b52b6a73ab3541b630b08a01a67d8)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[bbd8199](https://github.com/yyuank/microsoft-graph-docs/pull/3795/commits/bbd81996414b52b6a73ab3541b630b08a01a67d8)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[bbd8199](https://github.com/yyuank/microsoft-graph-docs/pull/3795/commits/bbd81996414b52b6a73ab3541b630b08a01a67d8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/group.md](https://github.com/yyuank/microsoft-graph-docs/blob/patch-1/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901162344265070-3795%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=O5BeQZquGqYrAIkQxuFUXt%2Bwskj0Sy3qKGK0Nd0yCNA%3D&st=2019-01-16T23%3A42%3A52Z&se=2019-02-16T23%3A47%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
