### PR TITLE
Adding properties from Beta to V1

### PR DESCRIPTION
**Pull request by anchandaAADGraph**
1. User properties
2. Transitive Members and MemberOf navigation

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[ad8eff6](https://github.com/anchandaAADGraph/microsoft-graph-docs/pull/3715/commits/ad8eff6cc886497baf9ab9106d161156ee889cf8)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 20 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[ad8eff6](https://github.com/anchandaAADGraph/microsoft-graph-docs/pull/3715/commits/ad8eff6cc886497baf9ab9106d161156ee889cf8)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[ad8eff6](https://github.com/anchandaAADGraph/microsoft-graph-docs/pull/3715/commits/ad8eff6cc886497baf9ab9106d161156ee889cf8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/device_list_transitivememberof.md](https://github.com/anchandaAADGraph/microsoft-graph-docs/blob/v1_mappings/api-reference/v1.0/api/device_list_transitivememberof.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fv1.0%2Fapi%2Fdevice_list_transitivememberof.md)
[api-reference/v1.0/api/group_list_transitivememberof.md](https://github.com/anchandaAADGraph/microsoft-graph-docs/blob/v1_mappings/api-reference/v1.0/api/group_list_transitivememberof.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fv1.0%2Fapi%2Fgroup_list_transitivememberof.md)
[api-reference/v1.0/api/group_list_transitivemembers.md](https://github.com/anchandaAADGraph/microsoft-graph-docs/blob/v1_mappings/api-reference/v1.0/api/group_list_transitivemembers.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fv1.0%2Fapi%2Fgroup_list_transitivemembers.md)
[api-reference/v1.0/api/user_list_transitivememberof.md](https://github.com/anchandaAADGraph/microsoft-graph-docs/blob/v1_mappings/api-reference/v1.0/api/user_list_transitivememberof.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fv1.0%2Fapi%2Fuser_list_transitivememberof.md)
[api-reference/v1.0/resources/user.md](https://github.com/anchandaAADGraph/microsoft-graph-docs/blob/v1_mappings/api-reference/v1.0/resources/user.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fv1.0%2Fresources%2Fuser.md)
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/anchandaAADGraph/microsoft-graph-docs/blob/v1_mappings/api-reference/v1.0/api/group-list-memberof.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/group-list-members.md](https://github.com/anchandaAADGraph/microsoft-graph-docs/blob/v1_mappings/api-reference/v1.0/api/group-list-members.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/device.md](https://github.com/anchandaAADGraph/microsoft-graph-docs/blob/v1_mappings/api-reference/v1.0/resources/device.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/group.md](https://github.com/anchandaAADGraph/microsoft-graph-docs/blob/v1_mappings/api-reference/v1.0/resources/group.md) | :white_check_mark:Succeeded | |

<a name="api-reference%2Fv1.0%2Fapi%2Fdevice_list_transitivememberof.md"></a>
### [api-reference/v1.0/api/device_list_transitivememberof.md](https://github.com/anchandaAADGraph/microsoft-graph-docs/blob/v1_mappings/api-reference/v1.0/api/device_list_transitivememberof.md)
 - **Line 9**: **[Warning]** Invalid file link:(~/../concepts/permissions_reference.md).

<a name="api-reference%2Fv1.0%2Fapi%2Fgroup_list_transitivememberof.md"></a>
### [api-reference/v1.0/api/group_list_transitivememberof.md](https://github.com/anchandaAADGraph/microsoft-graph-docs/blob/v1_mappings/api-reference/v1.0/api/group_list_transitivememberof.md)
 - **Line 9**: **[Warning]** Invalid file link:(~/../concepts/permissions_reference.md).
 - **Line 24**: **[Warning]** Invalid file link:(~/../concepts/query_parameters.md).

<a name="api-reference%2Fv1.0%2Fapi%2Fgroup_list_transitivemembers.md"></a>
### [api-reference/v1.0/api/group_list_transitivemembers.md](https://github.com/anchandaAADGraph/microsoft-graph-docs/blob/v1_mappings/api-reference/v1.0/api/group_list_transitivemembers.md)
 - **Line 9**: **[Warning]** Invalid file link:(~/../concepts/permissions_reference.md).
 - **Line 29**: **[Warning]** Invalid file link:(~/../concepts/query_parameters.md).

<a name="api-reference%2Fv1.0%2Fapi%2Fuser_list_transitivememberof.md"></a>
### [api-reference/v1.0/api/user_list_transitivememberof.md](https://github.com/anchandaAADGraph/microsoft-graph-docs/blob/v1_mappings/api-reference/v1.0/api/user_list_transitivememberof.md)
 - **Line 9**: **[Warning]** Invalid file link:(~/../concepts/permissions_reference.md).

<a name="api-reference%2Fv1.0%2Fresources%2Fuser.md"></a>
### [api-reference/v1.0/resources/user.md](https://github.com/anchandaAADGraph/microsoft-graph-docs/blob/v1_mappings/api-reference/v1.0/resources/user.md)
 - **Line 116**: **[Warning]** Invalid file link:(~/v1.0/api/user_invalidateallrefreshtokens.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901030016508161-3715%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=1VMJ7Fo0lnDbdeD2Nii37%2BPXuBl9pFvxyVsfkNJFqtM%3D&st=2019-01-03T00%3A15%3A03Z&se=2019-02-03T00%3A20%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[e69b426](https://github.com/anchandaAADGraph/microsoft-graph-docs/pull/3715/commits/e69b426fe373e0dc17abaa6f08e29140ee2a0098)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 20 sec(s)_

**Comment by anchandaAADGraph** [comment]
Creating new one,

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[e69b426](https://github.com/anchandaAADGraph/microsoft-graph-docs/pull/3715/commits/e69b426fe373e0dc17abaa6f08e29140ee2a0098)_: 

### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified commit because branch heads/49fa042e42f1bb39a321342600a01f49/v1_mappings has been deleted or has been force pushed: fatal: Could not parse object &#39;e69b426fe373e0dc17abaa6f08e29140ee2a0098&#39;.


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901032312457864-3715%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=7w%2FKIsP0BUqiEIJduDfaTqsfMwrISQrAVubNaKUsK%2F0%3D&st=2019-01-03T23%3A08%3A38Z&se=2019-02-03T23%3A13%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
