### PR TITLE
new doc

### PR DESCRIPTION
**Pull request by mecampos**
Graph Connectors /beta environment changes

### CODE REVIEW

**Review by angelgolfer-ms — COMMENTED** [review]
@mecampos , when your PR is ready for content review, please follow this process and set the label content review: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103181/Content-workflow
If you'd like me to review, please assign me as a reviewer, and please ping me on Teams :-)
For now to keep the "Reviewers" and "Labels" fields of the PR in sync and unambiguous, I've removed myself from "Reviewers".
Cc @lramosvea .

**Comment by lramosvea** [comment]
Hi @mecampos what is the status of this PR? Is it still work in progress? Thanks

**Comment by mecampos** [comment]
Closing PR.

**Comment by mecampos** [comment]
Hi,

It is still work in progress, but we are not planning on merging it soon, so I closed this PR for now.
We'll reopen it if needed.

Best,

Melissa Campos
she/her
Content Developer
Office: +506 4114 2639
***@***.******@***.***>

[Microsoft Logo]

**Pull request closed without merging**
