### PR TITLE
Updated get list to include get list by title

### PR DESCRIPTION
**Pull request by frankchen76**
Per conversation with Jeremy Thake from our FTE "Microsoft Graph Field Community", I updated the list get with list title for v1.0 and beta version.

### CODE REVIEW

**Comment by jthake-msft** [comment]
@frankchen76  the snippets are autogenerated. @andrueastman can you take a look to see whether the re-generation will fix this?

@JeremyKelley do you agree on these changes?

**Comment by andrueastman** [comment]
@jthake-msft Yes. Any disrepancies/issues will be fixed on regeneration once this goes in.

**Comment by Lauragra** [comment]
@jthake-msft , @darrelmiller , are we okay to merge this PR?

**Comment by jthake-msft** [comment]
@JeremyKelley  i believe you'd have to bless this as SharePoint PM?

@darrelmiller  @andrueastman we auto gen the snippets so should we ask for the snippet files to be removed in this instance?

**Comment by Lauragra** [comment]
@frankchen76 , can you please remove the snippet files that are included in this PR? Thanks.

**Pull request closed without merging**
