### PR TITLE
Update changelog for planner api

### PR DESCRIPTION
**Pull request by dianambb**
Update changelog for planner api

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[640bae2](https://github.com/dianambb/microsoft-graph-docs/pull/4030/commits/640bae2c1e72b25bd8e6ee92f2f6d0586eb276c4)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 25 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[640bae2](https://github.com/dianambb/microsoft-graph-docs/pull/4030/commits/640bae2c1e72b25bd8e6ee92f2f6d0586eb276c4)_: 

:clock10: **Incremental building**: average incremental building time is _2 min(s) 3 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[640bae2](https://github.com/dianambb/microsoft-graph-docs/pull/4030/commits/640bae2c1e72b25bd8e6ee92f2f6d0586eb276c4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/dianambb/microsoft-graph-docs/blob/master/concepts/changelog.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902222342412581-4030%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=oYcOTrDfi9o5TWLydqWkFwisShk3P9tXcsNgkt7Ocvk%3D&st=2019-02-22T23%3A41%3A08Z&se=2019-03-25T23%3A46%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
@angelgolfer-ms  @Lauragra  this is the PR that i suggested adding information to the resource object of its formerly known name so more discoverer than just the change log.

**Comment by dianambb** [comment]
There is no user visible change so there is not update to the docs

**Comment by angelgolfer-ms** [comment]
> There is no user visible change so there is not update to the docs

@dianambb , can you please clarify what the API-level change is then?
We got the impression from this PR that a property was renamed, which isn't the case.

Also, FYI, within a section that represents the changes for a month (e.g., February 2019), the order of the subsections should follow in alphabetical order, not LIFO.
I am going to let you reorder the subsections under the February section, so as not to create a merge conflict for you. That is, please move the "OneNote" subsection to before the "Outlook calendar" subsection. Then please place your "Planner API" subsection after the "Outlook calendar" section. Thanks.

**Comment by dianambb** [comment]
@angelgolfer-ms , The asg:workloadName was set to "userDetail" for plannerUser. This is an internal name used by asg which is not exposed to the user.
I shall reorder the subsections.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[0f7842b](https://github.com/dianambb/microsoft-graph-docs/pull/4030/commits/0f7842b289d8d0aeba1833e6229cf70209f299fb)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 25 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[0f7842b](https://github.com/dianambb/microsoft-graph-docs/pull/4030/commits/0f7842b289d8d0aeba1833e6229cf70209f299fb)_: 

:clock10: **Incremental building**: average incremental building time is _2 min(s) 3 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[0f7842b](https://github.com/dianambb/microsoft-graph-docs/pull/4030/commits/0f7842b289d8d0aeba1833e6229cf70209f299fb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/dianambb/microsoft-graph-docs/blob/master/concepts/changelog.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902281954163819-4030%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=KSvjf7Gvws5cLLQkwfWlg2DcasBYnz9moOa%2BT9qeEhE%3D&st=2019-02-28T19%3A52%3A40Z&se=2019-03-31T19%3A57%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[bbe1ede](https://github.com/dianambb/microsoft-graph-docs/pull/4030/commits/bbe1ede67068bfedf4b3bb071aec96aa310f46c0)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 25 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[bbe1ede](https://github.com/dianambb/microsoft-graph-docs/pull/4030/commits/bbe1ede67068bfedf4b3bb071aec96aa310f46c0)_: 

:clock10: **Incremental building**: average incremental building time is _2 min(s) 3 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[bbe1ede](https://github.com/dianambb/microsoft-graph-docs/pull/4030/commits/bbe1ede67068bfedf4b3bb071aec96aa310f46c0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/dianambb/microsoft-graph-docs/blob/master/concepts/changelog.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902282305533046-4030%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=nXp1%2BACD89153lOCOgEUJjNcCFOpNj%2BLkcKJtR%2FT8Uo%3D&st=2019-02-28T23%3A04%3A15Z&se=2019-03-31T23%3A09%3A15Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[ac71eb8](https://github.com/dianambb/microsoft-graph-docs/pull/4030/commits/ac71eb8b484f6ac0e8b8a2e355dce60a657fb66c)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 25 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[ac71eb8](https://github.com/dianambb/microsoft-graph-docs/pull/4030/commits/ac71eb8b484f6ac0e8b8a2e355dce60a657fb66c)_: 

:clock10: **Incremental building**: average incremental building time is _2 min(s) 3 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[ac71eb8](https://github.com/dianambb/microsoft-graph-docs/pull/4030/commits/ac71eb8b484f6ac0e8b8a2e355dce60a657fb66c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/dianambb/microsoft-graph-docs/blob/master/concepts/changelog.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902282323411735-4030%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=a15qnwOZilfDFM7wBjRZeqhGNFK%2BUq1iGYTtOpSrhEI%3D&st=2019-02-28T23%3A22%3A06Z&se=2019-03-31T23%3A27%3A06Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
