### PR TITLE
Update rest.md

### PR DESCRIPTION
**Pull request by brianharwell**
grant_type should be `authorization_code` otherwise the error is `AADSTS70003: The access grant 'code' is not supported`

### CODE REVIEW

**Comment by jthake** [comment]
@mtillman could you just double check this is correct? As this is a concept doc in Auth I wanted to make sure.

**Comment by mtillman** [comment]
@jthake This looks correct per our docs here: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-protocols-oauth-code#use-the-authorization-code-to-request-an-access-token.

**Comment by Lauragra** [comment]
@jthake-msft , do we still want to merge this PR? We'll need to close it and recreate a new one if so.

**Comment by Lauragra** [comment]
Closing this PR as it is out of date and failing validation.

**Pull request closed without merging**
