### PR TITLE
Update changelog.md

### PR DESCRIPTION
**Pull request by yyuank**

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[c65f66f](https://github.com/yyuank/microsoft-graph-docs/pull/3797/commits/c65f66f5870c4a00e6e2f32db772986d9996cabe)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[c65f66f](https://github.com/yyuank/microsoft-graph-docs/pull/3797/commits/c65f66f5870c4a00e6e2f32db772986d9996cabe)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[c65f66f](https://github.com/yyuank/microsoft-graph-docs/pull/3797/commits/c65f66f5870c4a00e6e2f32db772986d9996cabe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/yyuank/microsoft-graph-docs/blob/patch-2/concepts/changelog.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901160334050185-3797%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Rjnyn425vlGBqv2ym4UH2OnyVIfRzjtNJXdiP0cdihU%3D&st=2019-01-16T03%3A32%3A13Z&se=2019-02-16T03%3A37%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by yyuank** [comment]
@Lauragra Here's the entry for changelog for the new property. #sign-off

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[ea19836](https://github.com/yyuank/microsoft-graph-docs/pull/3797/commits/ea19836d77e0a4a24bbab0aa3af2d5fffe0f39ef)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[ea19836](https://github.com/yyuank/microsoft-graph-docs/pull/3797/commits/ea19836d77e0a4a24bbab0aa3af2d5fffe0f39ef)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[ea19836](https://github.com/yyuank/microsoft-graph-docs/pull/3797/commits/ea19836d77e0a4a24bbab0aa3af2d5fffe0f39ef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/yyuank/microsoft-graph-docs/blob/patch-2/concepts/changelog.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901162355289218-3797%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=YpaNRSrPafQRDpJqr%2BnMUZpuf5dTsygF1wreLselGDg%3D&st=2019-01-16T23%3A53%3A55Z&se=2019-02-16T23%3A58%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
