### PR TITLE
Replace all Excel-related permissions tables with new read/write table

### PR DESCRIPTION
**Pull request by Jackson-Woods**
- Replaced all Excel-related permissions tables with full read/write tables
- Still need to remove all Read permissions from POST/PATCH/DELETE reference pages

### CODE REVIEW

**Comment by grangeryy** [comment]
@Lauragra could you help to review on this for excel permission modification :)

**Comment by Jackson-Woods** [comment]
@grangeryy Just got assigned this issue, can you confirm correct MSA behavior? https://github.com/microsoftgraph/microsoft-graph-docs/issues/8662#event-3426347122

In our permissions reference doc we mark Files.Read.All and Files.ReadWrite.All as supported for MSA. Is this incorrect? If so we need to fix the PR to remove those permissions from all MSA lines in the tables and also correct the permissions ref doc.

**Comment by Lauragra** [comment]
> @grangeryy Just got assigned this issue, can you confirm correct MSA behavior? [#8662 (comment)](https://github.com/microsoftgraph/microsoft-graph-docs/issues/8662#event-3426347122)
> 
> In our permissions reference doc we mark Files.Read.All and Files.ReadWrite.All as supported for MSA. Is this incorrect? If so we need to fix the PR to remove those permissions from all MSA lines in the tables and also correct the permissions ref doc.

@grangeryy , following up; do we need to make changes to this PR?

**Comment by Jackson-Woods** [comment]
@grangeryy It would be great to get these updates merged. Do you know what the correct permissions for MSA scenarios are and whether changes are needed?

**Pull request closed without merging**
