### PR TITLE
Demo/examples headers

### PR DESCRIPTION
**Pull request by lleonard-msft**
This is an example for demo/discussion purposes.  #hold-off

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[b75a84c](https://github.com/lleonard-msft/microsoft-graph-docs/pull/3731/commits/b75a84c65cb7607829ccc54a9f639db3ae550752)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 20 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[b75a84c](https://github.com/lleonard-msft/microsoft-graph-docs/pull/3731/commits/b75a84c65cb7607829ccc54a9f639db3ae550752)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[b75a84c](https://github.com/lleonard-msft/microsoft-graph-docs/pull/3731/commits/b75a84c65cb7607829ccc54a9f639db3ae550752)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.gitignore](https://github.com/lleonard-msft/microsoft-graph-docs/blob/demo/examples-headers/.gitignore) | :white_check_mark:Succeeded | |
[api-reference/beta/api/group-post-groups.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/demo/examples-headers/api-reference/beta/api/group-post-groups.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/message-update.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/demo/examples-headers/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/user-reminderview.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/demo/examples-headers/api-reference/beta/api/user-reminderview.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/contentTypeInfo.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/demo/examples-headers/api-reference/beta/resources/contentTypeInfo.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/event.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/demo/examples-headers/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/message.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/demo/examples-headers/api-reference/beta/resources/message.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/riskyuser.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/demo/examples-headers/api-reference/beta/resources/riskyuser.md) | :white_check_mark:Succeeded | |
[api-reference/beta/toc.yml](https://github.com/lleonard-msft/microsoft-graph-docs/blob/demo/examples-headers/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/message-update.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/demo/examples-headers/api-reference/v1.0/api/message-update.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/api/user-reminderview.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/demo/examples-headers/api-reference/v1.0/api/user-reminderview.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/event.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/demo/examples-headers/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/message.md](https://github.com/lleonard-msft/microsoft-graph-docs/blob/demo/examples-headers/api-reference/v1.0/resources/message.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/toc.yml](https://github.com/lleonard-msft/microsoft-graph-docs/blob/demo/examples-headers/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901071940091044-3731%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=skpET8KtrrdJa8h7htY%2FwaiASCjn5G1HaStyKjtxBGY%3D&st=2019-01-07T19%3A40%3A36Z&se=2019-02-07T19%3A45%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lleonard-msft** [comment]
This was intended as a visual aid for internal discussion.

Now that the discussion has taken place, there's no reason to keep (or merge) the PR.  Closing.

**Pull request closed without merging**
