### PR TITLE
Fix the invalid sample json

### PR DESCRIPTION
**Pull request by tony-xia**
Modify the sample json to make it valid

### CODE REVIEW

**Comment by jthake-msft** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamstab_list.md](https://github.com/tony-xia/microsoft-graph-docs/blob/invalid-sample-json/api-reference/beta/api/teamstab_list.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fteamstab_list.md)

<a name="api-reference%2Fbeta%2Fapi%2Fteamstab_list.md"></a>
### [api-reference/beta/api/teamstab_list.md](https://github.com/tony-xia/microsoft-graph-docs/blob/invalid-sample-json/api-reference/beta/api/teamstab_list.md)
 - **Line 8**: **[Warning]** Invalid file link:(~/../concepts/permissions_reference.md).
 - **Line 24**: **[Warning]** Invalid file link:(~/../concepts/query_parameters.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201811202351254480-3451%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=d03K9%2FMBDq9EWI%2ByJcKneBjlQbpSmMd9egvcbF2mNb8%3D&st=2018-11-20T23%3A49%3A16Z&se=2018-12-21T23%3A54%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by tony-xia** [comment]
@jthake-msft thanks for your feedback. I updated this doc in v1.0 as well.

**Comment by jthake-msft** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamstab_list.md](https://github.com/tony-xia/microsoft-graph-docs/blob/invalid-sample-json/api-reference/beta/api/teamstab_list.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fteamstab_list.md)
[api-reference/v1.0/api/teamstab_list.md](https://github.com/tony-xia/microsoft-graph-docs/blob/invalid-sample-json/api-reference/v1.0/api/teamstab_list.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fv1.0%2Fapi%2Fteamstab_list.md)

<a name="api-reference%2Fbeta%2Fapi%2Fteamstab_list.md"></a>
### [api-reference/beta/api/teamstab_list.md](https://github.com/tony-xia/microsoft-graph-docs/blob/invalid-sample-json/api-reference/beta/api/teamstab_list.md)
 - **Line 8**: **[Warning]** Invalid file link:(~/../concepts/permissions_reference.md).
 - **Line 24**: **[Warning]** Invalid file link:(~/../concepts/query_parameters.md).

<a name="api-reference%2Fv1.0%2Fapi%2Fteamstab_list.md"></a>
### [api-reference/v1.0/api/teamstab_list.md](https://github.com/tony-xia/microsoft-graph-docs/blob/invalid-sample-json/api-reference/v1.0/api/teamstab_list.md)
 - **Line 8**: **[Warning]** Invalid file link:(~/../concepts/permissions_reference.md).
 - **Line 24**: **[Warning]** Invalid file link:(~/../concepts/query_parameters.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201811210035091671-3451%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=2MeG4WGQ9fIVM7y3jGUPEQzYPgGG2NUF3ndbuwvUrgk%3D&st=2018-11-21T00%3A33%3A12Z&se=2018-12-22T00%3A38%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamstab_list.md](https://github.com/tony-xia/microsoft-graph-docs/blob/invalid-sample-json/api-reference/beta/api/teamstab_list.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fteamstab_list.md)
[api-reference/v1.0/api/teamstab_list.md](https://github.com/tony-xia/microsoft-graph-docs/blob/invalid-sample-json/api-reference/v1.0/api/teamstab_list.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fv1.0%2Fapi%2Fteamstab_list.md)

<a name="api-reference%2Fbeta%2Fapi%2Fteamstab_list.md"></a>
### [api-reference/beta/api/teamstab_list.md](https://github.com/tony-xia/microsoft-graph-docs/blob/invalid-sample-json/api-reference/beta/api/teamstab_list.md)
 - **Line 8**: **[Warning]** Invalid file link:(~/../concepts/permissions_reference.md).
 - **Line 24**: **[Warning]** Invalid file link:(~/../concepts/query_parameters.md).

<a name="api-reference%2Fv1.0%2Fapi%2Fteamstab_list.md"></a>
### [api-reference/v1.0/api/teamstab_list.md](https://github.com/tony-xia/microsoft-graph-docs/blob/invalid-sample-json/api-reference/v1.0/api/teamstab_list.md)
 - **Line 8**: **[Warning]** Invalid file link:(~/../concepts/permissions_reference.md).
 - **Line 24**: **[Warning]** Invalid file link:(~/../concepts/query_parameters.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201811210036191341-3451%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=RUy8byf72dMLECgXQQGpQ%2FkKTEbBW8H7qH%2BAo9XZQkQ%3D&st=2018-11-21T00%3A36%3A16Z&se=2018-12-22T00%3A41%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
