### PR TITLE
Update serviceprincipal-list-transitivememberof.md

### PR DESCRIPTION
**Pull request by eketo-msft**

### CODE REVIEW

**Comment by Lauragra** [comment]
@eketo-msft , can you please ad an entry for this operation to the TOC? Also, are you okay merging this update to the examples now and waiting until Tuesday for the update to the SDK snippets?

**Comment by eketo-msft** [comment]
> @eketo-msft , can you please ad an entry for this operation to the TOC? Also, are you okay merging this update to the examples now and waiting until Tuesday for the update to the SDK snippets?

Yeah, @Lauragra are you okay with TOC/SDK snippets on Tuesday and just examples now?

**Comment by eketo-msft** [comment]
@Lauragra , where can I find out how the SDK snippet generator works?  What does the snippet pipeline trigger off of?

**Comment by Lauragra** [comment]
@eketo-msft , I think that's okay. Here's the info about the code snippets: https://msgo.azurewebsites.net/add/document/guidelines/generate-code-snippets.html

**Pull request merged**
