### PR TITLE
Only list for  Intune's deviceHealthScriptDeviceState

### PR DESCRIPTION
**Pull request by mestew**
Only list method is supported for Intune's deviceHealthScriptDeviceState entity. Edit TOC to reflect removed md files.

Tagging @zhushanms on this PR for review of removing these items too.

### CODE REVIEW

**Comment by davidmu1** [comment]
Unfortunately, PR's against the Intune documentation do not work. The content comes from engineering each month and totally overwrites any changes. Please contact @jaiprakashmb to make changes to Intune documentation.

**Comment by jaiprakashmb** [comment]
> Unfortunately, PR's against the Intune documentation do not work. The content comes from engineering each month and totally overwrites any changes. Please contact @jaiprakashmb to make changes to Intune documentation.

Sure @mestew / @davidmu1 Let me check and get back to you!

**Review by davidmu1 — CHANGES_REQUESTED** [review]
PM has been notified.

**Comment by mestew** [comment]
@jaiprakashmb I tossed you on the internal mail thread we had going about this one as an FYI. Thanks much.

**Pull request closed without merging**
