### PR TITLE
Intune app only auth perms doc update

### PR DESCRIPTION
**Pull request by davidmu1**

### CODE REVIEW

**Comment by davidmu1** [comment]
#sign-off

**Comment by Lauragra** [comment]
@davidmu1 , does this change merit a changelog update?

**Comment by davidmu1** [comment]
@Lauragra I do not think it does, just a clarification in permissions.

**Comment by Lauragra** [comment]
@davidmu1 , how is it a clarification? It looks like you're adding application permissions for Intune. That's generally something that we would call out to customers in the changelog.

**Comment by davidmu1** [comment]
@Lauragra I don't agree with what you are saying, but if you provide an example of the type of entry you think should be added, I will go ahead and add it.

**Comment by Lauragra** [comment]
We have entries in the changelog like this: 
Addition | Beta | Added delegated and application permissions for reading organizational contacts: OrgContact.Read.All

**Pull request merged**
