### PR TITLE
Update toc.yml

### PR DESCRIPTION
**Pull request by VinodRavichandran**
Added Call-keepalive in TOC FYI @Lauragra

### CODE REVIEW

**Comment by Lauragra** [comment]
@VinodRavichandran , we also have a PR to add the method to v1.0. Will you do the TOC update for that in a separate PR?

**Comment by VinodRavichandran** [comment]
@ananmishr , @paywuAtMicrosoft  - Can you please update/add keep-alive in the toc file for v1 and include it in your PR?

**Comment by Lauragra** [comment]
@VinodRavichandran , is this the TOC update you're looking for? We overlooked this one when I merged the keepAlive PR: https://github.com/microsoftgraph/microsoft-graph-docs/pull/6465/files

**Comment by VinodRavichandran** [comment]
@Lauragra No, I this is beta, I was responding to your comment above about v1

> @VinodRavichandran , we also have a PR to add the method to v1.0. Will you do the TOC update for that in a separate PR?

**Comment by Lauragra** [comment]
Looks like we already have the link in the beta TOC so closing this PR.

**Pull request closed without merging**
