### PR TITLE
alt key syntax v1 update

### PR DESCRIPTION
**Pull request by aricrowe57**

### CODE REVIEW

**Review by FaithOmbongi — CHANGES_REQUESTED** [review]
Hi @aricrowe57 - These changes look good. A few gaps: Please also update the rest of the application API docs, the service principal API docs, and add the changelog. You can refer to your beta PR https://github.com/microsoftgraph/microsoft-graph-docs/pull/17677/files for the template of the changelog to use (use different GUIDs for v1.0).

**Comment by aricrowe57** [comment]
@FaithOmbongi - addressed comments.  I'm not the PM for the service principal changes, and looks like they're already in V1 anyways.  Can you review and merge?  Thanks!

**Review by FaithOmbongi — APPROVED** [review]
LGTM. Please let me know the service principals feature owner so I can follow up with them on their documentation.

**Review by FaithOmbongi — APPROVED** [review]

**Comment by aricrowe57** [comment]
@FaithOmbongi , are there any other steps I need to do to get this merged?

**Pull request merged**
