### PR TITLE
Update registrykeystate.md

### PR DESCRIPTION
**Pull request by edwardkoval**

### CODE REVIEW

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[2836a18](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3978/commits/2836a1887c5a8253e9ddaa9b8447a23f2c3089ca)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 24 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[2836a18](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3978/commits/2836a1887c5a8253e9ddaa9b8447a23f2c3089ca)_: 

:clock10: **Incremental building**: average incremental building time is _2 min(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[2836a18](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3978/commits/2836a1887c5a8253e9ddaa9b8447a23f2c3089ca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/registrykeystate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edwardkoval-patch-1/api-reference/beta/resources/registrykeystate.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902131634206994-3978%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=uxVzrlenEVh1llJbrbR07ZOlurM1UsgYbZnmqrp7EFE%3D&st=2019-02-13T16%3A32%3A48Z&se=2019-03-16T16%3A37%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[28e094b](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3978/commits/28e094bad745cbb61a1b927ce28067ae69b76f37)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 24 sec(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[28e094b](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3978/commits/28e094bad745cbb61a1b927ce28067ae69b76f37)_: 

:clock10: **Incremental building**: average incremental building time is _2 min(s)_

**Comment by jthake-msft** [comment]
OPS Build status updates of commit _[28e094b](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3978/commits/28e094bad745cbb61a1b927ce28067ae69b76f37)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/registrykeystate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edwardkoval-patch-1/api-reference/beta/resources/registrykeystate.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902131815470754-3978%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=cO7a3oSeUQ1WL4I7TEd2ie8Nc%2BYNPxTxK%2BJ48gk%2FL%2Fg%3D&st=2019-02-13T18%3A14%3A25Z&se=2019-03-16T18%3A19%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by edwardkoval** [comment]
This is a fix for a typo that a customer has pointed out to us.

**Pull request merged**
